import { t } from './catalog-types'
import type { CatalogTool } from './catalog-types'

const tools: CatalogTool[] = [

  // ── Généraliste (15) ────────────────────────────────────────────────────────
  t('chatgpt','ChatGPT','Le chatbot IA le plus utilisé au monde','generaliste','',
    'freemium','Gratuit · GPT-4o à 20 $/mois',
    ['chatbot','assistant','texte','rédaction','code'],4.9,'https://chat.openai.com','🤖','#10a37f',18500,'200M+',true),
  t('claude-ai','Claude','L\'assistant IA conversationnel d\'Anthropic','generaliste','',
    'freemium','Gratuit · Pro à 20 $/mois',
    ['chatbot','assistant','analyse','rédaction','code'],4.8,'https://claude.ai','🟠','#d97757',12400,'30M+',true),
  t('gemini','Gemini','L\'IA multimodale de Google','generaliste','',
    'freemium','Gratuit · Advanced à 21,99 €/mois',
    ['chatbot','multimodal','image','recherche','google'],4.7,'https://gemini.google.com','✨','#4285f4',11200,'100M+',true),
  t('mistral-ai','Mistral AI','Modèles open source haute performance','generaliste','',
    'freemium','Gratuit · API dès 0,02 $/M tokens',
    ['modèle','open source','api','europe','performance'],4.6,'https://mistral.ai','🌬','#ff7000',6800,'5M+'),
  t('perplexity','Perplexity AI','Moteur de réponse IA avec sources citées','generaliste','',
    'freemium','Gratuit · Pro à 20 $/mois',
    ['recherche','sources','web','résumé','answers'],4.7,'https://perplexity.ai','🔍','#20b2aa',9300,'15M+',true),
  t('microsoft-copilot','Microsoft Copilot','L\'assistant IA intégré à l\'écosystème Microsoft','generaliste','',
    'freemium','Gratuit · Microsoft 365 à 6 €/mois',
    ['microsoft','office','productivité','chatbot','bing'],4.5,'https://copilot.microsoft.com','🪟','#0078d4',8700,'100M+'),
  t('deepseek','DeepSeek','Modèle IA open source très performant','generaliste','',
    'free','Gratuit en ligne et API',
    ['open source','modèle','code','raisonnement','chine'],4.5,'https://chat.deepseek.com','🌊','#4b6bfb',7200,'10M+'),
  t('grok','Grok','L\'assistant IA d\'Elon Musk intégré à X','generaliste','',
    'freemium','Gratuit sur X · Premium à 16 $/mois',
    ['x','twitter','actualités','humour','chatbot'],4.2,'https://grok.x.ai','⚡','#1da1f2',5400,'5M+'),
  t('meta-ai','Meta AI','L\'assistant IA de Meta disponible sur WhatsApp, Instagram','generaliste','',
    'free','Gratuit',
    ['meta','whatsapp','instagram','chatbot','image'],4.3,'https://meta.ai','🔵','#0082fb',6100,'100M+'),
  t('le-chat','Le Chat','Le chatbot de Mistral en français','generaliste','',
    'freemium','Gratuit · Pro disponible',
    ['français','europe','chatbot','mistral','vie privée'],4.5,'https://chat.mistral.ai','💬','#ff7000',4800,'2M+'),
  t('poe','Poe','Accès à tous les grands modèles IA en un seul endroit','generaliste','',
    'freemium','Gratuit · Pro à 19,99 $/mois',
    ['multi-modèle','chatbot','claude','gpt','gemini'],4.4,'https://poe.com','🎭','#8b5cf6',5600,'5M+'),
  t('you-com','You.com','Moteur de recherche IA avec assistant intégré','generaliste','',
    'freemium','Gratuit · Pro à 15 $/mois',
    ['recherche','moteur','chatbot','web','vie privée'],4.2,'https://you.com','🔎','#3b82f6',3900,'3M+'),
  t('pi-ai','Pi','L\'assistant IA personnel et bienveillant d\'Inflection','generaliste','',
    'free','Gratuit',
    ['personnel','coach','conversation','bienveillant','mobile'],4.3,'https://pi.ai','🥧','#ff6b35',3200,'1M+'),
  t('huggingchat','HuggingChat','Assistant IA open source de Hugging Face','generaliste','',
    'free','Gratuit',
    ['open source','huggingface','modèle','gratuit','api'],4.1,'https://huggingface.co/chat','🤗','#ffcc00',3500,'2M+'),
  t('inflection-ai','Inflection AI','IA émotionnellement intelligente pour usage personnel','generaliste','',
    'freemium','Gratuit · Premium disponible',
    ['personnel','entreprise','api','plateforme','modèle'],4.1,'https://inflection.ai','💡','#6366f1',2100,'500K+'),

  // ── Code (20) ───────────────────────────────────────────────────────────────
  t('github-copilot','GitHub Copilot','L\'assistant code IA de GitHub et Microsoft','code','',
    'freemium','Gratuit limité · Pro à 10 $/mois',
    ['code','completion','github','vscode','productivité'],4.8,'https://github.com/features/copilot','👾','#6e5494',14200,'1M+',true),
  t('cursor','Cursor','L\'éditeur de code propulsé par l\'IA','code','',
    'freemium','Gratuit · Pro à 20 $/mois',
    ['éditeur','code','vscode','ia','refactor'],4.9,'https://cursor.com','⚡','#000000',13500,'500K+',true),
  t('replit-ai','Replit','IDE en ligne avec IA intégrée','code','',
    'freemium','Gratuit · Core à 20 $/mois',
    ['ide','navigateur','déploiement','collaboration','code'],4.5,'https://replit.com','🔵','#f26207',7800,'20M+'),
  t('tabnine','Tabnine','Autocomplétion IA multilangage et sécurisée','code','',
    'freemium','Gratuit · Pro à 12 $/mois',
    ['completion','multilangage','sécurité','enterprise','ide'],4.5,'https://tabnine.com','🔮','#6c63ff',6200,'1M+'),
  t('codeium','Codeium','Extension IA gratuite pour développeurs','code','',
    'freemium','Gratuit · Teams à 12 $/mois',
    ['completion','gratuit','multilangage','vscode','jetbrains'],4.6,'https://codeium.com','🟢','#09b6a2',8100,'500K+'),
  t('bolt-new','Bolt.new','Générez et déployez des apps web avec l\'IA','code','',
    'freemium','Gratuit · Pro à 20 $/mois',
    ['no-code','génération','déploiement','react','fullstack'],4.7,'https://bolt.new','⚡','#ff6f00',9200,'1M+',true),
  t('v0-dev','v0 by Vercel','Génération de composants UI React par l\'IA','code','',
    'freemium','Gratuit · Pro à 20 $/mois',
    ['ui','react','composants','vercel','tailwind'],4.7,'https://v0.dev','▲','#000000',8600,'500K+'),
  t('windsurf','Windsurf','Éditeur de code IA de nouvelle génération par Codeium','code','',
    'freemium','Gratuit · Pro à 15 $/mois',
    ['éditeur','ia','codeium','agent','flow'],4.7,'https://codeium.com/windsurf','🏄','#3e63dd',7400,'200K+'),
  t('lovable-dev','Lovable','Transformez vos idées en apps web fonctionnelles','code','',
    'freemium','Gratuit · Pro à 20 $/mois',
    ['no-code','génération','app','react','supabase'],4.6,'https://lovable.dev','💜','#e64c9e',6700,'200K+'),
  t('devin-ai','Devin','Le premier ingénieur logiciel IA autonome','code','',
    'paid','À partir de 500 $/mois',
    ['agent','autonome','ingénieur','github','pr'],4.1,'https://cognition.ai','🤖','#6366f1',5200,'10K+'),
  t('sourcegraph','Sourcegraph Cody','Assistant IA pour explorer et comprendre le code','code','',
    'freemium','Gratuit · Enterprise disponible',
    ['code search','enterprise','compréhension','repo','ia'],4.4,'https://sourcegraph.com/cody','🔭','#ff5543',4100,'200K+'),
  t('askcodi','AskCodi','Assistant IA multi-IDE pour développeurs','code','',
    'freemium','Gratuit · Pro à 9,99 $/mois',
    ['completion','explication','test','documentation','multilangage'],4.2,'https://askcodi.com','💡','#7c3aed',2800,'100K+'),
  t('blackbox-ai','Blackbox AI','IA de code avec recherche et autocomplétion','code','',
    'freemium','Gratuit · Pro à 9,99 $/mois',
    ['completion','recherche','débogage','multilangage','vscode'],4.3,'https://blackbox.ai','⬛','#1a1a1a',4500,'3M+'),
  t('codiga','Codiga','Analyse statique et aide au code par l\'IA','code','',
    'freemium','Gratuit · Teams à 14 $/mois',
    ['analyse','sécurité','qualité','règles','ide'],4.0,'https://codiga.io','🛡','#ff6b6b',1900,'50K+'),
  t('safurai','Safurai','Assistant IA pour accélérer le développement','code','',
    'freemium','Gratuit · Pro disponible',
    ['completion','chat','refactoring','explication','vscode'],4.1,'https://safurai.com','🛡','#00b4d8',2300,'100K+'),
  t('continue-dev','Continue','Extension IA open source pour VS Code et JetBrains','code','',
    'free','Gratuit et open source',
    ['open source','extension','vscode','jetbrains','local'],4.4,'https://continue.dev','▶','#26c6da',3600,'100K+'),
  t('pieces-app','Pieces','Gestionnaire de snippets IA pour développeurs','code','',
    'freemium','Gratuit · Teams disponible',
    ['snippets','mémoire','contexte','workflow','ia'],4.3,'https://pieces.app','🧩','#ff7043',2700,'100K+'),
  t('stenography','Stenography','Génération automatique de documentation de code','code','',
    'freemium','Gratuit · Pro à 20 $/mois',
    ['documentation','docstring','auto','python','javascript'],4.0,'https://stenography.dev','📝','#f59e0b',1600,'30K+'),
  t('warp','Warp','Terminal moderne propulsé par l\'IA','code','',
    'freemium','Gratuit · Teams à 18 $/mois',
    ['terminal','cli','ia','productivité','shell'],4.6,'https://warp.dev','💻','#01a4a4',6300,'300K+'),

  // ── Image (20) ──────────────────────────────────────────────────────────────
  t('midjourney','Midjourney','Le générateur d\'images IA le plus créatif','image','',
    'paid','À partir de 10 $/mois',
    ['génération','art','créatif','discord','photo'],4.9,'https://midjourney.com','🎨','#000000',16800,'15M+',true),
  t('dalle-3','DALL-E 3','Générateur d\'images intégré à ChatGPT','image','',
    'freemium','Inclus dans ChatGPT Plus (20 $/mois)',
    ['génération','openai','chatgpt','réaliste','créatif'],4.7,'https://openai.com/dall-e-3','🖼','#10a37f',11400,'10M+'),
  t('stable-diffusion','Stable Diffusion','Modèle open source de génération d\'images','image','',
    'free','Gratuit et open source',
    ['open source','local','personnalisable','fine-tuning','gratuit'],4.5,'https://stability.ai','🌀','#6c4ab6',9800,'5M+'),
  t('adobe-firefly','Adobe Firefly','IA générative d\'Adobe intégrée à Creative Cloud','image','',
    'freemium','Inclus dans Creative Cloud (54,99 €/mois)',
    ['adobe','photoshop','illustrator','commercial','créatif'],4.6,'https://firefly.adobe.com','🔥','#ff0000',8700,'5M+'),
  t('leonardo-ai','Leonardo AI','Plateforme de génération d\'images IA professionnelle','image','',
    'freemium','Gratuit · Pro à 12 $/mois',
    ['génération','jeux','concept art','formation','tokens'],4.6,'https://leonardo.ai','🦁','#ff6900',7900,'2M+'),
  t('canva-ai','Canva AI','Design IA intégré dans Canva','image','',
    'freemium','Gratuit · Pro à 14,99 €/mois',
    ['design','templates','présentation','réseaux sociaux','facile'],4.7,'https://canva.com','🎨','#00c4cc',12300,'100M+',true),
  t('ideogram','Ideogram','Génération d\'images IA avec excellent rendu du texte','image','',
    'freemium','Gratuit · Pro à 8 $/mois',
    ['texte','typo','logo','affiche','génération'],4.5,'https://ideogram.ai','💭','#7c3aed',5400,'2M+'),
  t('flux-ai','Flux','Modèle de génération d\'images de Black Forest Labs','image','',
    'freemium','API disponible · intégré partout',
    ['modèle','haute qualité','réaliste','open source','api'],4.6,'https://blackforestlabs.ai','🌊','#4a90d9',4800,'1M+'),
  t('kling-ai','Kling AI','Générateur d\'images et vidéos IA de Kuaishou','image','',
    'freemium','Gratuit · Pro à 10 $/mois',
    ['génération','vidéo','image','chine','réaliste'],4.4,'https://kling.kuaishou.com','🎬','#1a1a2e',5100,'2M+'),
  t('runway-ml','Runway','La plateforme créative IA de référence','image','',
    'freemium','Gratuit · Standard à 12 $/mois',
    ['vidéo','image','génération','inpainting','créatif'],4.7,'https://runwayml.com','🛤','#000000',10200,'2M+',true),
  t('playground-ai','Playground AI','Générateur d\'images IA accessible et gratuit','image','',
    'freemium','Gratuit · Pro à 15 $/mois',
    ['génération','accessible','templates','flux','sd'],4.4,'https://playground.com','🎡','#ff6b6b',4200,'1M+'),
  t('nightcafe','NightCafe','Plateforme communautaire de création d\'art IA','image','',
    'freemium','Gratuit · Credits à partir de 7,99 $/mois',
    ['art','communauté','styles','modèles','créatif'],4.3,'https://nightcafe.studio','🌙','#1a1a2e',3700,'5M+'),
  t('artbreeder','Artbreeder','Créez des images uniques par interpolation IA','image','',
    'freemium','Gratuit · Pro à 8,99 $/mois',
    ['interpolation','portraits','paysages','créatif','génératif'],4.2,'https://artbreeder.com','🌱','#4ade80',3100,'5M+'),
  t('remove-bg','Remove.bg','Suppression automatique d\'arrière-plan par IA','image','',
    'freemium','Gratuit limité · API à partir de 0,20 $/image',
    ['background removal','photo','api','retouche','automatique'],4.7,'https://remove.bg','✂️','#26a65b',8900,'30M+'),
  t('clipdrop','Clipdrop','Suite d\'outils IA de retouche photo par Stability AI','image','',
    'freemium','Gratuit · Pro à 9 $/mois',
    ['retouche','background','upscale','inpainting','stability'],4.5,'https://clipdrop.co','📸','#7c3aed',5600,'10M+'),
  t('picsart-ai','Picsart AI','Éditeur photo et vidéo IA tout-en-un','image','',
    'freemium','Gratuit · Premium à 13 $/mois',
    ['retouche','filtre','collage','mobile','génération'],4.4,'https://picsart.com','🎨','#e91e8c',6700,'150M+'),
  t('fotor-ai','Fotor AI','Retouche et génération d\'images IA en ligne','image','',
    'freemium','Gratuit · Pro à 8,99 $/mois',
    ['retouche','génération','portrait','hdr','facile'],4.2,'https://fotor.com','📷','#1976d2',3400,'300M+'),
  t('pixlr-ai','Pixlr AI','Éditeur photo en ligne avec IA générative','image','',
    'freemium','Gratuit · Premium à 7,99 $/mois',
    ['retouche','navigateur','ia','suppression','fond'],4.1,'https://pixlr.com','🖌','#ef5350',2900,'100M+'),
  t('deep-dream','Deep Dream Generator','Art psychédélique par réseaux neuronaux','image','',
    'freemium','Gratuit · Advance à 19 $/mois',
    ['art','neuronal','psychédélique','style transfer','créatif'],4.0,'https://deepdreamgenerator.com','🌀','#9c27b0',2400,'5M+'),
  t('getimg-ai','Getimg.ai','Plateforme complète de génération et édition d\'images','image','',
    'freemium','Gratuit · Basic à 12 $/mois',
    ['génération','édition','modèles','api','inpainting'],4.4,'https://getimg.ai','🖼','#6366f1',3800,'500K+'),

  // ── Vidéo (15) ──────────────────────────────────────────────────────────────
  t('synthesia','Synthesia','Créez des vidéos avec avatars IA sans caméra','video','',
    'paid','Starter à 29 $/mois',
    ['avatars','formation','e-learning','présentateur','entreprise'],4.7,'https://synthesia.io','🎭','#6542e4',9200,'50K+',true),
  t('heygen','HeyGen','Génération de vidéos avec avatars IA réalistes','video','',
    'freemium','Gratuit limité · Creator à 29 $/mois',
    ['avatars','traduction','doublage','présentateur','réaliste'],4.7,'https://heygen.com','🎬','#ff6b35',8700,'500K+'),
  t('pika-labs','Pika','Générez des vidéos à partir de texte ou d\'images','video','',
    'freemium','Gratuit · Pro à 8 $/mois',
    ['text-to-video','image-to-video','créatif','génération','court'],4.5,'https://pika.art','🎥','#7c3aed',6300,'1M+'),
  t('sora','Sora','Générateur de vidéos réalistes d\'OpenAI','video','',
    'freemium','Inclus dans ChatGPT Plus (20 $/mois)',
    ['openai','réaliste','text-to-video','haute qualité','génération'],4.3,'https://openai.com/sora','🌀','#10a37f',5800,'1M+'),
  t('luma-ai','Luma AI','Génération de vidéos et effets 3D par IA','video','',
    'freemium','Gratuit · Pro à 29,99 $/mois',
    ['3d','nerf','vidéo','génération','dream machine'],4.5,'https://lumalabs.ai','💡','#ff4d6d',5400,'1M+'),
  t('invideo-ai','InVideo AI','Créateur de vidéos IA pour réseaux sociaux et marketing','video','',
    'freemium','Gratuit · Business à 30 $/mois',
    ['marketing','réseaux sociaux','templates','voix','automatique'],4.4,'https://invideo.io','📹','#3b82f6',4800,'7M+'),
  t('descript','Descript','Éditeur vidéo/audio IA qui édite comme un doc Word','video','',
    'freemium','Gratuit · Creator à 24 $/mois',
    ['édition','transcription','suppression silence','podcast','screencast'],4.6,'https://descript.com','✂️','#7c3aed',6100,'500K+'),
  t('capcut-ai','CapCut AI','Éditeur vidéo mobile et web boosté à l\'IA','video','',
    'freemium','Gratuit · Pro à 9,99 $/mois',
    ['mobile','tiktok','sous-titres','templates','effets'],4.6,'https://capcut.com','✂️','#000000',11200,'100M+'),
  t('veed-io','Veed.io','Suite complète d\'édition vidéo en ligne avec IA','video','',
    'freemium','Gratuit · Basic à 18 $/mois',
    ['sous-titres','traduction','transcription','édition','collaboratif'],4.5,'https://veed.io','🎬','#ffb703',5700,'1M+'),
  t('fliki-ai','Fliki','Texte vers vidéo avec voix IA et images','video','',
    'freemium','Gratuit · Standard à 28 $/mois',
    ['text-to-video','voix','images','blog','contenu'],4.3,'https://fliki.ai','💬','#7b2d8b',3600,'500K+'),
  t('pictory-ai','Pictory','Transformez articles et scripts en vidéos automatiquement','video','',
    'paid','Standard à 23 $/mois',
    ['blog-to-video','script','sous-titres','marketing','auto'],4.3,'https://pictory.ai','🖼','#ff4757',3200,'500K+'),
  t('steve-ai','Steve.ai','Création de vidéos animées et IA pour entreprises','video','',
    'paid','Basic à 20 $/mois',
    ['animation','entreprise','marketing','live action','ia'],4.1,'https://steve.ai','🎬','#ef5350',2700,'300K+'),
  t('haiper','Haiper','Génération de vidéos IA rapide et créative','video','',
    'freemium','Gratuit · Pro disponible',
    ['génération','créatif','text-to-video','rapide','effets'],4.2,'https://haiper.ai','⚡','#ff5722',2900,'200K+'),
  t('vidu-ai','Vidu AI','Générateur de vidéos IA de haute qualité','video','',
    'freemium','Gratuit · Pro disponible',
    ['génération','haute qualité','text-to-video','cinématique','ia'],4.1,'https://vidu.com','🎞','#1565c0',2100,'100K+'),
  t('wisecut','Wisecut','Montage automatique de vidéos longues par IA','video','',
    'freemium','Gratuit · Basic à 15 $/mois',
    ['montage auto','podcast','youtube','b-roll','transcription'],4.2,'https://wisecut.video','✂️','#00897b',2300,'100K+'),

  // ── Audio (15) ──────────────────────────────────────────────────────────────
  t('elevenlabs','ElevenLabs','Synthèse vocale IA ultra-réaliste et clonage de voix','audio','',
    'freemium','Gratuit · Starter à 5 $/mois',
    ['voix','synthèse','clonage','multilingue','tts'],4.9,'https://elevenlabs.io','🔊','#ff4d4d',13600,'1M+',true),
  t('suno-ai','Suno AI','Générez des chansons complètes avec paroles et musique','audio','',
    'freemium','Gratuit · Pro à 10 $/mois',
    ['musique','chanson','paroles','génération','créatif'],4.7,'https://suno.com','🎵','#ffd700',9800,'5M+',true),
  t('udio','Udio','Génération de musique IA de haute qualité','audio','',
    'freemium','Gratuit · Standard à 10 $/mois',
    ['musique','génération','qualité','paroles','créatif'],4.6,'https://udio.com','🎶','#7c3aed',7200,'1M+'),
  t('adobe-podcast','Adobe Podcast','Amélioration et transcription audio par IA','audio','',
    'freemium','Gratuit beta · Inclus dans Creative Cloud',
    ['podcast','amélioration','bruit','transcription','adobe'],4.6,'https://podcast.adobe.com','🎙','#ff0000',5300,'500K+'),
  t('murf-ai','Murf AI','Studio de voix IA pour créateurs de contenu','audio','',
    'freemium','Gratuit · Basic à 29 $/mois',
    ['voix','studio','présentateur','e-learning','langues'],4.5,'https://murf.ai','🎤','#845ef7',4700,'300K+'),
  t('podcastle','Podcastle','Enregistrement et édition podcast assisté par IA','audio','',
    'freemium','Gratuit · Storyteller à 23,99 $/mois',
    ['podcast','enregistrement','transcription','remote','collaboratif'],4.4,'https://podcastle.ai','🎙','#ff6b35',3500,'100K+'),
  t('auphonic','Auphonic','Post-production audio automatique par IA','audio','',
    'freemium','Gratuit 2h/mois · Credits à partir de 9 $/mois',
    ['post-production','normalisation','podcast','automatique','qualité'],4.5,'https://auphonic.com','🎚','#4caf50',3800,'100K+'),
  t('soundraw','Soundraw','Génération de musique libre de droits par IA','audio','',
    'freemium','Gratuit limité · Creator à 16,99 $/mois',
    ['musique','libre droits','génération','personnalisation','créateur'],4.4,'https://soundraw.io','🎼','#00bcd4',4100,'500K+'),
  t('boomy','Boomy','Créez et monetisez de la musique IA instantanément','audio','',
    'freemium','Gratuit · Personal à 2,99 $/mois',
    ['musique','génération','monetisation','streaming','facile'],4.2,'https://boomy.com','🎸','#9c27b0',3300,'2M+'),
  t('lalal-ai','Lalal.ai','Séparation de stems audio par IA','audio','',
    'freemium','Gratuit limité · Light à 15 $/mois',
    ['stems','séparation','voix','instruments','remix'],4.6,'https://lalal.ai','🔀','#ff5722',5100,'2M+'),
  t('krisp','Krisp','Suppression du bruit de fond par IA en temps réel','audio','',
    'freemium','Gratuit · Pro à 16 $/mois',
    ['bruit','suppression','meeting','temps réel','voix'],4.6,'https://krisp.ai','🔇','#1da462',5800,'5M+'),
  t('cleanvoice-ai','Cleanvoice','Suppression automatique des tics verbaux et silences','audio','',
    'freemium','Gratuit · Pay-as-you-go',
    ['podcast','tics','silence','montage','automatique'],4.3,'https://cleanvoice.ai','🧹','#3b82f6',2600,'50K+'),
  t('speechify','Speechify','Transformez n\'importe quel texte en audio par IA','audio','',
    'freemium','Gratuit · Premium à 139 $/an',
    ['tts','lecture','accessibilité','pdf','mobile'],4.5,'https://speechify.com','📖','#ff6b35',6200,'20M+'),
  t('play-ht','Play.ht','Voix IA réalistes pour podcasts et applications','audio','',
    'freemium','Gratuit · Starter à 31,2 $/mois',
    ['voix','tts','api','ultra-réaliste','multilingue'],4.4,'https://play.ht','▶','#9b59b6',4300,'300K+'),
  t('resemble-ai','Resemble AI','Clonage et synthèse de voix IA pour entreprises','audio','',
    'freemium','Gratuit · Pro à 30 $/mois',
    ['clonage','voix','entreprise','api','temps réel'],4.4,'https://resemble.ai','🔊','#6c63ff',2800,'100K+'),

  // ── Rédaction (20) ──────────────────────────────────────────────────────────
  t('jasper-ai','Jasper','Plateforme d\'IA pour la création de contenu marketing','redaction','',
    'paid','Creator à 49 $/mois',
    ['marketing','contenu','blog','emails','entreprise'],4.6,'https://jasper.ai','🖊','#ff5c28',8400,'100K+',true),
  t('copy-ai','Copy.ai','Générateur de textes marketing en quelques secondes','redaction','',
    'freemium','Gratuit · Pro à 36 $/mois',
    ['copywriting','marketing','emails','pub','automatisation'],4.5,'https://copy.ai','📝','#6c63ff',7200,'10M+'),
  t('writesonic','Writesonic','IA de rédaction SEO et génération de contenu','redaction','',
    'freemium','Gratuit · Individual à 16 $/mois',
    ['seo','blog','contenu','landing page','chatbot'],4.5,'https://writesonic.com','✍','#845ef7',6800,'3M+'),
  t('notion-ai','Notion AI','IA intégrée dans l\'espace de travail Notion','redaction','',
    'freemium','Add-on à 10 $/mois',
    ['notion','notes','résumé','rédaction','productivité'],4.6,'https://notion.so/product/ai','📓','#000000',9100,'30M+'),
  t('grammarly-ai','Grammarly','Assistant d\'écriture IA pour corriger et améliorer vos textes','redaction','',
    'freemium','Gratuit · Pro à 30 $/mois',
    ['grammaire','correction','style','anglais','extension'],4.7,'https://grammarly.com','✅','#15c39a',11600,'30M+',true),
  t('deepl','DeepL','Traducteur IA de référence, précis et naturel','redaction','',
    'freemium','Gratuit · Pro à 8,74 €/mois',
    ['traduction','langue','précision','professionnel','api'],4.8,'https://deepl.com','🌐','#0f2b46',12100,'100M+',true),
  t('quillbot','QuillBot','Paraphrase et amélioration de textes par IA','redaction','',
    'freemium','Gratuit · Premium à 19,95 $/mois',
    ['paraphrase','résumé','grammaire','traduction','citation'],4.5,'https://quillbot.com','🔄','#35b14e',9300,'35M+'),
  t('rytr','Rytr','Assistant de rédaction IA abordable et polyvalent','redaction','',
    'freemium','Gratuit · Saver à 9 $/mois',
    ['rédaction','contenu','templates','abordable','multilingue'],4.3,'https://rytr.me','✍','#8b5cf6',5100,'5M+'),
  t('anyword','Anyword','IA de copywriting orientée performance et conversion','redaction','',
    'paid','Starter à 49 $/mois',
    ['copywriting','conversion','score','ab test','marketing'],4.4,'https://anyword.com','🎯','#ff6b35',3800,'1M+'),
  t('wordtune','Wordtune','Reformulation et amélioration de phrases par IA','redaction','',
    'freemium','Gratuit · Plus à 13,99 $/mois',
    ['reformulation','style','anglais','extension','chrome'],4.4,'https://wordtune.com','🔤','#7c3aed',4900,'1M+'),
  t('hypotenuse-ai','Hypotenuse AI','Génération de contenu e-commerce et SEO à grande échelle','redaction','',
    'paid','Starter à 29 $/mois',
    ['e-commerce','produit','seo','bulk','contenu'],4.3,'https://hypotenuse.ai','📦','#ff6b35',2700,'50K+'),
  t('frase-io','Frase','Optimisation SEO et rédaction de contenu IA','redaction','',
    'paid','Basic à 45 $/mois',
    ['seo','brief','optimisation','recherche','contenu'],4.4,'https://frase.io','🔍','#8b5cf6',3400,'30K+'),
  t('surfer-seo','Surfer SEO','Optimisation on-page et rédaction SEO assistée par IA','redaction','',
    'paid','Essential à 99 $/mois',
    ['seo','on-page','audit','nlp','classement'],4.6,'https://surferseo.com','🏄','#ff6b35',5600,'150K+'),
  t('marketmuse','MarketMuse','Stratégie de contenu IA pour améliorer votre autorité SEO','redaction','',
    'freemium','Gratuit · Standard à 149 $/mois',
    ['seo','stratégie','autorité','brief','audit'],4.3,'https://marketmuse.com','📊','#6366f1',2300,'20K+'),
  t('clearscope','Clearscope','Optimisation de contenu IA pour mieux ranker sur Google','redaction','',
    'paid','Essentials à 189 $/mois',
    ['seo','optimisation','nlp','google','rank'],4.5,'https://clearscope.io','🔬','#4285f4',2100,'10K+'),
  t('textcortex','TextCortex','Assistant d\'écriture IA polyvalent et personnalisable','redaction','',
    'freemium','Gratuit · Unlimited à 23,99 $/mois',
    ['rédaction','personnalisation','templates','multilingue','browser'],4.3,'https://textcortex.com','🧠','#7c3aed',3100,'1M+'),
  t('longshot-ai','Longshot AI','Génération de contenu long-form IA optimisé SEO','redaction','',
    'paid','Basic à 29 $/mois',
    ['long-form','seo','blog','factuellement exact','recherche'],4.2,'https://longshot.ai','🏹','#ff5722',2400,'50K+'),
  t('simplified','Simplified','Suite créative IA tout-en-un pour équipes marketing','redaction','',
    'freemium','Gratuit · Pro à 12 $/mois',
    ['contenu','design','vidéo','réseaux sociaux','équipe'],4.4,'https://simplified.com','✨','#6c63ff',4600,'1M+'),
  t('scalenut','Scalenut','Plateforme IA SEO et contenu de bout en bout','redaction','',
    'paid','Essential à 39 $/mois',
    ['seo','contenu','brief','cluster','analyse'],4.3,'https://scalenut.com','📈','#845ef7',2800,'30K+'),
  t('narrato-io','Narrato','Espace de travail IA pour équipes de contenu','redaction','',
    'paid','Pro à 48 $/mois',
    ['équipe','workflow','contenu','seo','collaboration'],4.2,'https://narrato.io','📝','#ff6b35',1800,'10K+'),

  // ── Marketing (15) ──────────────────────────────────────────────────────────
  t('hubspot-ai','HubSpot AI','CRM et marketing automation propulsés par l\'IA','marketing','',
    'freemium','Gratuit · Starter à 20 $/mois',
    ['crm','marketing','emails','automation','inbound'],4.6,'https://hubspot.com','🟠','#ff7a59',9800,'200K+',true),
  t('mailchimp-ai','Mailchimp AI','Email marketing et automatisation avec IA prédictive','marketing','',
    'freemium','Gratuit · Essentials à 13 $/mois',
    ['email','newsletter','automation','segmentation','prédictif'],4.5,'https://mailchimp.com','🐒','#ffe01b',8200,'13M+'),
  t('semrush-ai','Semrush AI','Suite SEO et marketing digital avec IA intégrée','marketing','',
    'freemium','Gratuit · Pro à 139,95 $/mois',
    ['seo','concurrents','mots-clés','publicité','analyse'],4.7,'https://semrush.com','🔍','#ff642d',9400,'10M+'),
  t('predis-ai','Predis.ai','Génération de posts réseaux sociaux par IA','marketing','',
    'freemium','Gratuit · Starter à 32 $/mois',
    ['réseaux sociaux','posts','visuels','calendrier','ia'],4.4,'https://predis.ai','📱','#7c3aed',3600,'200K+'),
  t('ocoya','Ocoya','Automatisation des réseaux sociaux avec IA','marketing','',
    'paid','Starter à 19 $/mois',
    ['réseaux sociaux','programmation','contenu','ia','automatisation'],4.3,'https://ocoya.com','🦋','#5e35b1',2900,'50K+'),
  t('adcreative-ai','AdCreative.ai','Génération automatique de visuels publicitaires','marketing','',
    'paid','Starter à 21 $/mois',
    ['pub','créatifs','conversion','facebook','google ads'],4.4,'https://adcreative.ai','📣','#6c63ff',4200,'100K+'),
  t('persado','Persado','IA de persuasion pour optimiser les messages marketing','marketing','',
    'paid','Entreprise uniquement',
    ['nlp','persuasion','email','push','conversion'],4.3,'https://persado.com','💬','#ff5722',1800,'500+'),
  t('pencil-ai','Pencil','Génération et test de publicités IA à grande échelle','marketing','',
    'paid','Starter à 119 $/mois',
    ['pub','génération','test','performance','facebook'],4.2,'https://trypencil.com','✏️','#ffd700',2100,'5K+'),
  t('lately-ai','Lately','Transformez vos contenus longs en posts réseaux sociaux','marketing','',
    'paid','Starter à 49 $/mois',
    ['réseaux sociaux','repurposing','planification','contenu','ia'],4.2,'https://lately.ai','📅','#ff6b35',1900,'5K+'),
  t('phrasee','Phrasee','Optimisation IA du langage marketing pour l\'email et push','marketing','',
    'paid','Entreprise uniquement',
    ['email','push','langue','optimisation','ab test'],4.3,'https://phrasee.co','💬','#845ef7',1600,'1K+'),
  t('pattern89','Pattern89','IA prédictive pour la performance créative des pubs','marketing','',
    'paid','Entreprise uniquement',
    ['publicité','prédictif','créatifs','facebook','analyse'],4.1,'https://pattern89.com','📊','#6366f1',1400,'1K+'),
  t('seventh-sense','Seventh Sense','Optimisation de l\'heure d\'envoi email par IA','marketing','',
    'paid','HubSpot à 80 $/mois',
    ['email','timing','hubspot','marketo','délivrabilité'],4.3,'https://theseventhsense.com','⏰','#ff7043',1700,'5K+'),
  t('smartly-io','Smartly.io','Automatisation et optimisation des campagnes sociales','marketing','',
    'paid','Entreprise uniquement',
    ['pub','automation','facebook','instagram','performance'],4.4,'https://smartly.io','⚡','#1da1f2',2400,'700+'),
  t('trapica','Trapica','Ciblage publicitaire intelligent par apprentissage automatique','marketing','',
    'paid','Starter à 99 $/mois',
    ['ciblage','pub','facebook','optimisation','ml'],4.1,'https://trapica.com','🎯','#ff5722',1300,'2K+'),
  t('albert-ai','Albert.ai','IA autonome pour la gestion des campagnes publicitaires','marketing','',
    'paid','Entreprise uniquement',
    ['pub','autonome','search','social','optimisation'],4.2,'https://albert.ai','🤖','#3b82f6',1500,'200+'),

  // ── Business & Productivité (20) ─────────────────────────────────────────────
  t('tome-app','Tome','Créez des présentations narratives avec l\'IA','business','',
    'freemium','Gratuit · Pro à 20 $/mois',
    ['présentation','narrative','slides','génération','storytelling'],4.5,'https://tome.app','📖','#6366f1',5400,'500K+'),
  t('gamma-app','Gamma','Présentations, docs et sites web générés par IA','business','',
    'freemium','Gratuit · Pro à 15 $/mois',
    ['présentation','doc','site','génération','templates'],4.7,'https://gamma.app','⚡','#8b5cf6',7200,'2M+',true),
  t('otter-ai','Otter.ai','Transcription et résumé de réunions en temps réel','business','',
    'freemium','Gratuit · Pro à 16,99 $/mois',
    ['transcription','réunion','résumé','zoom','teams'],4.5,'https://otter.ai','🦦','#3b82f6',6800,'1M+'),
  t('fireflies-ai','Fireflies.ai','Prise de notes et analyse de réunions par IA','business','',
    'freemium','Gratuit · Pro à 18 $/mois',
    ['réunion','notes','transcription','crm','analyse'],4.6,'https://fireflies.ai','🔥','#7c3aed',7100,'300K+'),
  t('zapier-ai','Zapier AI','Automatisation de workflows avec IA intégrée','business','',
    'freemium','Gratuit · Starter à 29,99 $/mois',
    ['automatisation','workflow','intégrations','no-code','ia'],4.6,'https://zapier.com','⚡','#ff4a00',9300,'2M+',true),
  t('make-com','Make','Automatisation visuelle de workflows complexes','business','',
    'freemium','Gratuit · Core à 10,59 $/mois',
    ['automatisation','workflow','visuel','intégrations','no-code'],4.6,'https://make.com','🔧','#6d00cc',6700,'500K+'),
  t('monday-ai','Monday AI','Gestion de projet et équipes avec IA intégrée','business','',
    'freemium','Gratuit · Basic à 12 $/mois',
    ['gestion projet','équipe','automatisation','tableau','crm'],4.5,'https://monday.com','📊','#ff3d57',8100,'225K+'),
  t('mem-ai','Mem','Notes et base de connaissances auto-organisées par IA','business','',
    'freemium','Gratuit · Pro à 14,99 $/mois',
    ['notes','mémoire','organisation','connexions','recherche'],4.3,'https://mem.ai','🧠','#6366f1',3800,'200K+'),
  t('reclaim-ai','Reclaim.ai','Planification intelligente de réunions et tâches par IA','business','',
    'freemium','Gratuit · Starter à 8 $/mois',
    ['calendrier','planification','focus','réunion','productivité'],4.5,'https://reclaim.ai','📅','#6c63ff',4700,'500K+'),
  t('motion-ai','Motion','Planification automatique et gestion des tâches par IA','business','',
    'paid','Individual à 34 $/mois',
    ['productivité','tâches','calendrier','priorité','auto'],4.4,'https://usemotion.com','🏃','#845ef7',5200,'100K+'),
  t('clockwise','Clockwise','Optimisation de calendrier par IA pour équipes','business','',
    'freemium','Gratuit · Teams à 6,75 $/mois',
    ['calendrier','focus','réunion','optimisation','équipe'],4.4,'https://getclockwise.com','⏰','#00bcd4',3900,'100K+'),
  t('taskade','Taskade','Workspace IA pour gestion de projets et équipes','business','',
    'freemium','Gratuit · Pro à 19 $/mois',
    ['tâches','projets','agents','ia','collaboration'],4.4,'https://taskade.com','✅','#7c3aed',4300,'500K+'),
  t('coda-ai','Coda AI','Documents intelligents avec IA et automatisation','business','',
    'freemium','Gratuit · Pro à 12 $/mois',
    ['doc','automatisation','ia','table','workflow'],4.5,'https://coda.io','📄','#ef5350',5600,'50K+'),
  t('craft-do','Craft','Éditeur de documents élégant avec IA intégrée','business','',
    'freemium','Gratuit · Pro à 5 $/mois',
    ['documents','notes','ia','apple','design'],4.6,'https://craft.do','📝','#3b82f6',4100,'2M+'),
  t('tana-inc','Tana','Super workspace IA avec graphes et supertags','business','',
    'freemium','Gratuit · Plus disponible',
    ['notes','graphe','supertag','ia','productivité'],4.3,'https://tana.inc','🌿','#4ade80',2700,'100K+'),
  t('reflect-app','Reflect','Application de notes avec IA et pensée en réseau','business','',
    'paid','5 $/mois',
    ['notes','réseau','ia','pensée','simple'],4.4,'https://reflect.app','💡','#6366f1',3200,'50K+'),
  t('obsidian-md','Obsidian','Base de connaissances personnelle avec plugins IA','business','',
    'free','Gratuit (sync à 10 $/mois)',
    ['notes','graphe','markdown','local','plugins'],4.7,'https://obsidian.md','💎','#7c3aed',8400,'1M+'),
  t('lindy-ai','Lindy','Agents IA pour automatiser les tâches répétitives','business','',
    'freemium','Gratuit · Pro à 49,99 $/mois',
    ['agents','automatisation','email','crm','tâches'],4.4,'https://lindy.ai','🤖','#845ef7',3600,'50K+'),
  t('bardeen-io','Bardeen','Automatisation browser IA sans code','business','',
    'freemium','Gratuit · Pro à 10 $/mois',
    ['automatisation','browser','scraping','no-code','workflow'],4.3,'https://bardeen.ai','⚡','#3b82f6',4100,'200K+'),
  t('fellow-app','Fellow','Gestion de réunions et feedback d\'équipe par IA','business','',
    'freemium','Gratuit · Pro à 7 $/mois',
    ['réunion','agenda','feedback','équipe','manager'],4.5,'https://fellow.app','👥','#6c63ff',3500,'100K+'),

  // ── Design (10) ─────────────────────────────────────────────────────────────
  t('figma-ai','Figma AI','Design collaboratif avec IA générative intégrée','design','',
    'freemium','Gratuit · Pro à 15 $/mois',
    ['design','ui','ux','prototype','collaboratif'],4.8,'https://figma.com','🖌','#f24e1e',11200,'4M+',true),
  t('framer-ai','Framer AI','Créez des sites web avec l\'IA en quelques minutes','design','',
    'freemium','Gratuit · Mini à 5 $/mois',
    ['site web','génération','animations','no-code','design'],4.7,'https://framer.com','🎨','#0099ff',6800,'500K+'),
  t('looka','Looka','Création de logo et identité visuelle par IA','design','',
    'paid','Logo à partir de 20 $',
    ['logo','identité','marque','couleurs','typographie'],4.5,'https://looka.com','🏷','#6366f1',5200,'2M+'),
  t('brandmark-io','Brandmark','Générateur de logo IA minimaliste et professionnel','design','',
    'paid','Basic à 25 $',
    ['logo','marque','minimal','ia','svg'],4.3,'https://brandmark.io','✒️','#1a1a2e',3100,'500K+'),
  t('uizard','Uizard','Transformez des croquis en prototypes UI avec l\'IA','design','',
    'freemium','Gratuit · Pro à 19 $/mois',
    ['prototype','ui','croquis','wireframe','no-code'],4.4,'https://uizard.io','📱','#ff6b35',3700,'200K+'),
  t('penpot-ai','Penpot','Design open source avec fonctionnalités IA','design','',
    'free','Gratuit et open source',
    ['design','open source','ui','prototype','cloud'],4.4,'https://penpot.app','🐧','#7c3aed',3400,'300K+'),
  t('khroma','Khroma','Générateur de palettes de couleurs personnalisées par IA','design','',
    'free','Gratuit',
    ['couleurs','palette','ia','design','personnalisé'],4.4,'https://khroma.co','🎨','#ff6b6b',4600,'100K+'),
  t('colormind-io','Colormind','Palettes de couleurs harmonieuses générées par IA','design','',
    'free','Gratuit',
    ['couleurs','palette','harmonie','ia','design'],4.2,'https://colormind.io','🌈','#9c27b0',2800,'50K+'),
  t('visily-ai','Visily','Conversion de screenshots en wireframes par IA','design','',
    'freemium','Gratuit · Starter à 20 $/mois',
    ['wireframe','screenshot','ui','prototype','équipe'],4.4,'https://visily.ai','👁','#3b82f6',2600,'50K+'),
  t('galileo-ai','Galileo AI','Génération de maquettes UI complexes par IA','design','',
    'freemium','Liste d\'attente · Pro disponible',
    ['ui','génération','composants','figma','design'],4.2,'https://usegalileo.ai','🔭','#6366f1',2100,'50K+'),

  // ── Finance (10) ────────────────────────────────────────────────────────────
  t('kensho','Kensho','IA d\'analyse financière et de données pour S&P Global','finance','',
    'paid','Entreprise uniquement',
    ['analyse','marchés','nlp','données','s&p'],4.4,'https://kensho.com','📈','#1565c0',2200,'1K+'),
  t('alphasense','AlphaSense','Recherche d\'investissement augmentée par IA','finance','',
    'paid','Entreprise uniquement',
    ['investissement','recherche','documents','nlp','finance'],4.6,'https://alpha-sense.com','🔍','#003087',3800,'4K+'),
  t('trullion','Trullion','Automatisation de la comptabilité et des audits par IA','finance','',
    'paid','Entreprise uniquement',
    ['comptabilité','audit','conformité','ifrs','automatisation'],4.3,'https://trullion.com','📋','#6366f1',1600,'500+'),
  t('vic-ai','Vic.ai','Automatisation de la comptabilité fournisseurs par IA','finance','',
    'paid','Entreprise uniquement',
    ['factures','ap','comptabilité','automatisation','erp'],4.4,'https://vic.ai','🤖','#ff5722',1900,'1K+'),
  t('docyt','Docyt','Automatisation comptable et rapports financiers par IA','finance','',
    'paid','Scale à 299 $/mois',
    ['comptabilité','rapports','automatisation','pme','quickbooks'],4.3,'https://docyt.com','📊','#3b82f6',1500,'500+'),
  t('zeni-ai','Zeni','Tenue de livres et finances automatisées par IA','finance','',
    'paid','Starter à 149 $/mois',
    ['comptabilité','startups','trésorerie','automatisation','cfo'],4.4,'https://zeni.ai','💚','#4caf50',1800,'500+'),
  t('brex-ai','Brex AI','IA financière intégrée à la carte et gestion des dépenses','finance','',
    'freemium','Gratuit · Premium disponible',
    ['dépenses','carte','ia','startups','analyse'],4.5,'https://brex.com','💳','#6366f1',3200,'5K+'),
  t('ramp-ai','Ramp AI','Gestion des dépenses d\'entreprise optimisée par IA','finance','',
    'freemium','Gratuit · Plus disponible',
    ['dépenses','économies','ia','analyse','entreprise'],4.6,'https://ramp.com','💰','#00d563',4100,'20K+'),
  t('puzzle-io','Puzzle','Comptabilité en temps réel pour startups','finance','',
    'paid','Starter à 49 $/mois',
    ['comptabilité','startup','temps réel','rapports','gaap'],4.2,'https://puzzle.io','🧩','#7c3aed',1400,'1K+'),
  t('finmark-io','Finmark','Modélisation financière et planification IA pour startups','finance','',
    'paid','Starter à 50 $/mois',
    ['modélisation','planification','projection','startups','kpi'],4.3,'https://finmark.com','📈','#845ef7',1700,'2K+'),

  // ── RH & Formation (15) ─────────────────────────────────────────────────────
  t('eightfold-ai','Eightfold.ai','Plateforme de talent IA pour recrutement et rétention','rh','',
    'paid','Entreprise uniquement',
    ['recrutement','talent','ia','rétention','diversité'],4.5,'https://eightfold.ai','🎯','#6366f1',2800,'500+'),
  t('hirevue','HireVue','Entretiens vidéo et évaluation des candidats par IA','rh','',
    'paid','Entreprise uniquement',
    ['entretien','vidéo','évaluation','compétences','recrutement'],4.3,'https://hirevue.com','🎥','#00bcd4',2600,'700+'),
  t('paradox-ai','Paradox','Chatbot RH Olivia pour automatiser le recrutement','rh','',
    'paid','Entreprise uniquement',
    ['chatbot','recrutement','planning','candidats','automatisation'],4.5,'https://paradox.ai','🤖','#845ef7',2400,'1K+'),
  t('leena-ai','Leena AI','Agent IA RH pour automatiser les requêtes employés','rh','',
    'paid','Entreprise uniquement',
    ['rh','employés','requêtes','agent','automatisation'],4.3,'https://leena.ai','💬','#6366f1',1700,'500+'),
  t('duolingo-ai','Duolingo Max','Apprentissage des langues avec IA générative','rh','',
    'freemium','Gratuit · Super à 7,99 $/mois',
    ['langues','apprentissage','ia','gamification','mobile'],4.7,'https://duolingo.com','🦜','#58cc02',11400,'100M+',true),
  t('coursera-ai','Coursera AI','Cours et certifications en ligne avec tuteur IA','rh','',
    'freemium','Gratuit · Plus à 59 $/mois',
    ['formation','certificats','universities','ia','en ligne'],4.6,'https://coursera.org','📚','#0056d2',8700,'100M+'),
  t('edapp','EdApp','LMS mobile avec IA pour la microformation','rh','',
    'freemium','Gratuit · Pro à 2,95 $/mois',
    ['microlearning','mobile','lms','gamification','formation'],4.4,'https://edapp.com','📱','#ff6b35',3200,'5M+'),
  t('deel-ai','Deel AI','RH globales avec IA pour conformité et paie internationale','rh','',
    'paid','Contractors à partir de 49 $/mois',
    ['paie','international','conformité','rh','global'],4.5,'https://deel.com','🌍','#845ef7',5100,'20K+'),
  t('lattice-ai','Lattice AI','Performance et engagement employés optimisés par IA','rh','',
    'paid','Performance à 11 $/mois/personne',
    ['performance','engagement','feedback','objectifs','rh'],4.4,'https://lattice.com','📊','#4f46e5',3600,'5K+'),
  t('leapsome','Leapsome','Plateforme RH IA pour performance et apprentissage continu','rh','',
    'paid','Entreprise uniquement',
    ['performance','oкр','feedback','learning','rh'],4.5,'https://leapsome.com','🚀','#6366f1',2100,'2K+'),
  t('15five','15Five','Gestion de la performance et bien-être par IA','rh','',
    'paid','Engage à 4 $/mois/personne',
    ['performance','engagement','feedback','manager','bien-être'],4.4,'https://15five.com','5️⃣','#00bfa5',2800,'3K+'),
  t('betterworks','Betterworks','Gestion des objectifs OKR et performance par IA','rh','',
    'paid','Entreprise uniquement',
    ['okr','performance','objectifs','ia','alignement'],4.3,'https://betterworks.com','🎯','#3b82f6',1900,'500+'),
  t('zavvy','Zavvy','Onboarding et développement employés par IA','rh','',
    'paid','Starter à 4 $/mois/personne',
    ['onboarding','développement','formation','automatisation','rh'],4.4,'https://zavvy.io','🌱','#6c63ff',2100,'1K+'),
  t('speeko-app','Speeko','Coach IA pour améliorer la prise de parole en public','rh','',
    'freemium','Gratuit · Premium à 9,99 $/mois',
    ['communication','prise de parole','coach','mobile','pratique'],4.4,'https://speeko.co','🎤','#ff6b35',2600,'500K+'),
  t('degreed','Degreed','Plateforme d\'upskilling et de learning continu','rh','',
    'paid','Entreprise uniquement',
    ['formation','compétences','upskilling','parcours','entreprise'],4.3,'https://degreed.com','📈','#4285f4',2300,'5M+'),

  // ── Santé (10) ──────────────────────────────────────────────────────────────
  t('ada-health','Ada Health','Application de diagnostic santé par IA','sante','',
    'freemium','Gratuit · Entreprise disponible',
    ['diagnostic','symptômes','triage','santé','mobile'],4.6,'https://ada.com','🏥','#00bcd4',6200,'12M+'),
  t('babylon-health','Babylon Health','Consultation médicale et IA de diagnostic','sante','',
    'freemium','Gratuit · Subscription disponible',
    ['médecin','diagnostic','télémédecine','ia','symptômes'],4.3,'https://babylonhealth.com','💊','#00a86b',3800,'1M+'),
  t('glass-health','Glass Health','Assistant IA clinique pour médecins et praticiens','sante','',
    'freemium','Gratuit · Pro disponible',
    ['clinique','médecin','diagnostic','ddx','notes'],4.5,'https://glass.health','🔬','#3b82f6',2900,'100K+'),
  t('nabla-ai','Nabla','Assistant IA pour les soignants, génération de notes cliniques','sante','',
    'paid','Pro à 119 $/mois',
    ['notes','médecin','transcription','clinique','ambiance'],4.6,'https://nabla.com','🩺','#845ef7',3400,'30K+'),
  t('suki-ai','Suki AI','Assistant vocal IA pour documentation clinique','sante','',
    'paid','Entreprise uniquement',
    ['documentation','vocal','ehr','médecin','notes'],4.5,'https://suki.ai','🎙','#3b82f6',2600,'10K+'),
  t('nuance-dax','Nuance DAX','Documentation clinique ambiante et automatique','sante','',
    'paid','Entreprise uniquement',
    ['dax','dragon','clinique','notes','microsoft'],4.6,'https://nuance.com/healthcare','🎤','#0078d4',2200,'500+'),
  t('infermedica','Infermedica','API de triage et d\'évaluation des symptômes par IA','sante','',
    'freemium','Gratuit · Enterprise disponible',
    ['triage','symptômes','api','diagnostic','santé'],4.4,'https://infermedica.com','⚕️','#00bcd4',1800,'200+'),
  t('regard-health','Regard','Détection automatique des comorbidités dans les dossiers','sante','',
    'paid','Entreprise uniquement',
    ['ehr','comorbidités','hôpital','ia','détection'],4.3,'https://regard.com','📋','#6366f1',1400,'200+'),
  t('corti-ai','Corti','IA d\'aide à la décision en temps réel pour urgences','sante','',
    'paid','Entreprise uniquement',
    ['urgences','temps réel','décision','ems','appels'],4.4,'https://corti.ai','🚑','#ef5350',1600,'200+'),
  t('kry-health','Kry','Téléconsultation médicale avec triage IA intégré','sante','',
    'freemium','Consultation selon assurance',
    ['télémédecine','médecin','consultation','triage','europe'],4.4,'https://kry.se','💙','#00bfa5',2800,'2M+'),

  // ── Recherche & Data (15) ───────────────────────────────────────────────────
  t('consensus-app','Consensus','Moteur de recherche scientifique basé sur l\'IA','recherche','',
    'freemium','Gratuit · Premium à 9,99 $/mois',
    ['recherche','science','études','consensus','preuves'],4.6,'https://consensus.app','🔬','#3b82f6',5800,'500K+',true),
  t('elicit-org','Elicit','Assistant de recherche IA pour analyser des papiers scientifiques','recherche','',
    'freemium','Gratuit · Plus à 12 $/mois',
    ['recherche','papiers','résumé','analyse','science'],4.6,'https://elicit.com','📊','#845ef7',5200,'200K+'),
  t('semantic-scholar','Semantic Scholar','Moteur de recherche académique gratuit et puissant','recherche','',
    'free','Gratuit',
    ['académique','citations','graphe','science','gratuit'],4.5,'https://semanticscholar.org','📚','#2196f3',6400,'100M+'),
  t('scite-ai','Scite','Citations intelligentes et classification par IA','recherche','',
    'freemium','Gratuit · Premium à 20 $/mois',
    ['citations','smart citations','vérification','science','peer review'],4.5,'https://scite.ai','📑','#ff6b35',3700,'200K+'),
  t('researchrabbit','ResearchRabbit','Découverte de papiers scientifiques par graphe IA','recherche','',
    'free','Gratuit',
    ['papiers','graphe','découverte','zotero','visualisation'],4.6,'https://www.researchrabbit.ai','🐇','#845ef7',4300,'300K+'),
  t('connected-papers','Connected Papers','Visualisation des connexions entre papiers de recherche','recherche','',
    'freemium','Gratuit · Premium à 3 $/mois',
    ['graphe','connexions','visualisation','papers','académique'],4.5,'https://connectedpapers.com','🕸','#4285f4',4800,'500K+'),
  t('explainpaper','Explainpaper','Comprenez les papiers scientifiques complexes avec l\'IA','recherche','',
    'freemium','Gratuit · Plus disponible',
    ['explication','papiers','compréhension','termes','science'],4.4,'https://explainpaper.com','💡','#ff6b35',3100,'100K+'),
  t('scispace','SciSpace','Plateforme de lecture et de recherche scientifique IA','recherche','',
    'freemium','Gratuit · Premium à 12 $/mois',
    ['lecture','explication','papiers','analyse','science'],4.5,'https://typeset.io','🔭','#845ef7',4900,'5M+'),
  t('iris-ai','Iris.ai','IA pour analyser et synthétiser la littérature scientifique','recherche','',
    'paid','Team à 99 $/mois',
    ['littérature','synthèse','R&D','entreprise','brevets'],4.3,'https://iris.ai','👁','#6366f1',1900,'5K+'),
  t('humata-ai','Humata','Chat avec vos PDF et documents scientifiques','recherche','',
    'freemium','Gratuit · Pro à 14,99 $/mois',
    ['pdf','chat','résumé','questions','documents'],4.4,'https://humata.ai','📄','#7c3aed',4200,'500K+'),
  t('chatpdf','ChatPDF','Posez des questions à vos PDF en langage naturel','recherche','',
    'freemium','Gratuit · Plus à 8 $/mois',
    ['pdf','chat','résumé','questions','facile'],4.4,'https://chatpdf.com','💬','#ff6b35',5600,'5M+'),
  t('scholarcy','Scholarcy','Résumé automatique d\'articles académiques par IA','recherche','',
    'freemium','Gratuit · Personal à 9,99 $/mois',
    ['résumé','flashcard','académique','bibliographie','chrome'],4.3,'https://scholarcy.com','📖','#4285f4',2800,'100K+'),
  t('undermind-ai','Undermind','Agent de recherche IA pour la littérature scientifique','recherche','',
    'freemium','Gratuit · Pro à 19 $/mois',
    ['recherche','agent','littérature','scientifique','approfondi'],4.4,'https://undermind.ai','🔎','#845ef7',2200,'50K+'),
  t('dimensions-ai','Dimensions','Base de données de recherche et analytics scientifiques','recherche','',
    'freemium','Gratuit · API disponible',
    ['données','analytics','publications','brevets','science'],4.4,'https://dimensions.ai','📐','#1565c0',3100,'200K+'),
  t('litmaps','Litmaps','Cartographie de la littérature scientifique par IA','recherche','',
    'freemium','Gratuit · Pro à 10 $/mois',
    ['carte','littérature','visualisation','citations','découverte'],4.4,'https://litmaps.com','🗺','#26c6da',2500,'100K+'),

  // ── Droit & Juridique ────────────────────────────────────────────────────────
  t('harvey-ai','Harvey AI','IA juridique spécialisée pour cabinets d\'avocats','business','',
    'paid','Entreprise uniquement',
    ['juridique','contrats','recherche','avocats','analyse'],4.6,'https://harvey.ai','⚖️','#1a1a2e',3200,'1K+'),
  t('clio-ai','Clio','Gestion de cabinet juridique avec IA intégrée','business','',
    'paid','Starter à 49 $/mois',
    ['gestion','cabinet','facturation','dossiers','juridique'],4.4,'https://clio.com','📁','#3b82f6',4100,'150K+'),
  t('luminance','Luminance','Analyse et révision de contrats juridiques par IA','business','',
    'paid','Entreprise uniquement',
    ['contrats','analyse','due diligence','juridique','nlp'],4.5,'https://luminance.com','🔦','#6366f1',1800,'300+'),
  t('donotpay','DoNotPay','IA pour défendre vos droits et contester des décisions','business','',
    'paid','36 $/an',
    ['droits','contestation','consommateurs','juridique','automatisation'],4.2,'https://donotpay.com','🚫','#ef5350',3600,'1M+'),
  t('lexisnexis-ai','LexisNexis AI','Recherche juridique et analyse de jurisprudence par IA','business','',
    'paid','Entreprise uniquement',
    ['jurisprudence','recherche','juridique','législation','analyse'],4.6,'https://lexisnexis.com','📚','#e53935',2900,'500K+'),

  // ── Éducation ────────────────────────────────────────────────────────────────
  t('khanmigo','Khanmigo','Tuteur IA de Khan Academy pour élèves et enseignants','rh','',
    'freemium','Gratuit · Enseignants prioritaires',
    ['tuteur','élèves','enseignants','pédagogie','cours'],4.7,'https://khanmigo.ai','🎓','#1db954',5200,'500K+'),
  t('eduaide-ai','Eduaide.ai','Générateur de ressources pédagogiques par IA','rh','',
    'freemium','Gratuit · Pro à 8,99 $/mois',
    ['cours','fiches','exercices','enseignants','ressources'],4.6,'https://eduaide.ai','📝','#845ef7',3100,'200K+'),
  t('magicschool-ai','MagicSchool.ai','Suite IA complète pour les enseignants','rh','',
    'freemium','Gratuit · Pro à 9,99 $/mois',
    ['enseignants','cours','bulletins','différenciation','évaluation'],4.7,'https://magicschool.ai','🪄','#ff6b35',4800,'3M+'),
  t('diffit-ai','Diffit','Différenciation pédagogique IA pour adapter les textes','rh','',
    'freemium','Gratuit · Teacher à 12,99 $/mois',
    ['différenciation','lecture','niveau','textes','enseignants'],4.5,'https://diffit.me','🎯','#4285f4',2600,'500K+'),
  t('beamery','Beamery','Gestion des talents et recrutement proactif par IA','rh','',
    'paid','Entreprise uniquement',
    ['talent','recrutement','pipeline','diversité','ia'],4.4,'https://beamery.com','💡','#6366f1',1900,'500+'),

  // ── Design & Architecture ────────────────────────────────────────────────────
  t('arko-ai','Arko AI','Génération de concepts architecturaux par IA','design','',
    'freemium','Gratuit · Pro à 29 $/mois',
    ['architecture','concept','3d','rendu','design'],4.4,'https://arko.ai','🏛','#6366f1',1800,'10K+'),
  t('maket-ai','Maket','Génération de plans d\'étage et maquettes par IA','design','',
    'freemium','Gratuit · Starter à 15 $/mois',
    ['plans','étage','architecture','maquettes','génération'],4.3,'https://maket.ai','📐','#3b82f6',2100,'30K+'),
  t('testfit','TestFit','Optimisation foncière et faisabilité architecturale par IA','design','',
    'paid','Entreprise uniquement',
    ['faisabilité','foncier','promotion','architecture','optimisation'],4.5,'https://testfit.io','🏗','#10a37f',1400,'500+'),

  // ── Immobilier, Artisanat & Restauration ────────────────────────────────────
  t('likely-ai','Likely.AI','Prédiction de leads immobiliers et comportements vendeurs','business','',
    'paid','Starter à 99 $/mois',
    ['leads','immobilier','prédiction','vendeurs','ciblage'],4.4,'https://likely.ai','🏠','#4caf50',1600,'500+'),
  t('structurely','Structurely','Chatbot IA de qualification de leads immobiliers','business','',
    'paid','Starter à 99 $/mois',
    ['chatbot','leads','qualification','immobilier','suivi'],4.3,'https://structurely.com','🤖','#3b82f6',1400,'500+'),
  t('roof-ai','Roof AI','Conversion et engagement client pour agents immobiliers','business','',
    'paid','Entreprise uniquement',
    ['conversion','chat','immobilier','leads','engagement'],4.3,'https://roof.ai','🏡','#ff6b35',1100,'200+'),
  t('jobber-ai','Jobber AI','Gestion de chantiers et devis pour artisans par IA','business','',
    'freemium','Gratuit · Core à 19 $/mois',
    ['devis','chantier','artisan','planning','facturation'],4.6,'https://getjobber.com','🔨','#f59e0b',5800,'200K+'),
  t('servicetitan-ai','ServiceTitan AI','ERP pour artisans du bâtiment avec IA intégrée','business','',
    'paid','Entreprise uniquement',
    ['erp','artisan','plombier','électricien','gestion'],4.4,'https://servicetitan.com','🔧','#3b82f6',3200,'5K+'),
  t('plant-jammer','Plant Jammer','Génération de recettes IA personnalisées pour chefs','business','',
    'freemium','Gratuit · Pro disponible',
    ['recettes','cuisine','génération','ingrédients','chef'],4.3,'https://plantjammer.com','🍽','#4caf50',1900,'100K+'),
  t('winnow','Winnow','Réduction du gaspillage alimentaire en restauration par IA','business','',
    'paid','Entreprise uniquement',
    ['gaspillage','restauration','cuisine','analyse','durabilité'],4.4,'https://winnowsolutions.com','♻️','#00c853',1700,'500+'),
  t('marketman','MarketMan','Gestion des stocks et des fournisseurs pour restaurants','business','',
    'paid','Starter à 239 $/mois',
    ['stocks','fournisseurs','restaurant','coût','inventaire'],4.3,'https://marketman.com','📦','#ff6b35',1500,'500+'),
  t('feedly-ai','Feedly AI','Veille presse et curation de contenu IA pour journalistes','business','',
    'freemium','Gratuit · Pro à 8 $/mois',
    ['veille','presse','curation','actualités','journaliste'],4.5,'https://feedly.com','📰','#2bb24c',6200,'10M+'),
]

// ── Spécialisations par métier ───────────────────────────────────────────────
const SPECIALITES: Record<string, string[]> = {
  // Santé
  'nabla-ai':        ['medecin','infirmier','kinesitherapeute','dentiste'],
  'nuance-dax':      ['medecin','infirmier'],
  'suki-ai':         ['medecin','infirmier'],
  'glass-health':    ['medecin','infirmier'],
  'ada-health':      ['medecin','infirmier','pharmacien'],
  'infermedica':     ['medecin','infirmier','pharmacien'],
  'corti-ai':        ['medecin','infirmier'],
  'regard-health':   ['medecin','infirmier'],
  // Droit
  'harvey-ai':       ['avocat','juriste','notaire'],
  'clio-ai':         ['avocat'],
  'luminance':       ['avocat','juriste','notaire'],
  'donotpay':        ['avocat'],
  'lexisnexis-ai':   ['avocat','juriste','notaire','huissier'],
  // Finance
  'vic-ai':          ['comptable','expert-comptable'],
  'trullion':        ['comptable','expert-comptable'],
  'zeni-ai':         ['comptable','expert-comptable','auto-entrepreneur'],
  'docyt':           ['comptable','expert-comptable'],
  'kensho':          ['banquier','conseiller-financier'],
  'ramp-ai':         ['comptable','expert-comptable'],
  'brex-ai':         ['comptable','expert-comptable','auto-entrepreneur'],
  'puzzle-io':       ['comptable','expert-comptable','auto-entrepreneur'],
  // RH / Recrutement
  'eightfold-ai':    ['recruteur','drh','charge-de-formation'],
  'hirevue':         ['recruteur','drh'],
  'paradox-ai':      ['recruteur','drh'],
  'beamery':         ['recruteur','drh'],
  'leena-ai':        ['drh','gestionnaire-de-paie'],
  'deel-ai':         ['drh','gestionnaire-de-paie'],
  // Éducation
  'khanmigo':        ['professeur','formateur','tuteur'],
  'eduaide-ai':      ['professeur','formateur'],
  'magicschool-ai':  ['professeur','formateur','directeur-ecole'],
  'diffit-ai':       ['professeur','formateur'],
  // Code
  'github-copilot':  ['developpeur','devops','data-scientist'],
  'cursor':          ['developpeur'],
  'codeium':         ['developpeur'],
  'tabnine':         ['developpeur'],
  'replit-ai':       ['developpeur'],
  // Marketing / Rédaction
  'surfer-seo':      ['seo','redacteur-web'],
  'jasper-ai':       ['redacteur-web','community-manager','chef-de-pub'],
  'adcreative-ai':   ['chef-de-pub','community-manager','graphiste'],
  'predis-ai':       ['community-manager','chef-de-pub'],
  // Design / Architecture
  'midjourney':      ['graphiste','architecte','designer-ux'],
  'arko-ai':         ['architecte'],
  'maket-ai':        ['architecte','promoteur'],
  'testfit':         ['promoteur','architecte'],
  // Journaliste / Médias
  'otter-ai':        ['journaliste','podcaster'],
  'descript':        ['journaliste','videastes','podcaster'],
  'perplexity':      ['journaliste'],
  'feedly-ai':       ['journaliste'],
  // Restauration
  'plant-jammer':    ['chef-cuisinier','restaurateur','patissier'],
  'winnow':          ['restaurateur','chef-cuisinier'],
  'marketman':       ['restaurateur'],
  // Immobilier
  'likely-ai':       ['agent-immobilier'],
  'structurely':     ['agent-immobilier'],
  'roof-ai':         ['agent-immobilier'],
  // Artisanat
  'jobber-ai':       ['plombier','electricien','menuisier','macon','peintre'],
  'servicetitan-ai': ['plombier','electricien'],
}

tools.forEach((tool) => {
  if (SPECIALITES[tool.slug]) tool.specialites = SPECIALITES[tool.slug]
})

export default tools
