import { getCatalogToolBySlug } from './tools-index'
import type { CatalogTool } from './catalog-types'

export type MetierStep = { title: string; desc: string }

export type Metier = {
  slug: string
  name: string
  sector: string
  icon: string          // lucide-react icon name
  top5: string[]        // catalog-tools slugs
  useCases: string[]    // 4-5 cas d'usage spécifiques au métier
  tempsGagne: string    // ex : "3-5h / semaine"
  budget: string        // ex : "0-30 € / mois"
  steps: [MetierStep, MetierStep, MetierStep]
}

export const SECTORS = [
  { id: 'Santé',           icon: 'Stethoscope' },
  { id: 'Droit',           icon: 'Scale' },
  { id: 'Finance',         icon: 'TrendingUp' },
  { id: 'Éducation',       icon: 'GraduationCap' },
  { id: 'Tech',            icon: 'Code2' },
  { id: 'Marketing',       icon: 'Megaphone' },
  { id: 'Commerce',        icon: 'ShoppingBag' },
  { id: 'Santé mentale',   icon: 'Brain' },
  { id: 'Artisanat',       icon: 'Hammer' },
  { id: 'Restauration',    icon: 'ChefHat' },
  { id: 'Immobilier',      icon: 'Home' },
  { id: 'Médias',          icon: 'Camera' },
  { id: 'RH',              icon: 'Users' },
  { id: 'Entrepreneurs',   icon: 'Rocket' },
]

export const METIERS: Metier[] = [

  // ── Santé ──────────────────────────────────────────────────────────────────
  {
    slug: 'medecin',
    name: 'Médecin',
    sector: 'Santé',
    icon: 'Stethoscope',
    top5: ['chatgpt', 'glass-health', 'nabla-ai', 'nuance-dax', 'elicit-org'],
    useCases: [
      'Rédiger des comptes-rendus médicaux en quelques secondes',
      'Préparer des explications claires pour les patients',
      'Effectuer une veille médicale sur les dernières études',
      'Générer des lettres de correspondance entre confrères',
      'Aide au diagnostic différentiel et à la décision clinique',
    ],
    tempsGagne: '4-6h / semaine',
    budget: '20-50 € / mois',
    steps: [
      { title: 'Démarrez avec ChatGPT', desc: 'Utilisez ChatGPT pour rédiger vos premiers comptes-rendus en dictant simplement vos notes. Testez le prompt : "Transforme ces notes en compte-rendu médical structuré."' },
      { title: 'Adoptez Nabla pour la dictée clinique', desc: 'Nabla transcrit automatiquement vos consultations et génère le compte-rendu. Connectez-le à votre logiciel médical habituel.' },
      { title: 'Consultez Glass Health pour l\'aide à la décision', desc: 'Glass Health propose des diagnostics différentiels et des résumés de littérature médicale directement dans votre navigateur.' },
    ],
  },
  {
    slug: 'infirmier',
    name: 'Infirmier',
    sector: 'Santé',
    icon: 'Stethoscope',
    top5: ['chatgpt', 'ada-health', 'speechify', 'nuance-dax', 'deepl'],
    useCases: [
      'Rédiger les transmissions écrites rapidement',
      'Préparer des supports d\'éducation thérapeutique pour les patients',
      'Mémoriser les protocoles et procédures complexes',
      'Traduire des documents médicaux pour patients étrangers',
    ],
    tempsGagne: '2-4h / semaine',
    budget: '0-20 € / mois',
    steps: [
      { title: 'Utilisez ChatGPT pour les transmissions', desc: 'Dictez vos observations et demandez à ChatGPT de les structurer en transmissions SOAP ou en format SBAR.' },
      { title: 'Créez des fiches patients avec Speechify', desc: 'Speechify lit à voix haute vos protocoles et fiches pour vous permettre de les assimiler pendant vos déplacements.' },
      { title: 'Traduisez avec DeepL', desc: 'Pour les patients non francophones, DeepL traduit instantanément consentements, ordonnances et explications avec une précision médicale.' },
    ],
  },
  {
    slug: 'kinesitherapeute',
    name: 'Kinésithérapeute',
    sector: 'Santé',
    icon: 'Stethoscope',
    top5: ['chatgpt', 'claude-ai', 'notion-ai', 'canva-ai', 'grammarly-ai'],
    useCases: [
      'Créer des programmes d\'exercices personnalisés illustrés',
      'Rédiger les bilans de début et fin de rééducation',
      'Concevoir des fiches d\'exercices visuelles pour les patients',
      'Préparer les devis et courriers administratifs',
    ],
    tempsGagne: '2-3h / semaine',
    budget: '0-20 € / mois',
    steps: [
      { title: 'Rédigez vos bilans avec ChatGPT', desc: 'Décrivez l\'état du patient et demandez à ChatGPT de structurer un bilan kinésithérapeutique complet avec objectifs et plan de traitement.' },
      { title: 'Créez des fiches exercices avec Canva AI', desc: 'Canva AI génère des fiches illustrées professionnelles avec les exercices et consignes. Personnalisez les couleurs de votre cabinet.' },
      { title: 'Gérez vos notes avec Notion AI', desc: 'Centralisez le suivi de vos patients dans Notion et laissez l\'IA résumer les progrès et préparer vos comptes-rendus.' },
    ],
  },
  {
    slug: 'pharmacien',
    name: 'Pharmacien',
    sector: 'Santé',
    icon: 'Stethoscope',
    top5: ['chatgpt', 'glass-health', 'infermedica', 'deepl', 'perplexity'],
    useCases: [
      'Vérifier les interactions médicamenteuses complexes',
      'Rédiger des fiches conseil pour les patients',
      'Répondre aux questions des patients sur les traitements',
      'Traduire des notices et documents pharmaceutiques',
    ],
    tempsGagne: '2-4h / semaine',
    budget: '0-20 € / mois',
    steps: [
      { title: 'Vérifiez les interactions avec ChatGPT', desc: 'Posez directement vos questions d\'interactions médicamenteuses à ChatGPT. Croisez toujours avec Vidal, mais gagnez du temps sur la synthèse.' },
      { title: 'Créez des fiches conseil avec Canva AI', desc: 'Générez des affiches et fiches patients professionnelles sur les traitements courants (diabète, HTA, asthme...) en quelques minutes.' },
      { title: 'Faites votre veille avec Perplexity', desc: 'Perplexity vous donne des réponses sourcées sur les nouvelles molécules et les alertes de pharmacovigilance.' },
    ],
  },
  {
    slug: 'dentiste',
    name: 'Dentiste',
    sector: 'Santé',
    icon: 'Stethoscope',
    top5: ['chatgpt', 'canva-ai', 'notion-ai', 'grammarly-ai', 'gamma-app'],
    useCases: [
      'Rédiger les plans de traitement pour les patients',
      'Créer des supports de communication pour le cabinet',
      'Automatiser les emails de rappel de rendez-vous',
      'Concevoir des devis clairs et visuellement attractifs',
    ],
    tempsGagne: '2-3h / semaine',
    budget: '15-30 € / mois',
    steps: [
      { title: 'Rédigez vos plans de traitement', desc: 'Décrivez le cas clinique à ChatGPT et obtenez un plan de traitement clair et pédagogique à présenter au patient.' },
      { title: 'Créez votre communication avec Canva AI', desc: 'Créez brochures, posts Instagram et affiches cabinet en quelques clics avec les templates IA de Canva.' },
      { title: 'Présentez avec Gamma', desc: 'Gamma génère des présentations élégantes pour expliquer les soins à vos patients ou former votre équipe.' },
    ],
  },

  // ── Droit ───────────────────────────────────────────────────────────────────
  {
    slug: 'avocat',
    name: 'Avocat',
    sector: 'Droit',
    icon: 'Scale',
    top5: ['chatgpt', 'claude-ai', 'perplexity', 'deepl', 'grammarly-ai'],
    useCases: [
      'Rédiger des conclusions et actes juridiques plus rapidement',
      'Résumer et analyser des jurisprudences volumineuses',
      'Préparer les arguments et contre-arguments d\'un dossier',
      'Traduire des documents juridiques étrangers',
      'Générer des modèles de courriers et mises en demeure',
    ],
    tempsGagne: '5-8h / semaine',
    budget: '20-50 € / mois',
    steps: [
      { title: 'Résumez la jurisprudence avec Claude', desc: 'Claude excelle pour analyser de longs documents juridiques. Uploadez une décision et demandez-lui les points clés, les arguments et les implications.' },
      { title: 'Rédigez avec ChatGPT', desc: 'Utilisez ChatGPT pour générer des premiers jets de conclusions, requêtes et courriers. Relisez et adaptez — vous gagnez 60% du temps de rédaction.' },
      { title: 'Traduction juridique avec DeepL', desc: 'DeepL propose la meilleure qualité pour les documents juridiques étrangers. Abonnez-vous à DeepL Pro pour les documents confidentiels.' },
    ],
  },
  {
    slug: 'notaire',
    name: 'Notaire',
    sector: 'Droit',
    icon: 'Scale',
    top5: ['chatgpt', 'claude-ai', 'deepl', 'notion-ai', 'grammarly-ai'],
    useCases: [
      'Rédiger les actes notariés (vente, donation, testament)',
      'Expliquer clairement les actes aux clients',
      'Résumer des dossiers de succession complexes',
      'Traduire des actes étrangers',
    ],
    tempsGagne: '4-6h / semaine',
    budget: '20-40 € / mois',
    steps: [
      { title: 'Structurez vos actes avec ChatGPT', desc: 'Donnez les éléments essentiels à ChatGPT et obtenez une structure d\'acte complète à retravailler avec votre expertise.' },
      { title: 'Analysez les dossiers avec Claude', desc: 'Claude traite des documents longs. Uploadez un dossier de succession et obtenez un résumé des points sensibles et des étapes à suivre.' },
      { title: 'Gérez les dossiers dans Notion AI', desc: 'Notion AI permet de créer une base de données clients organisée avec résumés automatiques et suivi des étapes.' },
    ],
  },
  {
    slug: 'huissier',
    name: 'Huissier de justice',
    sector: 'Droit',
    icon: 'Scale',
    top5: ['chatgpt', 'claude-ai', 'notion-ai', 'grammarly-ai', 'deepl'],
    useCases: [
      'Rédiger les actes de signification et procès-verbaux',
      'Préparer les injonctions de payer',
      'Rédiger des courriers de mise en demeure',
      'Organiser le suivi des dossiers de recouvrement',
    ],
    tempsGagne: '3-5h / semaine',
    budget: '20-40 € / mois',
    steps: [
      { title: 'Rédigez vos actes avec ChatGPT', desc: 'Donnez les faits et les parties concernées pour obtenir un premier jet de procès-verbal ou de mise en demeure.' },
      { title: 'Suivez vos dossiers avec Notion AI', desc: 'Créez un tableau de bord de recouvrement dans Notion avec suivi des étapes, dates et montants.' },
      { title: 'Améliorez vos écrits avec Grammarly', desc: 'Grammarly corrige les tournures et assure la cohérence de vos documents officiels.' },
    ],
  },
  {
    slug: 'juriste',
    name: 'Juriste d\'entreprise',
    sector: 'Droit',
    icon: 'Scale',
    top5: ['chatgpt', 'claude-ai', 'perplexity', 'deepl', 'elicit-org'],
    useCases: [
      'Rédiger et analyser des contrats commerciaux',
      'Effectuer une veille réglementaire et juridique',
      'Préparer des notes de synthèse pour la direction',
      'Analyser les risques juridiques d\'un projet',
    ],
    tempsGagne: '5-8h / semaine',
    budget: '20-50 € / mois',
    steps: [
      { title: 'Analysez les contrats avec Claude', desc: 'Claude est excellent pour analyser des contrats longs. Demandez-lui les clauses à risque, les obligations de chaque partie et les points à renégocier.' },
      { title: 'Réalisez votre veille avec Perplexity', desc: 'Perplexity synthétise les nouvelles réglementations avec les sources. Idéal pour la veille RGPD, droit du travail, réglementation sectorielle.' },
      { title: 'Rédigez vos notes avec ChatGPT', desc: 'ChatGPT transforme vos analyses en notes de synthèse claires pour la direction, adaptées au niveau de compréhension souhaité.' },
    ],
  },
  {
    slug: 'clerc-de-notaire',
    name: 'Clerc de notaire',
    sector: 'Droit',
    icon: 'Scale',
    top5: ['chatgpt', 'deepl', 'grammarly-ai', 'notion-ai', 'claude-ai'],
    useCases: [
      'Préparer les dossiers et vérifier les pièces',
      'Rédiger les courriers aux clients et aux tiers',
      'Traduire des documents étrangers',
      'Créer des checklists de dossiers',
    ],
    tempsGagne: '2-4h / semaine',
    budget: '0-20 € / mois',
    steps: [
      { title: 'Organisez vos dossiers avec Notion AI', desc: 'Créez des templates de dossiers dans Notion pour chaque type d\'acte avec les pièces requises, dates et suivi.' },
      { title: 'Rédigez les courriers avec ChatGPT', desc: 'Générez rapidement des courriers de relance, demandes de pièces et confirmations de rendez-vous professionnels.' },
      { title: 'Vérifiez l\'orthographe avec Grammarly', desc: 'Grammarly assure la qualité rédactionnelle de tous vos documents officiels en temps réel.' },
    ],
  },

  // ── Finance ─────────────────────────────────────────────────────────────────
  {
    slug: 'comptable',
    name: 'Comptable',
    sector: 'Finance',
    icon: 'TrendingUp',
    top5: ['chatgpt', 'zeni-ai', 'vic-ai', 'ramp-ai', 'notion-ai'],
    useCases: [
      'Automatiser la saisie et le traitement des factures',
      'Générer des rapports financiers clairs pour les clients',
      'Rédiger des analyses financières et commentaires de comptes',
      'Préparer des notes d\'information fiscale',
    ],
    tempsGagne: '4-7h / semaine',
    budget: '20-60 € / mois',
    steps: [
      { title: 'Automatisez les factures avec Vic.ai', desc: 'Vic.ai automatise le traitement des factures fournisseurs et les intègre dans votre ERP. Réduction des erreurs de saisie de 90%.' },
      { title: 'Rédigez vos rapports avec ChatGPT', desc: 'Fournissez les chiffres clés et demandez à ChatGPT de rédiger le commentaire de gestion, les observations et les recommandations.' },
      { title: 'Suivez les dépenses avec Ramp AI', desc: 'Ramp analyse automatiquement les dépenses et identifie les économies potentielles pour vos clients PME.' },
    ],
  },
  {
    slug: 'expert-comptable',
    name: 'Expert-comptable',
    sector: 'Finance',
    icon: 'TrendingUp',
    top5: ['chatgpt', 'trullion', 'zeni-ai', 'alphasense', 'perplexity'],
    useCases: [
      'Automatiser les contrôles et révisions comptables',
      'Analyser les états financiers de clients en quelques minutes',
      'Effectuer une veille fiscale et réglementaire',
      'Rédiger les lettres de mission et rapports d\'audit',
    ],
    tempsGagne: '6-10h / semaine',
    budget: '50-150 € / mois',
    steps: [
      { title: 'Automatisez l\'audit avec Trullion', desc: 'Trullion automatise les contrôles IFRS, la révision des contrats et la réconciliation des données financières.' },
      { title: 'Faites votre veille avec Perplexity', desc: 'Restez à jour sur les évolutions fiscales et réglementaires avec des synthèses sourcées et quotidiennes.' },
      { title: 'Rédigez vos rapports avec ChatGPT', desc: 'ChatGPT transforme vos données en rapports de révision, lettres de recommandation et analyses de gestion clairs et professionnels.' },
    ],
  },
  {
    slug: 'conseiller-financier',
    name: 'Conseiller financier',
    sector: 'Finance',
    icon: 'TrendingUp',
    top5: ['chatgpt', 'alphasense', 'perplexity', 'notion-ai', 'gamma-app'],
    useCases: [
      'Analyser rapidement les marchés et les produits financiers',
      'Préparer des présentations de portefeuille pour les clients',
      'Rédiger des analyses et recommandations d\'investissement',
      'Vulgariser des concepts financiers complexes',
    ],
    tempsGagne: '4-6h / semaine',
    budget: '30-80 € / mois',
    steps: [
      { title: 'Analysez les marchés avec AlphaSense', desc: 'AlphaSense vous donne accès à des analyses de marchés, transcriptions de calls et rapports d\'analystes synthétisés par IA.' },
      { title: 'Préparez vos présentations avec Gamma', desc: 'Gamma crée des présentations client professionnelles à partir de vos données en quelques minutes. Impressionnez vos clients.' },
      { title: 'Rédigez vos analyses avec ChatGPT', desc: 'Fournissez les données de performance et obtenez des commentaires de gestion et des recommandations argumentées.' },
    ],
  },
  {
    slug: 'banquier',
    name: 'Chargé de clientèle bancaire',
    sector: 'Finance',
    icon: 'TrendingUp',
    top5: ['chatgpt', 'alphasense', 'perplexity', 'gamma-app', 'grammarly-ai'],
    useCases: [
      'Analyser les dossiers de crédit rapidement',
      'Préparer les présentations de produits pour les clients',
      'Rédiger les comptes-rendus de rendez-vous clients',
      'Effectuer une veille sur les produits concurrents',
    ],
    tempsGagne: '3-5h / semaine',
    budget: '20-40 € / mois',
    steps: [
      { title: 'Analysez les dossiers avec ChatGPT', desc: 'Donnez les éléments financiers d\'un client et obtenez une analyse du profil de risque, des points forts et des points de vigilance.' },
      { title: 'Préparez vos RDV avec Gamma', desc: 'Gamma crée des présentations de placement et de produits financiers visuellement impactantes pour vos rendez-vous clients.' },
      { title: 'Rédigez vos comptes-rendus avec ChatGPT', desc: 'Après chaque rendez-vous, dictez les points essentiels à ChatGPT pour obtenir un compte-rendu structuré et professionnel.' },
    ],
  },
  {
    slug: 'assureur',
    name: 'Conseiller en assurance',
    sector: 'Finance',
    icon: 'TrendingUp',
    top5: ['chatgpt', 'claude-ai', 'grammarly-ai', 'notion-ai', 'gamma-app'],
    useCases: [
      'Rédiger des propositions d\'assurance personnalisées',
      'Analyser et comparer les garanties de différents contrats',
      'Préparer des argumentaires de vente clairs',
      'Expliquer les contrats complexes aux assurés',
    ],
    tempsGagne: '3-5h / semaine',
    budget: '0-30 € / mois',
    steps: [
      { title: 'Rédigez vos propositions avec ChatGPT', desc: 'Entrez le profil du client et ses besoins, obtenez une proposition d\'assurance personnalisée et argumentée.' },
      { title: 'Analysez les contrats avec Claude', desc: 'Uploadez deux contrats et demandez à Claude de comparer les garanties, exclusions et tarifs pour conseiller au mieux votre client.' },
      { title: 'Présentez avec Gamma', desc: 'Créez des slides claires qui expliquent visuellement les garanties et la valeur ajoutée de votre offre.' },
    ],
  },

  // ── Éducation ───────────────────────────────────────────────────────────────
  {
    slug: 'professeur',
    name: 'Professeur',
    sector: 'Éducation',
    icon: 'GraduationCap',
    top5: ['chatgpt', 'notion-ai', 'canva-ai', 'grammarly-ai', 'duolingo-ai'],
    useCases: [
      'Créer des cours, exercices et évaluations en quelques minutes',
      'Différencier les supports selon les niveaux des élèves',
      'Générer des corrections types et grilles d\'évaluation',
      'Préparer des présentations pédagogiques visuelles',
    ],
    tempsGagne: '5-8h / semaine',
    budget: '0-20 € / mois',
    steps: [
      { title: 'Créez vos cours avec ChatGPT', desc: 'Demandez à ChatGPT de créer un plan de cours, des exercices progressifs et un quiz de 10 questions sur n\'importe quel sujet de votre programme.' },
      { title: 'Illustrez avec Canva AI', desc: 'Canva AI génère des supports visuels, infographies et présentations adaptés à vos élèves en quelques clics.' },
      { title: 'Organisez vos ressources avec Notion AI', desc: 'Centralisez toutes vos ressources pédagogiques dans Notion avec résumés automatiques et liens vers les programmes officiels.' },
    ],
  },
  {
    slug: 'formateur',
    name: 'Formateur',
    sector: 'Éducation',
    icon: 'GraduationCap',
    top5: ['synthesia', 'chatgpt', 'canva-ai', 'gamma-app', 'notion-ai'],
    useCases: [
      'Créer des modules e-learning avec avatars IA',
      'Concevoir des supports de formation attractifs',
      'Générer des cas pratiques et mises en situation',
      'Évaluer et personnaliser les parcours apprenants',
    ],
    tempsGagne: '6-10h / semaine',
    budget: '30-80 € / mois',
    steps: [
      { title: 'Créez vos vidéos e-learning avec Synthesia', desc: 'Synthesia transforme vos scripts en vidéos de formation professionnelles avec un présentateur IA. Pas besoin de caméra ni de studio.' },
      { title: 'Structurez vos modules avec ChatGPT', desc: 'Demandez à ChatGPT de créer le plan pédagogique, les objectifs, les exercices et les évaluations pour chaque module.' },
      { title: 'Créez vos supports avec Gamma', desc: 'Gamma génère des présentations de formation élégantes directement depuis votre plan. Exportez en PDF ou présentez en ligne.' },
    ],
  },
  {
    slug: 'coach',
    name: 'Coach professionnel',
    sector: 'Éducation',
    icon: 'GraduationCap',
    top5: ['chatgpt', 'claude-ai', 'notion-ai', 'otter-ai', 'gamma-app'],
    useCases: [
      'Préparer des séances de coaching personnalisées',
      'Prendre des notes et compte-rendus de séances',
      'Créer des outils et exercices pour les clients',
      'Développer du contenu marketing (blog, LinkedIn)',
    ],
    tempsGagne: '4-6h / semaine',
    budget: '20-40 € / mois',
    steps: [
      { title: 'Transcrivez vos séances avec Otter.ai', desc: 'Otter.ai transcrit automatiquement vos séances de coaching, génère les points clés et les engagements du client.' },
      { title: 'Préparez vos outils avec ChatGPT', desc: 'ChatGPT crée des questionnaires, exercices de visualisation, fiches de travail et plans d\'action personnalisés pour chaque client.' },
      { title: 'Créez votre contenu avec Claude', desc: 'Claude vous aide à rédiger des articles LinkedIn, newsletters et posts authentiques qui reflètent votre approche de coaching.' },
    ],
  },
  {
    slug: 'tuteur',
    name: 'Tuteur / Répétiteur',
    sector: 'Éducation',
    icon: 'GraduationCap',
    top5: ['chatgpt', 'perplexity', 'notion-ai', 'grammarly-ai', 'duolingo-ai'],
    useCases: [
      'Créer des exercices adaptés au niveau de l\'élève',
      'Expliquer des concepts difficiles différemment',
      'Générer des fiches de révision visuelles',
      'Préparer les examens avec des sujets types',
    ],
    tempsGagne: '3-5h / semaine',
    budget: '0-20 € / mois',
    steps: [
      { title: 'Expliquez avec ChatGPT', desc: 'Demandez à ChatGPT d\'expliquer un concept difficile avec 3 analogies différentes adaptées à l\'âge et au niveau de votre élève.' },
      { title: 'Créez des fiches de révision', desc: 'ChatGPT génère des fiches synthèse, tableaux comparatifs et QCM sur n\'importe quel sujet de programme scolaire.' },
      { title: 'Organisez avec Notion AI', desc: 'Créez un espace Notion par élève avec le suivi des progrès, les points à retravailler et le planning des révisions.' },
    ],
  },
  {
    slug: 'directeur-ecole',
    name: 'Directeur d\'école',
    sector: 'Éducation',
    icon: 'GraduationCap',
    top5: ['chatgpt', 'notion-ai', 'gamma-app', 'otter-ai', 'grammarly-ai'],
    useCases: [
      'Rédiger les communications aux parents et enseignants',
      'Créer des rapports d\'activité et bilans pédagogiques',
      'Préparer les conseils de classe et réunions',
      'Rédiger le projet d\'établissement',
    ],
    tempsGagne: '4-6h / semaine',
    budget: '0-30 € / mois',
    steps: [
      { title: 'Gérez vos communications avec ChatGPT', desc: 'Rédigez les lettres aux parents, emails aux enseignants et circulaires officielles en quelques secondes avec le bon ton.' },
      { title: 'Organisez l\'établissement avec Notion AI', desc: 'Créez un intranet d\'école dans Notion avec le planning, les projets, les ressources pédagogiques et le suivi des actions.' },
      { title: 'Préparez vos présentations avec Gamma', desc: 'Gamma génère des présentations professionnelles pour les conseils d\'administration, réunions parents-professeurs et journées pédagogiques.' },
    ],
  },

  // ── Tech ────────────────────────────────────────────────────────────────────
  {
    slug: 'developpeur',
    name: 'Développeur',
    sector: 'Tech',
    icon: 'Code2',
    top5: ['github-copilot', 'cursor', 'chatgpt', 'perplexity', 'warp'],
    useCases: [
      'Autocomplétion et génération de code intelligente',
      'Débogage et explication des erreurs',
      'Revue de code et suggestions d\'optimisation',
      'Génération de tests unitaires automatiques',
      'Documentation de code en un clic',
    ],
    tempsGagne: '8-15h / semaine',
    budget: '10-40 € / mois',
    steps: [
      { title: 'Installez GitHub Copilot', desc: 'GitHub Copilot s\'intègre directement dans VS Code, JetBrains ou Neovim. Il complète votre code en temps réel et génère des fonctions entières depuis un commentaire.' },
      { title: 'Passez à Cursor pour les refactors complexes', desc: 'Cursor permet de modifier plusieurs fichiers à la fois avec du contexte, de comprendre une codebase entière et de générer des PRs complètes.' },
      { title: 'Utilisez Perplexity pour le débogage', desc: 'Perplexity est un moteur de réponse IA qui cite ses sources. Plus efficace que Stack Overflow pour comprendre les erreurs complexes avec des explications contextualisées.' },
    ],
  },
  {
    slug: 'designer-ux',
    name: 'Designer UX/UI',
    sector: 'Tech',
    icon: 'Code2',
    top5: ['figma-ai', 'midjourney', 'uizard', 'framer-ai', 'canva-ai'],
    useCases: [
      'Générer des maquettes et wireframes depuis des descriptions',
      'Créer des variations visuelles rapidement',
      'Générer des illustrations et assets graphiques',
      'Convertir des screenshots en prototypes éditables',
      'Créer des sites web à partir de maquettes',
    ],
    tempsGagne: '6-12h / semaine',
    budget: '20-60 € / mois',
    steps: [
      { title: 'Générez des maquettes avec Figma AI', desc: 'Figma AI génère des composants et layouts complets depuis une description textuelle. Utilisez "Make Designs" pour prototyper en quelques minutes.' },
      { title: 'Explorez les visuels avec Midjourney', desc: 'Midjourney pour explorer les directions visuelles, générer des illustrations, des backgrounds et des concepts UI dès la phase de discovery.' },
      { title: 'Passez au web avec Framer AI', desc: 'Framer AI convertit vos maquettes Figma en sites web animés et responsives. Idéal pour les prototypes haute-fidélité et les landing pages.' },
    ],
  },
  {
    slug: 'chef-de-projet',
    name: 'Chef de projet',
    sector: 'Tech',
    icon: 'Code2',
    top5: ['notion-ai', 'monday-ai', 'otter-ai', 'gamma-app', 'taskade'],
    useCases: [
      'Générer des plans de projet et matrices RACI',
      'Transcrire et résumer les réunions automatiquement',
      'Créer des rapports de statut et reporting hebdomadaire',
      'Rédiger des spécifications fonctionnelles',
    ],
    tempsGagne: '5-8h / semaine',
    budget: '20-50 € / mois',
    steps: [
      { title: 'Transcrivez vos réunions avec Otter.ai', desc: 'Otter.ai rejoint automatiquement vos calls Teams/Zoom, transcrit tout et génère le compte-rendu avec les actions identifiées.' },
      { title: 'Gérez les tâches avec Monday AI', desc: 'Monday AI génère des plans de sprint, assigne les tâches automatiquement et prédit les risques de dérapage calendaire.' },
      { title: 'Rédigez vos specs avec Notion AI', desc: 'Notion AI transforme vos notes brutes en user stories, critères d\'acceptance et documentation technique structurée.' },
    ],
  },
  {
    slug: 'data-scientist',
    name: 'Data Scientist',
    sector: 'Tech',
    icon: 'Code2',
    top5: ['chatgpt', 'claude-ai', 'perplexity', 'elicit-org', 'consensus-app'],
    useCases: [
      'Générer et déboguer du code Python/R/SQL',
      'Expliquer et documenter les modèles',
      'Effectuer une revue de littérature scientifique',
      'Préparer des présentations de résultats',
    ],
    tempsGagne: '6-10h / semaine',
    budget: '20-50 € / mois',
    steps: [
      { title: 'Codez avec ChatGPT', desc: 'ChatGPT génère du code Python, crée des notebooks Jupyter, explique les erreurs et propose des optimisations de modèles.' },
      { title: 'Explorez la littérature avec Elicit', desc: 'Elicit analyse automatiquement les papiers académiques sur votre sujet, extrait les méthodes et résultats, et synthétise l\'état de l\'art.' },
      { title: 'Rédigez avec Claude', desc: 'Claude est idéal pour rédiger des rapports d\'analyse, des synthèses de résultats et la documentation technique de vos modèles.' },
    ],
  },
  {
    slug: 'devops',
    name: 'Ingénieur DevOps',
    sector: 'Tech',
    icon: 'Code2',
    top5: ['chatgpt', 'github-copilot', 'cursor', 'warp', 'perplexity'],
    useCases: [
      'Générer des scripts d\'automatisation et pipelines CI/CD',
      'Déboguer les configurations d\'infrastructure',
      'Rédiger la documentation technique',
      'Analyser les logs et identifier les incidents',
    ],
    tempsGagne: '6-12h / semaine',
    budget: '10-40 € / mois',
    steps: [
      { title: 'Maîtrisez Warp pour le terminal', desc: 'Warp est un terminal IA qui comprend vos commandes en langage naturel, explique les erreurs et suggère les corrections.' },
      { title: 'Générez vos scripts avec ChatGPT', desc: 'ChatGPT génère des scripts Bash, des configurations Terraform, Kubernetes et des Dockerfiles en quelques secondes.' },
      { title: 'Déboguez avec Perplexity', desc: 'Perplexity comprend les stack traces et les erreurs d\'infrastructure en citant des sources précises. Collez votre erreur et obtenez une solution contextualisée.' },
    ],
  },

  // ── Marketing ───────────────────────────────────────────────────────────────
  {
    slug: 'community-manager',
    name: 'Community Manager',
    sector: 'Marketing',
    icon: 'Megaphone',
    top5: ['chatgpt', 'canva-ai', 'predis-ai', 'capcut-ai', 'jasper-ai'],
    useCases: [
      'Générer un mois de contenu réseaux sociaux en une heure',
      'Créer des visuels et Reels attractifs',
      'Rédiger les réponses aux commentaires et messages',
      'Analyser les tendances et trouver des idées de contenus',
    ],
    tempsGagne: '8-15h / semaine',
    budget: '30-80 € / mois',
    steps: [
      { title: 'Planifiez avec Predis.ai', desc: 'Predis.ai génère automatiquement un calendrier éditorial avec posts, légendes et visuels adaptés à votre secteur et à vos objectifs.' },
      { title: 'Créez vos visuels avec Canva AI', desc: 'Les templates IA de Canva s\'adaptent à votre charte graphique. Générez 30 posts cohérents en 30 minutes.' },
      { title: 'Montez vos Reels avec CapCut AI', desc: 'CapCut AI ajoute automatiquement sous-titres, musique tendance et effets à vos vidéos pour maximiser l\'engagement.' },
    ],
  },
  {
    slug: 'redacteur-web',
    name: 'Rédacteur web',
    sector: 'Marketing',
    icon: 'Megaphone',
    top5: ['jasper-ai', 'surfer-seo', 'grammarly-ai', 'chatgpt', 'writesonic'],
    useCases: [
      'Rédiger des articles SEO optimisés rapidement',
      'Trouver les bons mots-clés et structurer les contenus',
      'Adapter le ton et le style selon les clients',
      'Créer des méta-descriptions et titres accrocheurs',
    ],
    tempsGagne: '8-15h / semaine',
    budget: '50-150 € / mois',
    steps: [
      { title: 'Structurez avec Surfer SEO', desc: 'Surfer SEO analyse les 10 premiers résultats Google et vous donne le plan exact, les mots-clés et le nombre de mots pour vous positionner.' },
      { title: 'Rédigez avec Jasper', desc: 'Jasper est calibré pour le contenu marketing. Donnez-lui votre brief et obtenez un article optimisé, à la voix de votre marque.' },
      { title: 'Corrigez avec Grammarly', desc: 'Grammarly corrige la grammaire, améliore le style et mesure la lisibilité pour que vos articles restent humains et engageants.' },
    ],
  },
  {
    slug: 'seo',
    name: 'Consultant SEO',
    sector: 'Marketing',
    icon: 'Megaphone',
    top5: ['surfer-seo', 'semrush-ai', 'chatgpt', 'writesonic', 'perplexity'],
    useCases: [
      'Analyser les positions et les opportunités de mots-clés',
      'Créer des briefs de contenu ultra-précis',
      'Auditer les sites et prioriser les corrections',
      'Construire des stratégies de liens et netlinking',
    ],
    tempsGagne: '8-15h / semaine',
    budget: '100-300 € / mois',
    steps: [
      { title: 'Auditez avec Semrush AI', desc: 'Semrush AI identifie les failles techniques, les opportunités de keywords et le gap avec vos concurrents en quelques minutes.' },
      { title: 'Créez des briefs avec Surfer SEO', desc: 'Surfer génère des briefs complets avec structure, mots-clés sémantiques et score de contenu cible pour chaque article.' },
      { title: 'Rédigez les metas avec ChatGPT', desc: 'ChatGPT génère des titres, descriptions et balises H1 optimisés en masse pour des centaines de pages simultanément.' },
    ],
  },
  {
    slug: 'chef-de-pub',
    name: 'Chef de publicité',
    sector: 'Marketing',
    icon: 'Megaphone',
    top5: ['adcreative-ai', 'chatgpt', 'semrush-ai', 'canva-ai', 'hubspot-ai'],
    useCases: [
      'Générer des centaines de variantes de créatives publicitaires',
      'Rédiger des accroches et call-to-action percutants',
      'Analyser les performances et optimiser les campagnes',
      'Créer des briefs créatifs pour les équipes',
    ],
    tempsGagne: '6-10h / semaine',
    budget: '50-150 € / mois',
    steps: [
      { title: 'Générez des créatives avec AdCreative.ai', desc: 'AdCreative.ai crée des centaines de visuels publicitaires adaptés à Facebook, Google, LinkedIn avec scores de conversion prédits.' },
      { title: 'Rédigez les copies avec ChatGPT', desc: 'ChatGPT génère 20 variantes d\'accroches, de descriptions et de CTA en quelques secondes. Testez et gardez les meilleures.' },
      { title: 'Analysez avec Semrush AI', desc: 'Semrush révèle les stratégies publicitaires de vos concurrents : quelles créatives tournent depuis longtemps, quels mots-clés ils achètent.' },
    ],
  },
  {
    slug: 'graphiste',
    name: 'Graphiste',
    sector: 'Marketing',
    icon: 'Megaphone',
    top5: ['midjourney', 'canva-ai', 'adobe-firefly', 'figma-ai', 'remove-bg'],
    useCases: [
      'Générer des concepts visuels et moodboards rapidement',
      'Créer des illustrations et assets graphiques originaux',
      'Retoucher et détourer des images automatiquement',
      'Explorer des directions artistiques pour les clients',
    ],
    tempsGagne: '8-15h / semaine',
    budget: '30-80 € / mois',
    steps: [
      { title: 'Conceptualisez avec Midjourney', desc: 'Midjourney génère des visuels de haute qualité pour explorer les directions artistiques. Parfait pour les moodboards et présentations clients.' },
      { title: 'Retouchez avec Adobe Firefly', desc: 'Adobe Firefly s\'intègre dans Photoshop pour le remplissage génératif, la suppression d\'objets et l\'expansion d\'images. Légal et safe pour le commercial.' },
      { title: 'Détourer avec Remove.bg', desc: 'Remove.bg supprime les arrière-plans en un clic avec une précision IA. Idéal pour les photos produits et les packshots.' },
    ],
  },

  // ── Commerce ─────────────────────────────────────────────────────────────────
  {
    slug: 'commercial',
    name: 'Commercial',
    sector: 'Commerce',
    icon: 'ShoppingBag',
    top5: ['chatgpt', 'hubspot-ai', 'otter-ai', 'notion-ai', 'gamma-app'],
    useCases: [
      'Personnaliser les emails et argumentaires de vente',
      'Préparer les rendez-vous et qualifier les prospects',
      'Rédiger des propositions commerciales convaincantes',
      'Analyser les objections et préparer les réponses',
    ],
    tempsGagne: '5-8h / semaine',
    budget: '20-60 € / mois',
    steps: [
      { title: 'Personnalisez vos emails avec ChatGPT', desc: 'Donnez le profil LinkedIn et le contexte du prospect à ChatGPT pour obtenir un email de prospection personnalisé et pertinent.' },
      { title: 'Gérez vos prospects avec HubSpot AI', desc: 'HubSpot AI enregistre automatiquement les interactions, prédit la probabilité de conversion et suggère les prochaines actions à effectuer.' },
      { title: 'Transcrivez vos appels avec Otter.ai', desc: 'Otter.ai transcrit vos appels de vente, identifie les points clés et génère un résumé avec les prochaines étapes et engagements.' },
    ],
  },
  {
    slug: 'e-commercant',
    name: 'E-commerçant',
    sector: 'Commerce',
    icon: 'ShoppingBag',
    top5: ['chatgpt', 'canva-ai', 'jasper-ai', 'mailchimp-ai', 'midjourney'],
    useCases: [
      'Rédiger des fiches produits optimisées SEO en masse',
      'Créer des visuels produits attractifs',
      'Automatiser les emails transactionnels et de relance',
      'Générer du contenu pour les réseaux sociaux',
    ],
    tempsGagne: '8-15h / semaine',
    budget: '30-80 € / mois',
    steps: [
      { title: 'Rédigez vos fiches produits avec ChatGPT', desc: 'ChatGPT génère des descriptions produits SEO-friendly en masse. Créez un prompt template et traitez 100 produits en une heure.' },
      { title: 'Créez vos visuels avec Canva AI', desc: 'Canva AI génère des visuels de produits professionnels avec fonds, textes et badges promotionnels en adéquation avec votre charte.' },
      { title: 'Automatisez vos emails avec Mailchimp AI', desc: 'Mailchimp AI personnalise les emails de relance panier abandonné, confirmation de commande et emails promotionnels selon le comportement d\'achat.' },
    ],
  },
  {
    slug: 'responsable-retail',
    name: 'Responsable retail',
    sector: 'Commerce',
    icon: 'ShoppingBag',
    top5: ['chatgpt', 'monday-ai', 'notion-ai', 'mailchimp-ai', 'canva-ai'],
    useCases: [
      'Créer les plannings et communications équipe',
      'Rédiger les supports de formation pour les vendeurs',
      'Analyser les ventes et préparer les reportings',
      'Concevoir les supports visuels de merchandising',
    ],
    tempsGagne: '4-6h / semaine',
    budget: '20-50 € / mois',
    steps: [
      { title: 'Gérez votre équipe avec Monday AI', desc: 'Monday AI automatise les plannings, les tâches et les relances équipe. Suivez les KPI de chaque vendeur en temps réel.' },
      { title: 'Créez vos formations avec ChatGPT', desc: 'ChatGPT génère des modules de formation produit, des scripts de vente et des guides de réponse aux objections pour votre équipe.' },
      { title: 'Concevez vos supports avec Canva AI', desc: 'Canva AI crée les affiches promotionnelles, PLV et supports de merchandising de manière cohérente et rapide.' },
    ],
  },
  {
    slug: 'account-manager',
    name: 'Account Manager',
    sector: 'Commerce',
    icon: 'ShoppingBag',
    top5: ['chatgpt', 'hubspot-ai', 'otter-ai', 'notion-ai', 'gamma-app'],
    useCases: [
      'Préparer les revues de compte et bilans clients',
      'Rédiger les comptes-rendus de réunion',
      'Créer des propositions de renouvellement et upsell',
      'Anticiper les risques de churn avec les données client',
    ],
    tempsGagne: '4-7h / semaine',
    budget: '20-50 € / mois',
    steps: [
      { title: 'Préparez vos revues avec Gamma', desc: 'Gamma crée des business reviews client professionnelles avec graphiques, KPIs et recommandations en quelques minutes depuis vos données.' },
      { title: 'Transcrivez vos appels avec Otter.ai', desc: 'Otter.ai capture tous vos appels clients, identifie les risques, les opportunités et les actions à suivre automatiquement.' },
      { title: 'Gérez le CRM avec HubSpot AI', desc: 'HubSpot AI met à jour automatiquement les fiches client, prédit le risque de churn et suggère les actions de fidélisation prioritaires.' },
    ],
  },
  {
    slug: 'acheteur',
    name: 'Acheteur',
    sector: 'Commerce',
    icon: 'ShoppingBag',
    top5: ['chatgpt', 'perplexity', 'notion-ai', 'monday-ai', 'claude-ai'],
    useCases: [
      'Analyser et comparer les offres fournisseurs',
      'Rédiger les cahiers des charges et appels d\'offres',
      'Préparer les négociations avec des argumentaires solides',
      'Effectuer une veille marché et prix',
    ],
    tempsGagne: '4-6h / semaine',
    budget: '20-40 € / mois',
    steps: [
      { title: 'Analysez les offres avec Claude', desc: 'Uploadez plusieurs offres fournisseurs et demandez à Claude un tableau comparatif objectif avec les points forts et faibles de chacune.' },
      { title: 'Rédigez vos cahiers des charges avec ChatGPT', desc: 'ChatGPT structure vos cahiers des charges, définit les critères d\'évaluation et génère les clauses contractuelles types.' },
      { title: 'Faites votre veille avec Perplexity', desc: 'Perplexity analyse les prix de marché, identifie de nouveaux fournisseurs et surveille les évolutions du secteur.' },
    ],
  },

  // ── Santé mentale ────────────────────────────────────────────────────────────
  {
    slug: 'psychologue',
    name: 'Psychologue',
    sector: 'Santé mentale',
    icon: 'Brain',
    top5: ['chatgpt', 'claude-ai', 'notion-ai', 'otter-ai', 'grammarly-ai'],
    useCases: [
      'Rédiger les comptes-rendus de séances',
      'Préparer des protocoles et outils thérapeutiques',
      'Effectuer une veille sur la recherche en psychologie',
      'Créer des ressources pédagogiques pour les patients',
    ],
    tempsGagne: '3-5h / semaine',
    budget: '0-30 € / mois',
    steps: [
      { title: 'Rédigez vos notes avec ChatGPT', desc: 'Après chaque séance, dictez vos observations à ChatGPT pour obtenir un compte-rendu structuré. Respectez la confidentialité : ne mentionnez pas le nom du patient.' },
      { title: 'Organisez vos dossiers avec Notion AI', desc: 'Notion AI crée une base de données de dossiers patients anonymisée avec suivi des objectifs thérapeutiques et des progrès.' },
      { title: 'Faites votre veille avec Elicit', desc: 'Elicit analyse les publications scientifiques en psychologie et vous donne des synthèses des études récentes sur les thérapies.' },
    ],
  },
  {
    slug: 'therapeute',
    name: 'Thérapeute',
    sector: 'Santé mentale',
    icon: 'Brain',
    top5: ['chatgpt', 'claude-ai', 'notion-ai', 'otter-ai', 'speechify'],
    useCases: [
      'Créer des exercices et protocoles pour les patients',
      'Rédiger des supports de communication et de présentation',
      'Organiser les dossiers et le suivi thérapeutique',
      'Développer du contenu de sensibilisation',
    ],
    tempsGagne: '3-5h / semaine',
    budget: '0-20 € / mois',
    steps: [
      { title: 'Créez des exercices avec ChatGPT', desc: 'Demandez à ChatGPT de créer des exercices de relaxation, de pleine conscience ou des journaux de bord adaptés à chaque type de patient.' },
      { title: 'Gérez votre cabinet avec Notion AI', desc: 'Notion AI structure votre planning, vos ressources thérapeutiques et vos suivis de patients dans un espace organisé.' },
      { title: 'Préparez vos formations avec Claude', desc: 'Claude vous aide à créer des ateliers, supports de groupe et documents de psychoéducation pour vos patients.' },
    ],
  },
  {
    slug: 'coach-de-vie',
    name: 'Coach de vie',
    sector: 'Santé mentale',
    icon: 'Brain',
    top5: ['chatgpt', 'notion-ai', 'gamma-app', 'claude-ai', 'canva-ai'],
    useCases: [
      'Créer des programmes de coaching personnalisés',
      'Concevoir des outils de développement personnel',
      'Développer son activité et son marketing digital',
      'Produire du contenu inspirationnel pour les réseaux',
    ],
    tempsGagne: '5-8h / semaine',
    budget: '20-40 € / mois',
    steps: [
      { title: 'Créez vos programmes avec ChatGPT', desc: 'ChatGPT génère des programmes de coaching complets : objectifs, exercices hebdomadaires, outils de suivi et questionnaires personnalisés.' },
      { title: 'Présentez avec Gamma', desc: 'Gamma crée des présentations de votre offre coaching, des ebooks et des supports de programme visuellement attractifs.' },
      { title: 'Communiquez avec Claude', desc: 'Claude vous aide à rédiger des newsletters, posts LinkedIn et contenus qui reflètent votre philosophie et attirent vos clients idéaux.' },
    ],
  },
  {
    slug: 'sophrologue',
    name: 'Sophrologue',
    sector: 'Santé mentale',
    icon: 'Brain',
    top5: ['chatgpt', 'notion-ai', 'canva-ai', 'elevenlabs', 'murf-ai'],
    useCases: [
      'Créer des séances de sophrologie audio personnalisées',
      'Rédiger des scripts de visualisation et relaxation',
      'Concevoir des supports visuels pour les séances de groupe',
      'Développer des programmes thématiques',
    ],
    tempsGagne: '3-6h / semaine',
    budget: '20-50 € / mois',
    steps: [
      { title: 'Rédigez vos scripts avec ChatGPT', desc: 'ChatGPT génère des scripts de sophrologie de haute qualité : relaxation dynamique, visualisations positives, ancrage.' },
      { title: 'Enregistrez avec ElevenLabs', desc: 'ElevenLabs transforme vos scripts en voix ultra-réalistes et apaisantes. Clonez même votre propre voix pour des séances audio personnalisées.' },
      { title: 'Créez vos supports visuels avec Canva AI', desc: 'Canva AI génère des affiches, guides et cartes de séance visuellement apaisants cohérents avec votre image.' },
    ],
  },

  // ── Artisanat ────────────────────────────────────────────────────────────────
  {
    slug: 'plombier',
    name: 'Plombier',
    sector: 'Artisanat',
    icon: 'Hammer',
    top5: ['chatgpt', 'canva-ai', 'notion-ai', 'grammarly-ai', 'gamma-app'],
    useCases: [
      'Rédiger les devis et factures professionnels',
      'Créer des fiches d\'intervention et rapports',
      'Communiquer avec les clients par email',
      'Créer des supports de communication pour son activité',
    ],
    tempsGagne: '2-4h / semaine',
    budget: '0-15 € / mois',
    steps: [
      { title: 'Rédigez vos devis avec ChatGPT', desc: 'Décrivez les travaux à effectuer et obtenez un devis professionnel clair avec détail des prestations, matériaux et délais.' },
      { title: 'Créez votre communication avec Canva AI', desc: 'Canva AI crée vos cartes de visite, flyers et présence sur les réseaux avec votre logo et vos coordonnées.' },
      { title: 'Répondez aux emails avec ChatGPT', desc: 'ChatGPT rédige des réponses professionnelles aux demandes de clients, aux réclamations et aux demandes de devis.' },
    ],
  },
  {
    slug: 'electricien',
    name: 'Électricien',
    sector: 'Artisanat',
    icon: 'Hammer',
    top5: ['chatgpt', 'notion-ai', 'canva-ai', 'grammarly-ai', 'claude-ai'],
    useCases: [
      'Rédiger les rapports d\'intervention et attestations',
      'Créer les devis détaillés pour les clients',
      'Préparer les dossiers de certification et conformité',
      'Communiquer clairement avec les clients sur les travaux',
    ],
    tempsGagne: '2-3h / semaine',
    budget: '0-15 € / mois',
    steps: [
      { title: 'Rédigez vos attestations avec ChatGPT', desc: 'ChatGPT génère des attestations de conformité, rapports d\'intervention et documents Consuel professionnels et précis.' },
      { title: 'Organisez vos dossiers avec Notion', desc: 'Créez un suivi de chantiers dans Notion avec les étapes, documents et photos de chaque intervention.' },
      { title: 'Créez vos devis avec ChatGPT', desc: 'Entrez le descriptif des travaux et obtenez un devis structuré avec fournitures, main d\'œuvre et conditions.' },
    ],
  },
  {
    slug: 'menuisier',
    name: 'Menuisier',
    sector: 'Artisanat',
    icon: 'Hammer',
    top5: ['chatgpt', 'canva-ai', 'midjourney', 'notion-ai', 'grammarly-ai'],
    useCases: [
      'Générer des visualisations de meubles sur mesure',
      'Rédiger des devis et plans de fabrication clairs',
      'Créer un portfolio visuel de réalisations',
      'Communiquer avec les clients sur les projets',
    ],
    tempsGagne: '2-4h / semaine',
    budget: '10-30 € / mois',
    steps: [
      { title: 'Visualisez vos créations avec Midjourney', desc: 'Midjourney génère des rendus réalistes de vos projets de menuiserie. Montrez à vos clients le résultat final avant fabrication.' },
      { title: 'Rédigez vos devis avec ChatGPT', desc: 'Décrivez les dimensions, essences et finitions pour obtenir un devis professionnel avec description technique détaillée.' },
      { title: 'Montrez votre travail avec Canva AI', desc: 'Canva AI crée un portfolio en ligne et des posts réseaux sociaux qui mettent en valeur vos réalisations.' },
    ],
  },
  {
    slug: 'macon',
    name: 'Maçon',
    sector: 'Artisanat',
    icon: 'Hammer',
    top5: ['chatgpt', 'canva-ai', 'notion-ai', 'gamma-app', 'grammarly-ai'],
    useCases: [
      'Rédiger les devis de chantier détaillés',
      'Créer les plans de chantier et fiches techniques',
      'Préparer les documents administratifs',
      'Communiquer avec les maîtres d\'ouvrage',
    ],
    tempsGagne: '2-4h / semaine',
    budget: '0-15 € / mois',
    steps: [
      { title: 'Rédigez vos devis avec ChatGPT', desc: 'Décrivez le chantier (surface, type de travaux, matériaux) pour obtenir un devis structuré et professionnel.' },
      { title: 'Présentez vos projets avec Gamma', desc: 'Gamma crée des présentations de projets convaincantes pour décrocher les chantiers importants.' },
      { title: 'Communiquez avec ChatGPT', desc: 'ChatGPT rédige vos emails aux architectes, maîtres d\'ouvrage et fournisseurs de manière professionnelle.' },
    ],
  },
  {
    slug: 'peintre',
    name: 'Peintre en bâtiment',
    sector: 'Artisanat',
    icon: 'Hammer',
    top5: ['chatgpt', 'midjourney', 'canva-ai', 'adobe-firefly', 'ideogram'],
    useCases: [
      'Générer des simulations de couleurs pour les clients',
      'Créer des devis avec descriptif des travaux',
      'Développer la présence en ligne et le portfolio',
      'Répondre professionnellement aux clients',
    ],
    tempsGagne: '2-4h / semaine',
    budget: '10-30 € / mois',
    steps: [
      { title: 'Simulez les couleurs avec Midjourney', desc: 'Uploadez une photo de la pièce et demandez à Midjourney de visualiser différentes couleurs et finitions avant les travaux.' },
      { title: 'Rédigez vos devis avec ChatGPT', desc: 'ChatGPT génère des devis professionnels avec description des préparations de surface, produits utilisés et conditions d\'application.' },
      { title: 'Créez votre vitrine avec Canva AI', desc: 'Canva AI crée un portfolio de vos chantiers et des posts Instagram qui montrent la qualité de votre travail.' },
    ],
  },

  // ── Restauration ─────────────────────────────────────────────────────────────
  {
    slug: 'chef-cuisinier',
    name: 'Chef cuisinier',
    sector: 'Restauration',
    icon: 'ChefHat',
    top5: ['chatgpt', 'midjourney', 'canva-ai', 'notion-ai', 'claude-ai'],
    useCases: [
      'Créer et optimiser des recettes selon les contraintes',
      'Concevoir des menus saisonniers équilibrés',
      'Générer des visuels de plats pour le marketing',
      'Rédiger des fiches techniques de recette',
    ],
    tempsGagne: '3-5h / semaine',
    budget: '15-40 € / mois',
    steps: [
      { title: 'Créez vos recettes avec ChatGPT', desc: 'Donnez vos contraintes (ingrédients disponibles, allergènes, budget) et obtenez des recettes créatives avec fiches techniques complètes.' },
      { title: 'Photographiez vos plats avec Midjourney', desc: 'Midjourney génère des visuels de food photography professionnels de vos plats pour vos menus et réseaux sociaux.' },
      { title: 'Gérez vos recettes avec Notion AI', desc: 'Centralisez toutes vos fiches techniques, coûts matières et fiches allergènes dans Notion.' },
    ],
  },
  {
    slug: 'restaurateur',
    name: 'Restaurateur',
    sector: 'Restauration',
    icon: 'ChefHat',
    top5: ['chatgpt', 'canva-ai', 'notion-ai', 'mailchimp-ai', 'predis-ai'],
    useCases: [
      'Gérer la communication et les réseaux sociaux',
      'Rédiger les menus et descriptions de plats',
      'Automatiser les emails clients et newsletters',
      'Analyser les avis et gérer la e-réputation',
    ],
    tempsGagne: '4-6h / semaine',
    budget: '20-50 € / mois',
    steps: [
      { title: 'Animez vos réseaux avec Predis.ai', desc: 'Predis.ai génère automatiquement vos posts Instagram avec visuels et descriptions adaptés à votre restaurant.' },
      { title: 'Créez vos menus avec Canva AI', desc: 'Canva AI crée des menus élégants, des affiches du jour et des supports promotionnels cohérents avec votre identité.' },
      { title: 'Fidélisez avec Mailchimp AI', desc: 'Mailchimp AI automatise vos campagnes email : newsletter des nouveaux menus, offres anniversaire et rappels de réservation.' },
    ],
  },
  {
    slug: 'barman',
    name: 'Barman / Bartender',
    sector: 'Restauration',
    icon: 'ChefHat',
    top5: ['chatgpt', 'canva-ai', 'midjourney', 'notion-ai', 'predis-ai'],
    useCases: [
      'Créer des cocktails originaux et signatures',
      'Concevoir la carte des boissons',
      'Créer du contenu pour les réseaux sociaux',
      'Gérer les stocks et les commandes',
    ],
    tempsGagne: '2-4h / semaine',
    budget: '0-20 € / mois',
    steps: [
      { title: 'Créez vos cocktails avec ChatGPT', desc: 'Décrivez les spiritueux disponibles, le concept du bar et vos contraintes pour obtenir des recettes de cocktails originaux avec histoire et présentation.' },
      { title: 'Visualisez avec Midjourney', desc: 'Midjourney crée des visuels de cocktails sublimes pour votre carte, vos réseaux et vos supports de communication.' },
      { title: 'Animez les réseaux avec Canva AI', desc: 'Canva AI génère des posts Instagram et Stories attractifs qui mettent en valeur vos créations et événements.' },
    ],
  },
  {
    slug: 'traiteur',
    name: 'Traiteur',
    sector: 'Restauration',
    icon: 'ChefHat',
    top5: ['chatgpt', 'canva-ai', 'notion-ai', 'mailchimp-ai', 'midjourney'],
    useCases: [
      'Créer des propositions et menus pour événements',
      'Rédiger les devis et contrats',
      'Gérer la logistique et les plannings',
      'Créer des supports commerciaux attractifs',
    ],
    tempsGagne: '3-6h / semaine',
    budget: '15-40 € / mois',
    steps: [
      { title: 'Créez vos propositions avec ChatGPT', desc: 'Entrez le type d\'événement, le nombre de convives et le budget pour obtenir une proposition de menu complète et personnalisée.' },
      { title: 'Créez vos supports avec Canva AI', desc: 'Canva AI crée des brochures, catalogues de prestations et menus visuellement appétissants pour vos prospects.' },
      { title: 'Gérez les événements avec Notion', desc: 'Centralisez le planning, les menus, les équipes et les contrats de chaque événement dans Notion.' },
    ],
  },
  {
    slug: 'patissier',
    name: 'Pâtissier',
    sector: 'Restauration',
    icon: 'ChefHat',
    top5: ['chatgpt', 'midjourney', 'canva-ai', 'adobe-firefly', 'ideogram'],
    useCases: [
      'Développer de nouvelles recettes et créations',
      'Créer des visuels attractifs pour la vitrine et les réseaux',
      'Concevoir les boîtes et emballages',
      'Raconter l\'histoire de ses créations',
    ],
    tempsGagne: '3-5h / semaine',
    budget: '15-40 € / mois',
    steps: [
      { title: 'Développez des recettes avec ChatGPT', desc: 'ChatGPT propose des associations de saveurs, variations de recettes classiques et innovations selon vos contraintes et la saison.' },
      { title: 'Inspirez-vous avec Midjourney', desc: 'Midjourney visualise des créations pâtissières que vous pouvez adapter. Parfait pour trouver des idées visuelles et de décoration.' },
      { title: 'Présentez vos créations avec Canva AI', desc: 'Canva AI crée des posts Instagram, étiquettes et packagings qui reflètent l\'artisanat et le soin de vos créations.' },
    ],
  },

  // ── Immobilier ───────────────────────────────────────────────────────────────
  {
    slug: 'agent-immobilier',
    name: 'Agent immobilier',
    sector: 'Immobilier',
    icon: 'Home',
    top5: ['chatgpt', 'canva-ai', 'notion-ai', 'mailchimp-ai', 'gamma-app'],
    useCases: [
      'Rédiger des annonces immobilières percutantes',
      'Préparer les dossiers de vente et compromis',
      'Créer des supports de présentation pour les biens',
      'Automatiser le suivi des prospects',
    ],
    tempsGagne: '4-7h / semaine',
    budget: '20-50 € / mois',
    steps: [
      { title: 'Rédigez vos annonces avec ChatGPT', desc: 'Donnez les caractéristiques du bien et obtenez une annonce captivante, optimisée pour les portails immobiliers, en 30 secondes.' },
      { title: 'Créez vos supports avec Canva AI', desc: 'Canva AI génère des dossiers de présentation, visuels de bien et brochures professionnelles pour vos mandats premium.' },
      { title: 'Suivez vos contacts avec Notion AI', desc: 'Créez une base CRM dans Notion avec suivi des projets acheteurs, matching automatique et rappels de relance.' },
    ],
  },
  {
    slug: 'promoteur',
    name: 'Promoteur immobilier',
    sector: 'Immobilier',
    icon: 'Home',
    top5: ['chatgpt', 'midjourney', 'canva-ai', 'gamma-app', 'notion-ai'],
    useCases: [
      'Générer des perspectives et rendus 3D de programmes',
      'Créer les supports commerciaux des programmes',
      'Rédiger les dossiers de financement et permis',
      'Analyser les marchés et l\'opportunité des projets',
    ],
    tempsGagne: '5-8h / semaine',
    budget: '30-80 € / mois',
    steps: [
      { title: 'Visualisez avec Midjourney', desc: 'Midjourney génère des perspectives architecturales et rendus extérieurs réalistes de vos programmes pour les supports de vente.' },
      { title: 'Créez les brochures avec Canva AI', desc: 'Canva AI crée des plaquettes commerciales haut de gamme pour vos programmes avec plans, vues et descriptions.' },
      { title: 'Analysez les marchés avec ChatGPT', desc: 'ChatGPT vous aide à structurer les études de marché, les études de faisabilité et les argumentaires pour les financeurs.' },
    ],
  },
  {
    slug: 'gestionnaire-de-biens',
    name: 'Gestionnaire de biens',
    sector: 'Immobilier',
    icon: 'Home',
    top5: ['chatgpt', 'notion-ai', 'monday-ai', 'claude-ai', 'grammarly-ai'],
    useCases: [
      'Rédiger les baux, états des lieux et quittances',
      'Gérer les communications avec les locataires',
      'Suivre les travaux et la maintenance',
      'Préparer les comptes-rendus de gérance',
    ],
    tempsGagne: '4-6h / semaine',
    budget: '0-30 € / mois',
    steps: [
      { title: 'Rédigez les documents avec ChatGPT', desc: 'ChatGPT génère baux, états des lieux, quittances et lettres de mise en demeure professionnels et conformes.' },
      { title: 'Organisez les biens avec Notion AI', desc: 'Créez une base de données de biens gérés avec état des lieux, contrats, locataires et suivi des paiements.' },
      { title: 'Gérez les travaux avec Monday AI', desc: 'Monday AI coordonne les prestataires, suit les devis et les interventions pour chaque bien géré.' },
    ],
  },
  {
    slug: 'architecte',
    name: 'Architecte',
    sector: 'Immobilier',
    icon: 'Home',
    top5: ['midjourney', 'adobe-firefly', 'canva-ai', 'chatgpt', 'figma-ai'],
    useCases: [
      'Générer des concepts architecturaux et moodboards',
      'Créer des supports de présentation clients',
      'Rédiger les notices architecturales et descriptifs',
      'Concevoir les supports de permis de construire',
    ],
    tempsGagne: '5-10h / semaine',
    budget: '30-80 € / mois',
    steps: [
      { title: 'Explorez les concepts avec Midjourney', desc: 'Midjourney génère des concepts architecturaux variés depuis vos briefs. Explorez styles, matériaux et ambiances pour présenter des options clients.' },
      { title: 'Créez les supports de présentation avec Canva AI', desc: 'Canva AI assemble des dossiers d\'avant-projet soignés avec plans, rendus, références et planning.' },
      { title: 'Rédigez les notices avec ChatGPT', desc: 'ChatGPT structure les notices architecturales, descriptifs de travaux et mémoires justificatifs pour vos dossiers permis.' },
    ],
  },

  // ── Médias ──────────────────────────────────────────────────────────────────
  {
    slug: 'journaliste',
    name: 'Journaliste',
    sector: 'Médias',
    icon: 'Camera',
    top5: ['chatgpt', 'perplexity', 'grammarly-ai', 'otter-ai', 'deepl'],
    useCases: [
      'Vérifier les faits et croiser les sources',
      'Transcrire les interviews automatiquement',
      'Résumer et analyser des documents longs',
      'Traduire des sources étrangères',
      'Structurer et rédiger les articles plus vite',
    ],
    tempsGagne: '5-8h / semaine',
    budget: '20-40 € / mois',
    steps: [
      { title: 'Transcrivez vos interviews avec Otter.ai', desc: 'Otter.ai transcrit vos enregistrements en quelques minutes et identifie les citations clés. Gain de temps massif en post-entretien.' },
      { title: 'Vérifiez avec Perplexity', desc: 'Perplexity vous donne des réponses sourcées et vérifiables pour le fact-checking. Croisez toujours avec vos propres vérifications.' },
      { title: 'Rédigez et corrigez avec ChatGPT + Grammarly', desc: 'ChatGPT structure vos articles depuis vos notes, Grammarly assure la qualité rédactionnelle avant publication.' },
    ],
  },
  {
    slug: 'photographe',
    name: 'Photographe',
    sector: 'Médias',
    icon: 'Camera',
    top5: ['midjourney', 'remove-bg', 'adobe-firefly', 'canva-ai', 'clipdrop'],
    useCases: [
      'Retoucher et améliorer les photos automatiquement',
      'Supprimer et remplacer les arrière-plans',
      'Créer des décors et contextes générés par IA',
      'Développer la présence en ligne et le portfolio',
    ],
    tempsGagne: '4-8h / semaine',
    budget: '20-60 € / mois',
    steps: [
      { title: 'Détourer avec Remove.bg', desc: 'Remove.bg supprime les arrière-plans de centaines de photos en quelques secondes. Idéal pour les photos produits et portraits.' },
      { title: 'Retouchez avec Adobe Firefly', desc: 'Firefly dans Photoshop permet le remplissage génératif, l\'extension d\'image et la suppression d\'objets de manière réaliste.' },
      { title: 'Créez les supports avec Canva AI', desc: 'Canva AI crée un portfolio en ligne, des tarifs illustrés et des posts réseaux qui mettent en valeur votre travail.' },
    ],
  },
  {
    slug: 'vidéaste',
    name: 'Vidéaste',
    sector: 'Médias',
    icon: 'Camera',
    top5: ['capcut-ai', 'runway-ml', 'descript', 'heygen', 'invideo-ai'],
    useCases: [
      'Monter des vidéos automatiquement avec sous-titres',
      'Générer des effets visuels et transitions IA',
      'Créer des vidéos avec avatars et voix IA',
      'Transformer les longues vidéos en courts formats',
    ],
    tempsGagne: '8-15h / semaine',
    budget: '30-80 € / mois',
    steps: [
      { title: 'Montez avec CapCut AI', desc: 'CapCut AI ajoute automatiquement sous-titres, effets et musique à vos vidéos. Le mode auto-cut génère des Reels depuis vos rushes.' },
      { title: 'Créez avec Runway ML', desc: 'Runway ML permet la génération vidéo, le rotoscoping, la suppression d\'arrière-plan et les effets visuels professionnels.' },
      { title: 'Éditez avec Descript', desc: 'Descript transcrit votre vidéo et vous permet de l\'éditer comme un document texte : supprimez les hésitations, coupez les silences en un clic.' },
    ],
  },
  {
    slug: 'podcaster',
    name: 'Podcaster',
    sector: 'Médias',
    icon: 'Camera',
    top5: ['descript', 'adobe-podcast', 'elevenlabs', 'krisp', 'otter-ai'],
    useCases: [
      'Améliorer la qualité audio et supprimer le bruit',
      'Transcrire et créer des show notes automatiquement',
      'Générer des extraits et clips promotionnels',
      'Créer des voix IA pour les introductions',
    ],
    tempsGagne: '4-8h / semaine',
    budget: '20-50 € / mois',
    steps: [
      { title: 'Améliorez l\'audio avec Adobe Podcast', desc: 'Adobe Podcast Enhance supprime le bruit de fond et améliore la qualité de votre voix gratuitement. Studio professionnel depuis votre domicile.' },
      { title: 'Éditez avec Descript', desc: 'Descript transcrit votre épisode et vous permet de supprimer les "euh", les silences et les erreurs en éditant simplement le texte.' },
      { title: 'Transcrivez avec Otter.ai', desc: 'Otter.ai génère automatiquement les show notes, résumés et timestamped chapters à publier avec chaque épisode.' },
    ],
  },
  {
    slug: 'influenceur',
    name: 'Créateur de contenu / Influenceur',
    sector: 'Médias',
    icon: 'Camera',
    top5: ['canva-ai', 'capcut-ai', 'chatgpt', 'predis-ai', 'midjourney'],
    useCases: [
      'Planifier et générer un mois de contenu en quelques heures',
      'Créer des thumbnails et visuels attrayants',
      'Monter des Reels et TikToks avec sous-titres automatiques',
      'Rédiger des légendes, hashtags et CTAs optimisés',
    ],
    tempsGagne: '10-20h / semaine',
    budget: '20-60 € / mois',
    steps: [
      { title: 'Planifiez avec Predis.ai', desc: 'Predis.ai génère un calendrier éditorial complet avec idées de contenus, captions et visuels adaptés à votre niche et audience.' },
      { title: 'Montez avec CapCut AI', desc: 'CapCut AI ajoute sous-titres dynamiques, effets et musique tendance à vos vidéos. Le mode auto-highlight crée des clips depuis vos longues vidéos.' },
      { title: 'Créez vos thumbnails avec Canva AI + Midjourney', desc: 'Midjourney pour les visuels originaux, Canva AI pour les titres et la mise en page. Des thumbnails qui font 10x plus de clics.' },
    ],
  },

  // ── RH ──────────────────────────────────────────────────────────────────────
  {
    slug: 'recruteur',
    name: 'Recruteur',
    sector: 'RH',
    icon: 'Users',
    top5: ['chatgpt', 'eightfold-ai', 'hirevue', 'notion-ai', 'grammarly-ai'],
    useCases: [
      'Rédiger des offres d\'emploi attractives et inclusives',
      'Shortlister les candidats et matcher les profils',
      'Préparer les grilles d\'entretien',
      'Automatiser les communications avec les candidats',
    ],
    tempsGagne: '5-8h / semaine',
    budget: '20-60 € / mois',
    steps: [
      { title: 'Rédigez vos offres avec ChatGPT', desc: 'ChatGPT génère des offres d\'emploi attractives, inclusives et optimisées pour les jobboards en précisant le poste, les critères et la culture entreprise.' },
      { title: 'Évaluez avec HireVue', desc: 'HireVue analyse les entretiens vidéo des candidats et identifie les soft skills, les compétences et le fit culturel automatiquement.' },
      { title: 'Gérez le pipeline avec Notion AI', desc: 'Créez un ATS simplifié dans Notion pour suivre tous les candidats, planifier les entretiens et centraliser les feedbacks.' },
    ],
  },
  {
    slug: 'drh',
    name: 'Directeur des Ressources Humaines',
    sector: 'RH',
    icon: 'Users',
    top5: ['chatgpt', 'lattice-ai', 'monday-ai', 'notion-ai', 'otter-ai'],
    useCases: [
      'Rédiger les politiques RH et règlements intérieurs',
      'Analyser les données RH et préparer les reportings',
      'Préparer les entretiens annuels et évaluations',
      'Gérer la communication interne',
    ],
    tempsGagne: '5-8h / semaine',
    budget: '30-80 € / mois',
    steps: [
      { title: 'Gérez la performance avec Lattice AI', desc: 'Lattice AI analyse les données de performance, identifie les risques de départ et suggère les actions de développement pour chaque collaborateur.' },
      { title: 'Rédigez les politiques avec ChatGPT', desc: 'ChatGPT génère des politiques RH, chartes, règlements intérieurs et communications RH professionnels et conformes.' },
      { title: 'Transcrivez les réunions avec Otter.ai', desc: 'Otter.ai capture les comités de direction, CODIR et réunions syndicales avec résumés et points d\'action automatiques.' },
    ],
  },
  {
    slug: 'gestionnaire-de-paie',
    name: 'Gestionnaire de paie',
    sector: 'RH',
    icon: 'Users',
    top5: ['chatgpt', 'deel-ai', 'notion-ai', 'claude-ai', 'grammarly-ai'],
    useCases: [
      'Effectuer une veille sociale et juridique',
      'Rédiger les communications paie aux salariés',
      'Préparer les déclarations et attestations',
      'Gérer les questions des collaborateurs',
    ],
    tempsGagne: '3-5h / semaine',
    budget: '0-30 € / mois',
    steps: [
      { title: 'Faites votre veille avec ChatGPT', desc: 'Demandez à ChatGPT les impacts des nouvelles lois sociales sur votre paie : prime, cotisation, URSSAF. Vérifiez toujours avec les textes officiels.' },
      { title: 'Gérez l\'international avec Deel AI', desc: 'Deel AI simplifie la paie internationale, la conformité réglementaire et les contrats pour les collaborateurs à l\'étranger.' },
      { title: 'Rédigez vos communications avec Claude', desc: 'Claude rédige des explications claires de bulletins de paie, des réponses aux questions et des notes d\'information aux salariés.' },
    ],
  },
  {
    slug: 'charge-de-formation',
    name: 'Chargé de formation',
    sector: 'RH',
    icon: 'Users',
    top5: ['chatgpt', 'synthesia', 'edapp', 'canva-ai', 'coursera-ai'],
    useCases: [
      'Créer des modules e-learning rapidement',
      'Concevoir des programmes de formation sur mesure',
      'Gérer les plans de formation et les budgets',
      'Mesurer l\'efficacité des formations',
    ],
    tempsGagne: '6-10h / semaine',
    budget: '30-100 € / mois',
    steps: [
      { title: 'Créez des vidéos avec Synthesia', desc: 'Synthesia génère des vidéos de formation avec présentateur IA depuis vos scripts. Pas besoin de tournage ni de studio.' },
      { title: 'Déployez avec EdApp', desc: 'EdApp crée des micro-formations mobiles engageantes avec quiz, gamification et suivi des progrès apprenants.' },
      { title: 'Structurez avec ChatGPT', desc: 'ChatGPT rédige les plans de formation, objectifs pédagogiques, évaluations et supports depuis vos briefs métier.' },
    ],
  },

  // ── Entrepreneurs ────────────────────────────────────────────────────────────
  {
    slug: 'startup-founder',
    name: 'Startup Founder',
    sector: 'Entrepreneurs',
    icon: 'Rocket',
    top5: ['chatgpt', 'notion-ai', 'gamma-app', 'zapier-ai', 'claude-ai'],
    useCases: [
      'Rédiger le business plan et le pitch deck',
      'Automatiser les processus et workflows internes',
      'Créer le site web et les contenus marketing',
      'Analyser le marché et les concurrents',
      'Gérer les communications investisseurs',
    ],
    tempsGagne: '10-20h / semaine',
    budget: '50-150 € / mois',
    steps: [
      { title: 'Structurez votre business plan avec Claude', desc: 'Claude analyse votre idée, identifie les risques, structure le business plan et génère les projections financières de base.' },
      { title: 'Créez votre pitch avec Gamma', desc: 'Gamma génère un pitch deck investisseur professionnel depuis votre brief. Personnalisez le contenu et envoyez le lien directement.' },
      { title: 'Automatisez avec Zapier AI', desc: 'Zapier AI connecte vos outils (CRM, emails, Slack, Notion) et automatise les workflows répétitifs sans coder.' },
    ],
  },
  {
    slug: 'freelance',
    name: 'Freelance',
    sector: 'Entrepreneurs',
    icon: 'Rocket',
    top5: ['chatgpt', 'notion-ai', 'grammarly-ai', 'canva-ai', 'zapier-ai'],
    useCases: [
      'Rédiger les propositions commerciales et contrats',
      'Gérer la facturation et le suivi administratif',
      'Créer du contenu pour développer sa visibilité',
      'Automatiser les relances et communications clients',
    ],
    tempsGagne: '5-10h / semaine',
    budget: '20-60 € / mois',
    steps: [
      { title: 'Gérez votre activité avec Notion AI', desc: 'Notion AI centralise vos clients, projets, factures et tâches. L\'IA génère automatiquement les comptes-rendus et les to-dos.' },
      { title: 'Rédigez vos propositions avec ChatGPT', desc: 'ChatGPT rédige des propositions commerciales personnalisées, des emails de prospection et des réponses aux appels d\'offres.' },
      { title: 'Automatisez avec Zapier AI', desc: 'Zapier connecte vos outils freelance : relances automatiques, synchronisation comptable et notifications projets.' },
    ],
  },
  {
    slug: 'auto-entrepreneur',
    name: 'Auto-entrepreneur',
    sector: 'Entrepreneurs',
    icon: 'Rocket',
    top5: ['chatgpt', 'canva-ai', 'notion-ai', 'mailchimp-ai', 'grammarly-ai'],
    useCases: [
      'Gérer les devis, factures et comptabilité simplifiée',
      'Créer une présence en ligne professionnelle',
      'Développer sa clientèle par email et réseaux sociaux',
      'Automatiser les tâches administratives répétitives',
    ],
    tempsGagne: '3-6h / semaine',
    budget: '0-30 € / mois',
    steps: [
      { title: 'Gérez l\'administratif avec ChatGPT', desc: 'ChatGPT génère vos devis, conditions générales, CGV et emails professionnels en quelques secondes.' },
      { title: 'Créez votre image avec Canva AI', desc: 'Canva AI crée votre logo, carte de visite, site web et posts réseaux sociaux cohérents et professionnels.' },
      { title: 'Fidélisez avec Mailchimp AI', desc: 'Mailchimp AI envoie des newsletters personnalisées à vos clients pour les fidéliser et générer du bouche-à-oreille.' },
    ],
  },
  {
    slug: 'consultant',
    name: 'Consultant',
    sector: 'Entrepreneurs',
    icon: 'Rocket',
    top5: ['chatgpt', 'claude-ai', 'gamma-app', 'notion-ai', 'perplexity'],
    useCases: [
      'Préparer les diagnostics et analyses clients',
      'Créer des livrables et présentations de conseil',
      'Effectuer une veille marché et sectorielle',
      'Rédiger des recommandations et feuilles de route',
    ],
    tempsGagne: '6-12h / semaine',
    budget: '30-80 € / mois',
    steps: [
      { title: 'Analysez avec Claude', desc: 'Claude traite des documents longs (rapports, données, bilans) et produit des diagnostics structurés avec les points clés et recommandations.' },
      { title: 'Créez vos livrables avec Gamma', desc: 'Gamma génère des présentations de conseil professionnelles depuis vos analyses. Client-ready en quelques minutes.' },
      { title: 'Faites votre veille avec Perplexity', desc: 'Perplexity synthétise les tendances sectorielles avec sources citées pour alimenter vos diagnostics et recommandations.' },
    ],
  },
]

export function getAllMetiers(): Metier[] {
  return METIERS
}

export function getMetierBySlug(slug: string): Metier | undefined {
  return METIERS.find((m) => m.slug === slug)
}

export function getMetiersBySector(sector: string): Metier[] {
  return METIERS.filter((m) => m.sector === sector)
}

export function getMetierTop5Tools(metier: Metier): CatalogTool[] {
  return metier.top5
    .map((slug) => getCatalogToolBySlug(slug))
    .filter((t): t is CatalogTool => t !== undefined)
}
