import { t } from './catalog-types'
import type { CatalogTool } from './catalog-types'

const tools: CatalogTool[] = [
  // ── Génération d'images IA ────────────────────────────────────────────────
  t('midjourney','Midjourney','Le générateur d\'images IA le plus créatif et photoréaliste, utilisé par des millions d\'artistes.','image','generation','paid','10$/mois (Basic)',['créer des illustrations IA','générer des images artistiques','créer un logo avec l\'IA','visualiser une idée créative'],4.9,'https://midjourney.com','🎨','#7c3aed',870000,'15M+',true),
  t('dalle-3','DALL-E 3','Générateur d\'images IA d\'OpenAI intégré à ChatGPT, capable de comprendre des descriptions détaillées.','image','generation','freemium','Inclus dans ChatGPT Plus / API pay-as-you-go',['générer des images depuis une description','créer des illustrations de blog','visualiser un concept'],4.8,'https://openai.com/dall-e-3','🖼️','#10a37f',650000,'50M+',true),
  t('stable-diffusion','Stable Diffusion','Le modèle de génération d\'images open source le plus populaire, personnalisable à l\'infini.','image','generation','free','Open source gratuit / Cloud',['générer des images en local','fine-tuner un modèle d\'image','créer du contenu NSFW sécurisé'],4.7,'https://stability.ai','🌊','#5c54c4',580000,'10M+',true),
  t('adobe-firefly','Adobe Firefly','Générateur d\'images IA d\'Adobe avec inpainting, text effects et génération commercialement sûre.','image','generation','freemium','25 générations gratuites / inclus Creative Cloud',['créer des images commercialement sûres','remplacer un fond photo','ajouter du texte stylisé à une image'],4.8,'https://firefly.adobe.com','🔥','#f97316',390000,'10M+',true),
  t('ideogram','Ideogram','Générateur d\'images IA spécialisé dans le rendu précis du texte dans les images.','image','generation','freemium','Gratuit / 7$/mois',['créer une affiche avec du texte','générer un logo avec texte','design graphique IA'],4.7,'https://ideogram.ai','💬','#ec4899',180000,'3M+',true),
  t('leonardo-ai','Leonardo AI','Plateforme de génération d\'images avec fine-tuning, canvas IA et workflows créatifs avancés.','image','generation','freemium','Gratuit 150 tokens/jr / 12$/mois',['créer des assets pour jeux vidéo','générer des personnages cohérents','fine-tuner un style visuel'],4.7,'https://leonardo.ai','🦁','#f59e0b',210000,'4M+',true),
  t('playground-ai','Playground AI','Éditeur d\'images IA en ligne avec des dizaines de modèles et un canvas puissant.','image','generation','freemium','Gratuit / 15$/mois',['éditer une image avec l\'IA','mélanger des styles artistiques','créer des images pour les réseaux sociaux'],4.6,'https://playground.com','🎡','#6366f1',120000,'3M+'),
  t('microsoft-designer','Microsoft Designer','Créateur de designs IA par Microsoft avec génération DALL-E et templates professionnels.','image','design','freemium','Gratuit / inclus Microsoft 365',['créer des posts réseaux sociaux','designer une invitation','créer un visuel marketing rapidement'],4.6,'https://designer.microsoft.com','🪟','#0078d4',95000,'5M+'),
  t('krea-ai','Krea AI','Génération d\'images en temps réel avec canvas interactif et upscaling ultra-HD.','image','generation','freemium','Gratuit / 35$/mois',['générer des images en temps réel','améliorer la qualité d\'une image','créer des variations d\'un concept'],4.7,'https://krea.ai','⚡','#7c3aed',87000,'1M+'),
  t('flux-ai','FLUX (Black Forest Labs)','Modèles de génération d\'images open source FLUX.1 ultra-réalistes surpassant Stable Diffusion.','image','generation','freemium','Gratuit / API pay-as-you-go',['générer des images photoréalistes','créer des portraits IA de haute qualité','générer des images commerciales'],4.8,'https://blackforestlabs.ai','🌌','#1a1a2e',160000,'2M+',true),
  t('nightcafe','NightCafe','Créateur d\'art IA avec de nombreux styles artistiques et une communauté active.','image','generation','freemium','5 créations gratuites/jour / 6$/mois',['créer de l\'art IA style peinture','participer à des défis créatifs','générer des NFT'],4.4,'https://nightcafe.studio','🌙','#1a1a2e',72000,'5M+'),
  t('dreamstudio','DreamStudio','Interface officielle de Stability AI pour Stable Diffusion avec contrôle avancé.','image','generation','paid','Pay as you go',['contrôler les paramètres Stable Diffusion','créer des images avec CFG scale','générer en batch'],4.5,'https://dreamstudio.ai','💤','#5c54c4',68000,'2M+'),
  t('getimg-ai','getimg.ai','Suite complète : génération, édition, inpainting et fine-tuning de modèles d\'images.','image','generation','freemium','Gratuit 100 images/mois / 12$/mois',['créer un modèle IA de mon visage','inpainting d\'image','agrandir une image (outpainting)'],4.6,'https://getimg.ai','🖼️','#8b5cf6',58000,'1M+'),
  t('stablecog','Stablecog','Générateur d\'images open source et multilingue basé sur Stable Diffusion.','image','generation','freemium','Gratuit / 10$/mois',['générer des images gratuitement','créer en français','hébergement open source'],4.4,'https://stablecog.com','⭐','#6d28d9',31000,'500K+'),

  // ── Édition photo IA ──────────────────────────────────────────────────────
  t('adobe-photoshop-ai','Adobe Photoshop (IA générative)','Photoshop avec Generative Fill, Generative Expand et Remove Object alimentés par Adobe Firefly.','image','edition','paid','54.99€/mois Creative Cloud',['supprimer un objet d\'une photo','agrandir une image IA','remplacer un fond automatiquement','retoucher un portrait'],4.9,'https://adobe.com/photoshop','🖌️','#001e36',290000,'30M+',true),
  t('remove-bg','Remove.bg','Supprimez instantanément l\'arrière-plan d\'une image en un clic grâce à l\'IA.','image','edition','freemium','Gratuit basse résolution / 9€/image HD',['supprimer le fond d\'une photo','détourer un sujet','créer des images produit sans fond'],4.8,'https://remove.bg','✂️','#00d4aa',280000,'30M+',true),
  t('cleanup-pictures','Cleanup.pictures','Supprimez des objets, du texte ou des personnes de vos photos par IA en quelques secondes.','image','edition','freemium','Gratuit / 5$/mois',['effacer un objet d\'une photo','supprimer une personne d\'une image','nettoyer une photo de vacances'],4.7,'https://cleanup.pictures','🧹','#10b981',190000,'10M+'),
  t('upscayl','Upscayl','Agrandisseur d\'image IA open source gratuit qui quadruple la résolution sans perte de qualité.','image','upscaling','free','Open source gratuit',['agrandir une image sans perte de qualité','améliorer une photo floue','restaurer une vieille photo'],4.8,'https://upscayl.org','🔍','#7c3aed',110000,'2M+',true),
  t('photoroom','PhotoRoom','Créez des photos produit professionnelles et supprimez les fonds en secondes.','image','edition','freemium','Gratuit / 9.99$/mois',['créer des photos produit e-commerce','changer le fond d\'une photo','créer des visuels marketing'],4.8,'https://photoroom.com','📸','#6366f1',210000,'100M+',true),
  t('pixelcut','Pixelcut','Éditeur photo IA pour créer des visuels produit et réseaux sociaux sur mobile.','image','edition','freemium','Gratuit / 7.99$/mois',['éditer des photos produit sur mobile','créer du contenu réseaux sociaux','supprimer le fond sur téléphone'],4.6,'https://pixelcut.ai','✂️','#f97316',89000,'30M+'),
  t('picwish','PicWish','Outils d\'édition photo IA : suppression de fond, retouche portrait et amélioration.','image','edition','freemium','Gratuit / 5.99$/mois',['améliorer un portrait automatiquement','supprimer le fond en lot','dénoiser une photo'],4.5,'https://picwish.com','🌸','#ec4899',67000,'5M+'),
  t('luminar-ai','Luminar Neo AI','Logiciel de retouche photo IA avec remplacement de ciel, suppression de câbles et masquage intelligent.','image','edition','paid','79$/an',['remplacer le ciel d\'une photo','retouche portrait automatique','améliorer un paysage'],4.6,'https://skylum.com/luminar','🌟','#f97316',48000,'8M+'),
  t('topaz-labs','Topaz Labs AI','Suite de plugins IA pour upscaling, dénoisage et amélioration de photos professionnelles.','image','edition','paid','199$/an',['agrandir des photos en 4K/8K','dénoiser une photo de nuit','améliorer la netteté d\'une image'],4.7,'https://topazlabs.com','💎','#1d4ed8',45000,'3M+'),
  t('fotor-ai','Fotor AI','Éditeur photo en ligne avec génération d\'images IA, effets et templates.','image','edition','freemium','Gratuit / 8.99$/mois',['éditer une photo en ligne','créer un portrait IA','ajouter des effets artistiques'],4.4,'https://fotor.com/ai-image-generator','🎨','#f97316',76000,'10M+'),
  t('clipdrop','ClipDrop','Suite d\'outils IA par Stability AI : suppression de fond, upscaling, reimagine et plus.','image','edition','freemium','Gratuit / 9$/mois',['supprimer le fond d\'un produit','améliorer une image avec l\'IA','créer des variations d\'une image'],4.6,'https://clipdrop.co','📎','#5c54c4',98000,'10M+'),

  // ── Design graphique IA ──────────────────────────────────────────────────
  t('canva-ai','Canva AI','Magic Studio de Canva avec génération d\'images, rédaction IA et design automatique.','image','design-graphique','freemium','Gratuit / Pro 14.99$/mois',['créer un post Instagram','designer un flyer','générer des visuels marketing','créer une présentation'],4.8,'https://canva.com','✨','#00c4cc',720000,'150M+',true),
  t('looka','Looka','Créez un logo professionnel et une identité de marque complète grâce à l\'IA.','image','logo','freemium','Logo basique gratuit / 65$ haute résolution',['créer un logo d\'entreprise','générer une identité visuelle','designer un favicon'],4.6,'https://looka.com','🏷️','#4f46e5',87000,'3M+'),
  t('brandmark','Brandmark','Générateur de logo IA unique avec personnalisation avancée et formats multiples.','image','logo','paid','25$ logo unique',['créer un logo original','générer une identité de marque','télécharger un logo SVG'],4.5,'https://brandmark.io','🎯','#1d4ed8',52000,'1M+'),
  t('khroma','Khroma','IA qui apprend vos préférences de couleurs pour générer des palettes infinies.','image','couleur','free','Gratuit',['créer une palette de couleurs','trouver les couleurs de ma marque','explorer des combinaisons de couleurs'],4.5,'https://khroma.co','🎨','#f43f5e',34000,'500K+'),
  t('autodraw','AutoDraw','Outil de dessin IA de Google qui reconnait vos croquis et propose des illustrations nettes.','image','dessin','free','Gratuit',['transformer un croquis en illustration','dessiner rapidement','créer des icônes simples'],4.3,'https://autodraw.com','✏️','#4285f4',29000,'5M+'),
  t('designs-ai','Designs.ai','Suite créative IA complète : logo, vidéo, mockup, voix et social media en un outil.','image','design-graphique','paid','29$/mois',['créer une identité de marque complète','générer du contenu marketing','créer un logo et des supports visuels'],4.4,'https://designs.ai','🎨','#ec4899',38000,'1M+'),
  t('adobe-express-ai','Adobe Express AI','Créez des designs professionnels rapidement avec l\'IA générative Adobe intégrée.','image','design-graphique','freemium','Gratuit / 9.99$/mois',['créer des posts réseaux sociaux','designer des flyers','créer des bannières publicitaires'],4.7,'https://adobe.com/express','🔶','#ff0000',85000,'50M+'),

  // ── Mode & Fashion IA ────────────────────────────────────────────────────
  t('the-new-black','The New Black','Créez des designs de mode et collections entières grâce à l\'IA générative.','image','mode','freemium','Gratuit / 24.99$/mois',['créer des designs de vêtements','générer une collection de mode','visualiser un concept vestimentaire'],4.5,'https://thenewblack.ai','👗','#1a1a2e',22000,'100K+'),
  t('stitch-fix-ai','Stitch Fix AI','Service de styling personnalisé piloté par l\'IA qui apprend vos goûts.','image','mode','paid','20$ styling fee/boîte',['obtenir des conseils de style personnalisés','découvrir des vêtements adaptés à mon style','recevoir une sélection de mode'],4.4,'https://stitchfix.com','🧵','#7c3aed',38000,'4M+'),
  t('vue-ai','Vue.ai','Plateforme IA pour les retailers mode : recommendation, recherche visuelle et expérience personnalisée.','image','mode','paid','Sur devis',['personnaliser l\'expérience d\'achat mode','recherche visuelle de vêtements','recommandations de tailles automatiques'],4.4,'https://vue.ai','👁️','#ec4899',12000,'100+'),
  t('heuritech','Heuritech','IA de prévision des tendances mode basée sur l\'analyse de millions de posts sociaux.','image','mode','paid','Sur devis',['prévoir les tendances mode','analyser les tendances réseaux sociaux','planifier les collections'],4.5,'https://heuritech.com','📊','#f97316',9000,'200+'),
  t('stylumia','Stylumia AI','Intelligence de marché mode IA pour prévoir la demande et optimiser les collections.','image','mode','paid','Sur devis',['analyser les tendances de consommation','prévoir les best-sellers mode','réduire les invendus'],4.4,'https://stylumia.com','👒','#db2777',7000,'500+'),
  t('cala-ai','Cala AI','Plateforme de design et production mode IA pour créer et sourcer des vêtements.','image','mode','paid','Sur devis',['designer des vêtements avec l\'IA','sourcer des fournisseurs de mode','gérer une collection'],4.3,'https://ca.la','🪡','#1a1a2e',8000,'10K+'),
  t('refabric','Re:fabric AI','Transformez vos designs de mode en renders photoréalistes grâce à l\'IA générative.','image','mode','freemium','Gratuit / 35$/mois',['générer des visuels de mode','créer des lookbooks IA','visualiser un design de vêtement'],4.5,'https://refabric.com','✂️','#db2777',11000,'20K+'),
  t('visualhound','VisualHound','Créez des moodboards et prototypes de vêtements réalistes avec l\'IA pour la mode.','image','mode','freemium','Gratuit / 19$/mois',['créer un moodboard de mode','prototyper un vêtement','visualiser une collection'],4.3,'https://visualhound.com','🖼️','#ec4899',6000,'10K+'),
  t('fashwell','Fashwell','Reconnaissance visuelle de mode IA pour le tagging automatique de produits et la recherche visuelle.','image','mode','paid','Sur devis',['tagger automatiquement des produits mode','recherche de vêtements par image','catalogage IA de mode'],4.4,'https://fashwell.com','🏷️','#7c3aed',5000,'100+'),
]

export default tools
