import { t } from './catalog-types'
import type { CatalogTool } from './catalog-types'

const tools: CatalogTool[] = [
  // ── Santé médicale ────────────────────────────────────────────────────────
  t('ada-health','Ada Health','Vérificateur de symptômes IA qui évalue vos symptômes et oriente vers le bon soin.','health','sante','free','Gratuit',['vérifier mes symptômes','comprendre une maladie','savoir si je dois consulter un médecin'],4.7,'https://ada.com','🩺','#ef4444',110000,'12M+',true),
  t('babylon-health','Babylon Health','Télémédecine et consultation IA qui démocratise l\'accès aux soins de santé.','health','sante','freemium','Gratuit / abonnement',['consulter un médecin en ligne','vérifier mes symptômes','suivi médical personnalisé'],4.4,'https://babylonhealth.com','💊','#10b981',52000,'1M+'),
  t('buoy-health','Buoy Health','Assistant de santé IA qui guide les patients vers le bon niveau de soin.','health','sante','free','Gratuit',['identifier la cause de mes symptômes','trouver le bon médecin','comprendre mes options de soin'],4.5,'https://buoyhealth.com','⛵','#3b82f6',38000,'5M+'),
  t('k-health','K Health','Médecin IA qui diagnostique et prescrit pour des conditions courantes.','health','sante','freemium','Gratuit symptômes / 35$/consultation',['consulter un médecin IA 24h/24','obtenir une prescription en ligne','urgences de santé non vitales'],4.5,'https://khealth.com','🏥','#1d4ed8',42000,'5M+'),
  t('nabla-ai','Nabla AI','Copilote IA pour médecins qui transcrit et résume automatiquement les consultations.','health','sante','freemium','Gratuit / 99$/mois praticiens',['transcrire une consultation médicale','générer des comptes-rendus automatiquement','réduire les tâches administratives médicales'],4.7,'https://nabla.com','🩻','#6366f1',28000,'45K+'),
  t('nuance-dax','Nuance DAX','Documentation médicale IA qui écoute les consultations et génère des notes cliniques.','health','sante','paid','Sur devis',['automatiser la documentation médicale','rédiger des notes cliniques','réduire le burnout médical'],4.8,'https://nuance.com/healthcare/physician-and-clinical-speech/dax','🎙️','#1a1a2e',18000,'100K+'),
  t('aidoc','Aidoc','IA de radiologie qui analyse les scanners et alertes les médecins sur les urgences.','health','imagerie','paid','Sur devis',['analyser des scanners automatiquement','détecter des urgences radiologiques','prioriser les cas critiques'],4.7,'https://aidoc.com','🔬','#3b82f6',14000,'1000+'),
  t('enlitic','Enlitic AI','IA d\'aide à la décision clinique pour la radiologie et la médecine basée sur les preuves.','health','imagerie','paid','Sur devis',['améliorer la précision diagnostique','standardiser les rapports radiologiques','détecter des pathologies rares'],4.5,'https://enlitic.com','💡','#7c3aed',8000,'100+'),
  t('tempus-ai','Tempus AI','Médecine de précision IA basée sur la génomique et les données cliniques pour l\'oncologie.','health','oncologie','paid','Sur devis',['analyser des données génomiques','personnaliser les traitements du cancer','recherche clinique IA'],4.6,'https://tempus.com','🧬','#1d4ed8',12000,'2000+'),
  t('google-med-palm','Med-PaLM 2 (Google)','LLM médical de Google capable de répondre aux questions médicales au niveau USMLE.','health','sante','paid','Accès limité via Google Cloud',['répondre à des questions médicales complexes','analyser des dossiers médicaux','aide à la décision clinique'],4.7,'https://cloud.google.com/blog/topics/healthcare-life-sciences','🔬','#4285f4',19000,'10K+'),
  t('butterfly-network','Butterfly Network AI','Échographe portable avec IA pour guider l\'acquisition et l\'interprétation des images.','health','imagerie','paid','2999$ appareil + abonnement',['échographier avec guidage IA','interpréter des échographies','démocratiser l\'imagerie médicale'],4.6,'https://butterflynetwork.com','🦋','#0ea5e9',11000,'500K+'),
  t('flatiron-health','Flatiron Health AI','Plateforme oncologie IA qui agrège et analyse les données de patients en vie réelle.','health','oncologie','paid','Sur devis',['analyser des données oncologiques','accélérer la recherche clinique','personnaliser les traitements'],4.5,'https://flatiron.com','🏥','#10b981',8000,'1000+'),
  t('microsoft-health-ai','Microsoft Nuance AI Health','Suite IA de Microsoft pour les hôpitaux : documentation, recherche et aide à la décision.','health','sante','paid','Sur devis',['automatiser la documentation hospitalière','rechercher de la littérature médicale','aide à la décision clinique IA'],4.6,'https://microsoft.com/health','🏥','#0078d4',14000,'1000+'),

  // ── Sport & Fitness ───────────────────────────────────────────────────────
  t('whoop-ai','WHOOP AI','Bracelet de fitness avec IA qui mesure la récupération, le strain et le sommeil.','health','sport','paid','30$/mois avec appareil',['optimiser ma récupération sportive','analyser mon sommeil','adapter mon entraînement à mon état'],4.7,'https://whoop.com','⌚','#ef4444',82000,'1M+',true),
  t('tempo-fit','Tempo AI','Miroir de fitness IA avec coach personnel et analyse des mouvements en temps réel.','health','sport','paid','195$/mois avec appareil',['s\'entraîner avec un coach IA','corriger mes mouvements en temps réel','suivre ma progression fitness'],4.5,'https://tempo.fit','🏋️','#1a1a2e',28000,'100K+'),
  t('vi-trainer','Vi Trainer','Entraîneur vocal IA qui adapte en temps réel l\'intensité de votre course.','health','sport','paid','95$ casque + app',['courir avec un coach IA vocal','adapter l\'intensité à mon rythme cardiaque','progresser en course à pied'],4.4,'https://vi.com','🎧','#f43f5e',18000,'500K+'),
  t('hudl-ai','Hudl AI','Analyse vidéo IA de performance sportive pour les équipes et athlètes.','health','sport','paid','Sur devis équipes',['analyser les performances de mon équipe','étudier les tactiques adverses','améliorer mes gestes techniques'],4.7,'https://hudl.com','🏆','#f97316',32000,'200K+'),
  t('catapult-ai','Catapult AI','Suivi de performance GPS et IA pour les athlètes professionnels et équipes.','health','sport','paid','Sur devis',['tracker la charge d\'entraînement','prévenir les blessures sportives','optimiser les performances en match'],4.6,'https://catapultsports.com','🛰️','#10b981',14000,'3000+'),
  t('secondspectrum','Second Spectrum AI','IA d\'analyse tactique NBA et soccer avec tracking optique des joueurs.','health','sport','paid','Sur devis ligues',['analyser les tactiques en basket','tracker les joueurs automatiquement','créer des highlights tactiques'],4.6,'https://secondspectrum.com','👁️','#1d4ed8',9000,'50+'),
  t('playertek','PlayerTek AI','Système GPS léger avec IA pour analyser les performances des footballeurs amateurs.','health','sport','paid','249€ appareil',['suivre mes performances au foot','analyser ma distance parcourue','optimiser mon positionnement'],4.4,'https://catapultsports.com/playertek','⚽','#f59e0b',12000,'50K+'),
  t('strava-ai','Strava AI','App de fitness sociale avec analyse IA des performances et coaching personnalisé.','health','sport','freemium','Gratuit / 8$/mois',['analyser mes sorties vélo/course','comparer avec des amis','suivre ma progression sportive'],4.6,'https://strava.com','🚴','#fc4c02',180000,'100M+',true),
  t('form-ai','FORM AI','Lunettes de natation avec affichage tête haute IA et analyse en temps réel.','health','sport','paid','299$ lunettes',['analyser mes nages en temps réel','suivre les longueurs automatiquement','améliorer ma technique de natation'],4.4,'https://formswim.com','🏊','#0ea5e9',8000,'100K+'),

  // ── Nutrition ────────────────────────────────────────────────────────────
  t('myfitnesspal-ai','MyFitnessPal AI','Application de suivi nutritionnel avec analyse IA des aliments et recommandations.','health','nutrition','freemium','Gratuit / 19.99$/mois',['compter mes calories','suivre mes macros','analyser ma nutrition'],4.6,'https://myfitnesspal.com','🥗','#00acee',210000,'200M+',true),
  t('lifesum-ai','Lifesum AI','Coach de nutrition IA avec plans personnalisés et suivi du régime alimentaire.','health','nutrition','freemium','Gratuit / 5.83$/mois',['créer un plan alimentaire personnalisé','perdre du poids avec l\'IA','adopter une alimentation saine'],4.5,'https://lifesum.com','🥑','#10b981',95000,'50M+'),
  t('january-ai','January AI','Analyse de glycémie IA avec prédictions personnalisées d\'impact alimentaire.','health','nutrition','freemium','Gratuit / 24.99$/mois',['prédire l\'impact des aliments sur ma glycémie','optimiser mon alimentation pour la performance','gérer mon diabète avec l\'IA'],4.5,'https://january.ai','📊','#3b82f6',18000,'100K+'),
  t('lark-health','Lark Health AI','Coaching santé IA 24h/24 pour les maladies chroniques (diabète, hypertension).','health','nutrition','paid','Via assurance santé',['gérer mon diabète avec l\'IA','coacher mon mode de vie','prévenir les maladies chroniques'],4.5,'https://lark.com','🐦','#10b981',15000,'1M+'),
  t('signos-ai','Signos AI','CGM + IA pour optimiser l\'alimentation et la santé métabolique en temps réel.','health','nutrition','paid','199$/mois',['optimiser ma santé métabolique','comprendre l\'impact des aliments','perdre du poids grâce aux données'],4.5,'https://signos.com','📈','#f97316',12000,'50K+'),

  // ── Psychologie & Bien-être ───────────────────────────────────────────────
  t('woebot','Woebot','Thérapeute IA basé sur les TCC qui vous aide à gérer l\'anxiété et la dépression.','health','psychologie','free','Gratuit',['gérer mon anxiété avec l\'IA','pratiquer la TCC','soutien émotionnel quotidien'],4.6,'https://woebothealth.com','🤗','#f59e0b',88000,'1M+',true),
  t('wysa','Wysa','Manchot IA de soutien émotionnel utilisant la TCC, la pleine conscience et la thérapie comportementale.','health','psychologie','freemium','Gratuit / 29.99$/mois',['parler à une IA de mes problèmes','gérer le stress et l\'anxiété','améliorer ma santé mentale'],4.5,'https://wysa.com','🐧','#4f46e5',62000,'5M+'),
  t('youper','Youper','Assistant de santé émotionnelle IA qui suit votre humeur et identifie les patterns.','health','psychologie','freemium','Gratuit / 10$/mois',['suivre mon humeur quotidiennement','identifier mes déclencheurs d\'anxiété','améliorer mon bien-être émotionnel'],4.4,'https://youper.ai','💚','#10b981',42000,'1M+'),
  t('replika','Replika','Compagnon IA créé pour l\'amitié, le soutien émotionnel et la discussion.','health','psychologie','freemium','Gratuit / 14.99$/mois',['trouver un compagnon IA','pratiquer des conversations sociales','soutien émotionnel par IA'],4.3,'https://replika.com','🤖','#7c3aed',120000,'10M+'),
  t('headspace-ai','Headspace AI','Application de méditation et mindfulness avec parcours IA personnalisé.','health','bien-etre','freemium','Gratuit / 12.99$/mois',['méditer avec un guide IA','réduire mon stress','améliorer mon sommeil'],4.7,'https://headspace.com','🧘','#f47d31',180000,'70M+',true),
  t('calm-ai','Calm AI','Application de bien-être avec méditations, sons et histoires du coucher personnalisées.','health','bien-etre','freemium','Gratuit / 14.99$/mois',['s\'endormir plus vite','réduire l\'anxiété','méditer au quotidien'],4.7,'https://calm.com','☁️','#4a90d9',160000,'150M+',true),
  t('cerebral-ai','Cerebral AI','Thérapie en ligne et psychiatrie avec IA pour diagnostiquer et traiter l\'anxiété.','health','psychologie','paid','85$/mois',['accéder à une thérapie en ligne','traiter l\'anxiété et la dépression','obtenir une prescription psychiatrique'],4.4,'https://cerebral.com','🧠','#6366f1',28000,'500K+'),
  t('spring-health-ai','Spring Health AI','Plateforme de santé mentale enterprise avec IA pour orienter vers les bons soins.','health','psychologie','paid','Via employeur',['accéder à des soins de santé mentale','trouver le bon thérapeute','mesurer le bien-être des équipes'],4.5,'https://springhealth.com','🌱','#10b981',18000,'10000+'),
  t('limbic-ai','Limbic AI','IA d\'évaluation de santé mentale qui oriente vers les bons soins cliniques.','health','psychologie','paid','Via cliniques',['évaluer ma santé mentale','préparer une thérapie','réduire le délai d\'accès aux soins'],4.4,'https://limbic.ai','🧠','#a855f7',9000,'100K+'),
  t('pyx-health','Pyx Health AI','Compagnon IA de santé mentale pour les personnes socialement isolées.','health','psychologie','paid','Via assurance',['réduire la solitude avec l\'IA','soutien quotidien par conversation','identifier des signaux de détresse'],4.3,'https://pyxhealth.com','💜','#7c3aed',6000,'100K+'),
]

export default tools
