import { t } from './catalog-types'
import type { CatalogTool } from './catalog-types'

const tools: CatalogTool[] = [
  // ── Marketing ─────────────────────────────────────────────────────────────
  t('hubspot-ai','HubSpot AI','CRM et plateforme marketing tout-en-un avec IA pour automatiser les ventes et le marketing.','business','marketing','freemium','Gratuit / 20$/mois',['automatiser le marketing','gérer un CRM IA','générer des leads qualifiés','créer des campagnes email'],4.7,'https://hubspot.com/artificial-intelligence','🔶','#ff7a59',390000,'5M+',true),
  t('salesforce-einstein','Salesforce Einstein','IA intégrée à Salesforce pour prédire les ventes, personnaliser et automatiser le CRM.','business','crm','paid','Sur devis',['prédire les ventes avec l\'IA','personnaliser les parcours clients','automatiser le suivi commercial'],4.6,'https://salesforce.com/products/einstein','☁️','#00a1e0',180000,'150K+',true),
  t('adobe-marketo','Adobe Marketo Engage AI','Plateforme d\'automatisation marketing B2B avec IA pour le lead scoring et la personnalisation.','business','marketing','paid','Sur devis',['scorer des leads automatiquement','personnaliser des campagnes B2B','nurturing de leads avec IA'],4.5,'https://business.adobe.com/products/marketo','⚡','#68217a',75000,'5000+'),
  t('klaviyo-mkt','Klaviyo','Plateforme d\'email et SMS marketing IA avec segmentation prédictive pour l\'e-commerce.','business','email-marketing','freemium','Gratuit / 45$/mois',['automatiser les emails e-commerce','segmenter mes clients par comportement','créer des flows d\'emails personnalisés'],4.7,'https://klaviyo.com','📧','#1a73e8',210000,'150K+',true),
  t('brevo-ai','Brevo AI','Anciennement Sendinblue : emailing, SMS et marketing automation IA abordable.','business','email-marketing','freemium','Gratuit / 25$/mois',['envoyer des newsletters','créer des campagnes SMS','automatiser mes emails marketing'],4.6,'https://brevo.com','📩','#0cbf9c',150000,'500K+'),
  t('mailchimp-ai','Mailchimp AI','Plateforme d\'emailing avec IA pour optimiser les envois et personnaliser les campagnes.','business','email-marketing','freemium','Gratuit 500 contacts / 20$/mois',['créer une newsletter','segmenter ma liste d\'emails','optimiser mes taux d\'ouverture'],4.6,'https://mailchimp.com','🐒','#ffe01b',310000,'13M+',true),
  t('activecampaign-ai','ActiveCampaign AI','Automatisation marketing avancée avec IA prédictive pour le scoring et la segmentation.','business','email-marketing','paid','39$/mois',['créer des automatisations email complexes','scorer mes contacts','personnaliser mes communications'],4.7,'https://activecampaign.com','⚡','#356ae6',120000,'185K+'),
  t('omnisend-ai','Omnisend AI','Marketing omnicanal IA pour l\'e-commerce : email, SMS, push et popups.','business','email-marketing','freemium','Gratuit / 16$/mois',['créer des campagnes omnicanales','automatiser les abandons de panier','segmenter par comportement d\'achat'],4.6,'https://omnisend.com','🌐','#6e4fff',68000,'100K+'),

  // ── Email IA ──────────────────────────────────────────────────────────────
  t('instantly-ai','Instantly.ai','Plateforme d\'envoi de cold emails IA à grande échelle avec rotation de domaines.','business','cold-email','freemium','Gratuit / 37$/mois',['envoyer des cold emails en masse','automatiser la prospection par email','personnaliser les emails à grande échelle'],4.6,'https://instantly.ai','⚡','#f97316',110000,'500K+',true),
  t('lemlist-ai','Lemlist AI','Outreach multicanal (email, LinkedIn, appel) avec personnalisation IA et images custom.','business','cold-email','paid','59$/mois',['personnaliser des cold emails avec photos','créer des séquences de prospection','automatiser LinkedIn et email'],4.7,'https://lemlist.com','🍋','#f59e0b',88000,'100K+'),
  t('reply-io','Reply.io','Automatisation de la prospection multicanal avec IA pour générer des emails personnalisés.','business','cold-email','freemium','Gratuit / 60$/mois',['automatiser la prospection commerciale','créer des séquences email personnalisées','gérer des campagnes multicanales'],4.5,'https://reply.io','💬','#3b82f6',62000,'200K+'),
  t('lavender-ai','Lavender AI','Coach d\'email IA qui analyse et améliore vos emails de vente en temps réel.','business','cold-email','freemium','Gratuit / 29$/mois',['améliorer mes emails de vente','augmenter mon taux de réponse','écrire des emails plus efficaces'],4.6,'https://lavender.ai','💜','#a855f7',48000,'100K+'),
  t('smartwriter-ai','Smartwriter.ai','Génération d\'emails de prospection ultra-personnalisés à partir du profil LinkedIn.','business','cold-email','paid','59$/mois',['personnaliser des cold emails depuis LinkedIn','générer des emails de prospection en masse','augmenter les taux de réponse'],4.4,'https://smartwriter.ai','🤖','#6366f1',35000,'50K+'),
  t('superhuman-ai','Superhuman AI','Client email le plus rapide au monde avec triage IA, résumés et rédaction automatique.','business','email-productivite','paid','30$/mois',['lire et répondre aux emails plus vite','trier automatiquement mes emails','résumer des fils de discussion'],4.8,'https://superhuman.com','⚡','#f43f5e',95000,'500K+',true),
  t('shortwave-ai','Shortwave AI','Client email IA avec résumés, recherche sémantique et rédaction pour Gmail.','business','email-productivite','freemium','Gratuit / 25$/mois',['résumer mes emails automatiquement','rechercher dans mes emails en langage naturel','répondre plus vite aux emails'],4.6,'https://shortwave.com','📧','#3b82f6',48000,'200K+'),
  t('mailerlite-ai','MailerLite AI','Emailing simple et abordable avec IA pour créer des newsletters et automatisations.','business','email-marketing','freemium','Gratuit 1000 contacts / 9$/mois',['créer une newsletter professionnelle','automatiser des emails de bienvenue','créer des formulaires de capture'],4.6,'https://mailerlite.com','💌','#10b981',82000,'2M+'),
  t('convertkit-ai','ConvertKit AI','Plateforme email pour créateurs avec IA pour les newsletters et monétisation.','business','email-marketing','freemium','Gratuit 1000 abonnés / 15$/mois',['créer une newsletter de créateur','monétiser ma liste d\'abonnés','automatiser des séquences d\'onboarding'],4.6,'https://convertkit.com','📨','#f97316',75000,'600K+'),

  // ── Réseaux sociaux ───────────────────────────────────────────────────────
  t('hootsuite-ai','Hootsuite AI','Planifiez, publiez et analysez vos posts sur tous les réseaux sociaux avec l\'IA.','business','social-media','freemium','Gratuit / 99$/mois',['planifier mes publications réseaux sociaux','analyser mes performances sociales','générer des captions IA'],4.5,'https://hootsuite.com','🦉','#000000',180000,'5M+'),
  t('buffer-ai','Buffer AI','Planification de contenu réseaux sociaux avec assistant IA pour générer des idées.','business','social-media','freemium','Gratuit / 6$/mois',['planifier mes posts Facebook/Instagram','trouver les meilleurs horaires de publication','générer des idées de contenu'],4.6,'https://buffer.com','📅','#2c4bff',150000,'10M+'),
  t('later-ai','Later AI','Planificateur visuel de contenu pour Instagram, TikTok et Pinterest avec IA.','business','social-media','freemium','Gratuit / 25$/mois',['planifier du contenu Instagram','créer un feed cohérent','trouver les meilleurs hashtags'],4.6,'https://later.com','🗓️','#f97316',130000,'7M+'),
  t('taplio','Taplio','L\'outil de croissance LinkedIn N°1 avec IA pour créer des posts viraux et développer son réseau.','business','social-media','paid','65$/mois',['créer des posts LinkedIn viraux','développer mon personal branding','générer des idées de contenu LinkedIn'],4.7,'https://taplio.com','💼','#0a66c2',95000,'100K+',true),
  t('tweethunter','Tweet Hunter','Créez et planifiez des tweets et threads viraux avec IA et analysez vos performances.','business','social-media','paid','49$/mois',['créer des threads Twitter viraux','trouver des idées de tweets','développer ma communauté Twitter'],4.6,'https://tweethunter.io','🐦','#1da1f2',82000,'150K+'),
  t('flick-ai','Flick AI','Planificateur de contenu Instagram et TikTok avec générateur de captions et hashtags IA.','business','social-media','paid','14$/mois',['trouver des hashtags performants','créer des captions Instagram','planifier mon contenu social'],4.5,'https://flick.tech','✨','#ec4899',55000,'500K+'),
  t('predis-ai','Predis.ai','Créez du contenu réseaux sociaux complet (visuel + texte) avec l\'IA en quelques secondes.','business','social-media','freemium','Gratuit / 29$/mois',['créer des posts avec visuel et texte','générer une semaine de contenu','créer des Reels scriptés'],4.5,'https://predis.ai','🚀','#7c3aed',68000,'1M+'),
  t('ocoya','Ocoya','Suite de marketing social IA complète avec génération de contenu, planification et analytics.','business','social-media','paid','19$/mois',['gérer tous mes réseaux sociaux','créer du contenu et le planifier','analyser les performances'],4.4,'https://ocoya.com','🌿','#10b981',45000,'100K+'),
  t('postwise-ai','Postwise AI','Generateur de threads Twitter et posts LinkedIn viraux par l\'IA.','business','social-media','paid','37$/mois',['écrire des threads Twitter viraux','créer du contenu LinkedIn engageant','trouver des angles de contenu originaux'],4.5,'https://postwise.ai','📱','#7c3aed',38000,'50K+'),
  t('socialbee-ai','SocialBee AI','Planificateur de contenu multicanal avec IA pour les solopreneurs et agences.','business','social-media','paid','29$/mois',['recycler du contenu efficacement','planifier sur tous les réseaux','créer des catégories de contenu'],4.5,'https://socialbee.com','🐝','#f59e0b',42000,'200K+'),
  t('metricool-ai','Metricool AI','Analytics et planification réseaux sociaux avec insights IA pour optimiser votre stratégie.','business','social-media','freemium','Gratuit / 22$/mois',['analyser mes stats Instagram','planifier et publier du contenu','créer des rapports de performance'],4.6,'https://metricool.com','📊','#3b82f6',62000,'1M+'),
  t('vista-social','Vista Social AI','Outil de gestion de réseaux sociaux tout-en-un avec IA pour les agences.','business','social-media','freemium','Gratuit / 39$/mois',['gérer plusieurs clients sur les réseaux','créer des rapports client','collaborer sur le contenu social'],4.5,'https://vistasocial.com','👁️','#6366f1',28000,'100K+'),

  // ── Publicité IA ──────────────────────────────────────────────────────────
  t('adcreative-ai','AdCreative.ai','Générez des visuels publicitaires haute performance grâce à l\'IA avec un taux de conversion optimisé.','business','publicite','freemium','Gratuit / 21$/mois',['créer des publicités Facebook et Google','générer des bannières publicitaires','optimiser mes créatifs pub'],4.6,'https://adcreative.ai','🎯','#f97316',130000,'1M+',true),
  t('smartly-io','Smartly.io','Automatisation et optimisation des publicités social media IA pour les grandes entreprises.','business','publicite','paid','Sur devis',['automatiser les campagnes Meta','optimiser les budgets publicitaires','personnaliser les créatifs à grande échelle'],4.5,'https://smartly.io','🤖','#6366f1',28000,'1000+'),
  t('albert-ai','Albert AI','IA autonome qui gère et optimise vos campagnes publicitaires digitales de A à Z.','business','publicite','paid','Sur devis',['automatiser la gestion des ads','optimiser le ROAS en temps réel','lancer des campagnes multicanales'],4.4,'https://albert.ai','🤖','#1d4ed8',15000,'500+'),
  t('pencil-ai','Pencil AI','Générez des publicités vidéo et statiques IA et prédisez leurs performances.','business','publicite','freemium','Gratuit / 119$/mois',['créer des ads vidéo IA','prédire les performances publicitaires','tester des créatifs automatiquement'],4.4,'https://pencil.li','✏️','#ec4899',22000,'50K+'),
  t('madgicx','Madgicx AI','Plateforme IA pour optimiser les campagnes Meta Ads avec insights et automatisation.','business','publicite','paid','49$/mois',['optimiser mes Facebook Ads','analyser les audiences Meta','automatiser les règles de campagne'],4.5,'https://madgicx.com','🪄','#a855f7',38000,'100K+'),
  t('motionapp-ai','Motion (Ads)','Analysez les performances de vos créatifs publicitaires et identifiez ce qui convertit.','business','publicite','paid','109$/mois',['analyser les meilleurs créatifs','identifier les patterns de performance','brieferles créatifs gagnants'],4.5,'https://usemotion.com','📊','#3b82f6',18000,'20K+'),
  t('creatopy','Creatopy AI','Studio de création publicitaire IA avec génération de bannières et animation automatique.','business','publicite','freemium','Gratuit / 45$/mois',['créer des bannières en HTML5','générer des publicités display','animer des créatifs automatiquement'],4.4,'https://creatopy.com','🎨','#f43f5e',25000,'100K+'),

  // ── Service Client ─────────────────────────────────────────────────────────
  t('zendesk-ai','Zendesk AI','Plateforme de service client avec IA pour la réponse automatique et l\'analyse des tickets.','business','service-client','freemium','Gratuit / 55$/mois',['automatiser les réponses au support','analyser le sentiment client','réduire le temps de traitement des tickets'],4.7,'https://zendesk.com/platform/ai','🎫','#03363d',280000,'100K+',true),
  t('intercom-ai','Intercom AI','Plateforme de messagerie client avec Fin, l\'agent IA qui résout 50% des questions.','business','service-client','paid','74$/mois',['créer un chatbot de support IA','automatiser les FAQ','améliorer le support avec l\'IA'],4.7,'https://intercom.com/ai-chatbot','💬','#6366f1',210000,'25K+',true),
  t('freshdesk-ai','Freshdesk AI','Helpdesk avec Freddy AI pour automatiser les tickets et améliorer la satisfaction client.','business','service-client','freemium','Gratuit / 29$/mois',['automatiser le support client','classifier des tickets automatiquement','suggérer des réponses aux agents'],4.5,'https://freshdesk.com','🌿','#25c16f',150000,'60K+'),
  t('tidio-ai','Tidio AI (Lyro)','Chatbot IA abordable pour le e-commerce qui répond en 6 secondes aux questions clients.','business','service-client','freemium','Gratuit / 29$/mois',['créer un chatbot e-commerce','répondre automatiquement aux clients','automatiser le support Shopify'],4.6,'https://tidio.com','🤖','#3b82f6',120000,'500K+',true),
  t('drift-ai','Drift AI','Plateforme de conversational marketing avec chatbots IA pour générer des leads B2B.','business','service-client','paid','2500$/mois',['qualifier des leads par chatbot','automatiser les démonstrations','accélérer le pipeline commercial'],4.5,'https://drift.com','💨','#10b981',78000,'50K+'),
]

export default tools
