import { t } from './catalog-types'
import type { CatalogTool } from './catalog-types'

const tools: CatalogTool[] = [
  // ── Finance & Investissement ──────────────────────────────────────────────
  t('alphasense','AlphaSense','Moteur de recherche IA pour les marchés financiers analysant les rapports, calls et news.','finance','investissement','paid','Sur devis',['analyser des rapports financiers','rechercher des informations de marché','surveiller les concurrents financièrement'],4.7,'https://alpha-sense.com','📈','#1d4ed8',28000,'4000+'),
  t('bloomberg-gpt','BloombergGPT','LLM financier entraîné par Bloomberg sur 700 milliards de tokens de données financières.','finance','investissement','paid','Bloomberg Terminal (~24K$/an)',['analyser des données Bloomberg','rechercher des informations financières','prédire des tendances de marché'],4.7,'https://bloomberg.com','💹','#f97316',22000,'300K+'),
  t('palantir-ai','Palantir AI Platform','Plateforme d\'analyse de données et IA pour les grandes institutions financières et gouvernementales.','finance','analytics','paid','Sur devis',['analyser des données massives','détecter des fraudes financières','prédire des risques d\'investissement'],4.5,'https://palantir.com/platforms/aip','🔮','#1a1a2e',19000,'3000+'),
  t('kensho-ai','Kensho (S&P Global)','IA analytique de S&P Global pour la recherche financière et l\'intelligence économique.','finance','recherche','paid','Sur devis',['analyser des événements de marché','rechercher des données macroéconomiques','créer des rapports financiers automatiques'],4.6,'https://kensho.com','📊','#3b82f6',12000,'1000+'),
  t('sentieo','Sentieo','Recherche d\'investissement IA avec analyse de sentiments sur les earnings calls et documents.','finance','investissement','paid','Sur devis',['analyser le sentiment des earnings calls','rechercher des informations d\'investissement','suivre les concurrents financièrement'],4.5,'https://sentieo.com','🔍','#6366f1',9000,'2000+'),
  t('kavout','Kavout','Plateforme de quant investing IA avec signal K pour la sélection d\'actions.','finance','trading','paid','99$/mois',['sélectionner des actions avec l\'IA','créer des stratégies de trading quantitatives','analyser les performances d\'un portefeuille'],4.4,'https://kavout.com','📊','#10b981',7000,'10K+'),
  t('refinitiv-ai','Refinitiv (LSEG) AI','Données et analytics financiers IA de LSEG pour les professionnels de la finance.','finance','analytics','paid','Sur devis',['accéder aux données de marché','analyser des ESG','surveiller des risques financiers'],4.5,'https://lseg.com/refinitiv','🌐','#d97706',11000,'400K+'),
  t('plaid-ai','Plaid AI','Infrastructure IA de connexion bancaire pour analyser et catégoriser les transactions.','finance','fintech','paid','Pay as you go',['analyser les transactions bancaires','catégoriser les dépenses automatiquement','connecter des comptes bancaires'],4.6,'https://plaid.com','🔗','#000000',18000,'8000+'),
  t('stripe-radar','Stripe Radar AI','Protection contre la fraude IA de Stripe avec machine learning en temps réel.','finance','fraude','freemium','Inclus Stripe / 0.05$/transaction',['détecter les fraudes en temps réel','réduire les chargebacks','protéger mon e-commerce des fraudes'],4.8,'https://stripe.com/radar','🛡️','#6772e5',45000,'1M+',true),
  t('upstart-ai','Upstart AI','Plateforme de crédit IA qui approuve des prêts en se basant sur 1600+ variables.','finance','credit','paid','Commission prêteur',['obtenir un crédit avec un faible score','analyser la solvabilité','améliorer l\'accès au crédit'],4.4,'https://upstart.com','⬆️','#3b82f6',14000,'100K+'),
  t('zest-ai','Zest AI','Underwriting de crédit IA pour les institutions financières avec modèles équitables.','finance','credit','paid','Sur devis',['prédire le risque de défaut','automatiser l\'approbation de crédit','réduire les biais dans le scoring'],4.4,'https://zest.ai','🌱','#10b981',8000,'200+'),
  t('featurespace','Featurespace AI','Détection de fraude et gestion des risques IA pour les banques et assureurs.','finance','fraude','paid','Sur devis',['détecter des transactions frauduleuses','analyser le comportement client','prévenir la fraude en temps réel'],4.5,'https://featurespace.com','🔐','#7c3aed',6000,'500+'),
  t('personetics','Personetics AI','IA d\'engagement client bancaire qui personnalise l\'expérience et les conseils financiers.','finance','banque','paid','Sur devis',['personnaliser les conseils bancaires','analyser le comportement financier','augmenter l\'engagement client'],4.4,'https://personetics.com','👥','#1d4ed8',7000,'200+'),
  t('kasisto','Kasisto AI (KAI)','Assistant conversationnel IA pour les banques avec compréhension du domaine financier.','finance','banque','paid','Sur devis',['créer un assistant bancaire IA','répondre aux questions financières','automatiser le service bancaire'],4.4,'https://kasisto.com','💬','#3b82f6',5000,'100+'),
  t('brighterion','Brighterion (Mastercard)','IA temps réel de Mastercard pour la détection de fraudes et la gestion des risques.','finance','fraude','paid','Sur devis',['détecter les fraudes à la carte','protéger les paiements en temps réel','réduire les faux positifs'],4.5,'https://mastercard.com/brighterion','💳','#eb001b',9000,'1000+'),

  // ── Comptabilité ──────────────────────────────────────────────────────────
  t('quickbooks-ai','QuickBooks AI','Logiciel de comptabilité avec IA pour catégoriser les dépenses, prédire les flux.','finance','comptabilite','freemium','Essai gratuit / 30$/mois',['automatiser ma comptabilité','catégoriser mes dépenses','préparer ma déclaration fiscale','gérer mes factures'],4.6,'https://quickbooks.intuit.com','📚','#2ca01c',180000,'7M+',true),
  t('xero-ai','Xero AI','Logiciel de comptabilité cloud avec réconciliation automatique et insights IA.','finance','comptabilite','paid','14.5€/mois',['réconcilier les transactions automatiquement','gérer la trésorerie','partager la comptabilité avec mon expert'],4.6,'https://xero.com','💙','#13b5ea',140000,'3.7M+',true),
  t('sage-ai','Sage AI','Suite comptable et ERP avec Sage Copilot pour automatiser et analyser les finances.','finance','comptabilite','paid','Sur devis',['automatiser la saisie comptable','prédire la trésorerie','générer des rapports financiers'],4.5,'https://sage.com','🟢','#00dc84',82000,'3M+'),
  t('freshbooks-ai','FreshBooks AI','Comptabilité et facturation IA pour les freelances et petites entreprises.','finance','comptabilite','paid','19$/mois',['créer et envoyer des factures','suivre le temps travaillé','gérer les dépenses d\'entreprise'],4.6,'https://freshbooks.com','🌿','#0075dd',95000,'30M+'),
  t('botkeeper','Botkeeper','Comptabilité automatisée IA pour les cabinets comptables et leurs clients.','finance','comptabilite','paid','Sur devis',['automatiser la comptabilité d\'un cabinet','rapprocher des transactions en masse','réduire les tâches manuelles comptables'],4.4,'https://botkeeper.com','🤖','#6366f1',11000,'1000+'),
  t('vic-ai','Vic.ai','Automatisation IA de la comptabilité fournisseurs et des processus AP.','finance','comptabilite','paid','Sur devis',['automatiser les factures fournisseurs','réduire les erreurs de saisie','accélérer les paiements fournisseurs'],4.5,'https://vic.ai','⚡','#f97316',8000,'500+'),
  t('docyt','Docyt','Automatisation comptable IA avec lecture de documents et catégorisation instantanée.','finance','comptabilite','paid','299$/mois',['numériser et catégoriser les reçus','automatiser la saisie comptable','fermer les livres plus rapidement'],4.4,'https://docyt.com','📄','#10b981',6000,'5000+'),
  t('bench-ai','Bench AI','Service de comptabilité IA + humain pour les petites entreprises américaines.','finance','comptabilite','paid','249$/mois',['externaliser ma comptabilité','avoir des états financiers mensuels','préparer mes impôts'],4.5,'https://bench.co','🏦','#3b82f6',22000,'35K+'),
  t('taxjar-ai','TaxJar AI','Automatisation de la taxe de vente (US) avec calcul et dépôt IA pour les e-commerçants.','finance','fiscalite','paid','19$/mois',['calculer la taxe de vente automatiquement','déposer les taxes automatiquement','gérer la conformité fiscale'],4.6,'https://taxjar.com','🧾','#ef4444',28000,'30K+'),
  t('avalara-ai','Avalara AI','Conformité fiscale mondiale IA pour les transactions e-commerce et B2B.','finance','fiscalite','paid','Sur devis',['automatiser la TVA internationale','gérer la conformité fiscale mondiale','calculer les taxes cross-border'],4.5,'https://avalara.com','🌍','#f97316',19000,'30K+'),

  // ── Assurance ─────────────────────────────────────────────────────────────
  t('lemonade-ai','Lemonade AI','Assurance habitation et vie IA avec remboursements instantanés par chatbot.','finance','assurance','paid','5$/mois',['souscrire une assurance habitation','déclarer un sinistre rapidement','obtenir un remboursement en secondes'],4.5,'https://lemonade.com','🍋','#ef4444',68000,'1.5M+',true),
  t('zelros','Zelros AI','IA de personnalisation des offres d\'assurance et de recommandation de produits.','finance','assurance','paid','Sur devis',['personnaliser les offres d\'assurance','recommander des produits adaptés','augmenter la conversion d\'assurance'],4.4,'https://zelros.com','🛡️','#3b82f6',7000,'100+'),
  t('shift-technology','Shift Technology','Détection de fraude à l\'assurance et automatisation des sinistres par IA.','finance','assurance','paid','Sur devis',['détecter les fraudes à l\'assurance','automatiser le traitement des sinistres','accélérer les décisions d\'indemnisation'],4.6,'https://shift-technology.com','🔍','#1d4ed8',9000,'100+'),
  t('cytora','Cytora AI','Traitement intelligent des demandes d\'assurance commerciale par IA.','finance','assurance','paid','Sur devis',['automatiser la souscription','analyser les risques d\'assurance','accélérer le traitement des dossiers'],4.4,'https://cytora.com','⚡','#7c3aed',6000,'50+'),
  t('tractable-ai','Tractable AI','IA de vision pour évaluer les dommages automobiles et immobiliers instantanément.','finance','assurance','paid','Sur devis',['évaluer des dommages automobile par photo','accélérer les expertises sinistres','réduire le coût des sinistres'],4.5,'https://tractable.ai','🚗','#f59e0b',8000,'100+'),

  // ── Juridique ─────────────────────────────────────────────────────────────
  t('harvey-ai','Harvey AI','Assistant IA pour avocats formé sur le droit : analyse de contrats, recherche et rédaction.','finance','juridique','paid','Sur devis',['analyser un contrat juridique','rechercher de la jurisprudence','rédiger des actes juridiques'],4.8,'https://harvey.ai','⚖️','#1a1a2e',42000,'100+',true),
  t('donotpay','DoNotPay','IA juridique grand public qui vous aide à combattre des amendes, annuler des abonnements, etc.','finance','juridique','paid','36$/an',['contester une amende','annuler un abonnement','rédiger une lettre juridique simple'],4.3,'https://donotpay.com','🚫','#ef4444',58000,'2M+'),
  t('casetext-ai','Casetext AI (CoCounsel)','Recherche juridique IA et assistant pour les professionnels du droit.','finance','juridique','paid','100$/mois',['rechercher de la jurisprudence','analyser des documents juridiques','préparer un dossier juridique'],4.6,'https://casetext.com','📋','#3b82f6',18000,'10K+'),
  t('lawgeex','LawGeex AI','Révision et analyse automatique de contrats IA avec identification des risques.','finance','juridique','paid','Sur devis',['réviser des contrats automatiquement','identifier les clauses risquées','approuver des contrats plus vite'],4.5,'https://lawgeex.com','📜','#7c3aed',11000,'500+'),
  t('kira-systems','Kira Systems','Extraction d\'informations et analyse de contrats IA pour les cabinets d\'avocats.','finance','juridique','paid','Sur devis',['extraire des données de contrats','analyser des dossiers de due diligence','accélérer la révision documentaire'],4.5,'https://kirasystems.com','🔍','#1d4ed8',8000,'2000+'),
  t('luminance','Luminance AI','IA juridique de pointe pour la due diligence, les contrats et la conformité.','finance','juridique','paid','Sur devis',['analyser des documents de fusion-acquisition','réviser des contrats en masse','due diligence automatisée'],4.6,'https://luminance.com','💡','#f59e0b',9000,'600+'),
  t('spellbook-ai','Spellbook AI','Assistant de rédaction juridique IA directement dans Word pour les contrats.','finance','juridique','freemium','Gratuit trial / 79$/mois',['rédiger des clauses contractuelles','suggérer des termes manquants','négocier des contrats avec l\'IA'],4.5,'https://spellbook.legal','📝','#6366f1',12000,'5000+'),
  t('ironclad-ai','Ironclad AI','Gestion du cycle de vie des contrats avec IA pour les équipes juridiques.','finance','juridique','paid','Sur devis',['gérer tous mes contrats','automatiser les workflows de signature','extraire des données de contrats'],4.5,'https://ironcladapp.com','⛓️','#f97316',14000,'2000+'),
  t('evisort','Evisort AI','Intelligence contractuelle IA pour l\'extraction de données et la gestion des contrats.','finance','juridique','paid','Sur devis',['chercher dans mes contrats','extraire des dates et termes clés','gérer les renouvellements de contrats'],4.4,'https://evisort.com','📋','#3b82f6',8000,'1000+'),
  t('patlytics','Patlytics AI','Analyse de brevets et intelligence de propriété intellectuelle par IA.','finance','juridique','paid','Sur devis',['analyser des brevets','rechercher de l\'antériorité','évaluer des portefeuilles de brevets'],4.4,'https://patlytics.com','💡','#7c3aed',5000,'500+'),
  t('leya-ai','Leya AI','Assistant IA pour avocats européens avec conformité RGPD et langues locales.','finance','juridique','paid','Sur devis',['assistant juridique RGPD-compliant','recherche juridique en français','analyser du droit européen'],4.5,'https://leya.law','⚖️','#1d4ed8',6000,'100+'),
]

export default tools
