import { t } from './catalog-types'
import type { CatalogTool } from './catalog-types'

const tools: CatalogTool[] = [
  // ── RH & Recrutement ─────────────────────────────────────────────────────
  t('workday-ai','Workday AI','Suite RH complète avec IA pour le recrutement, la paie, les compétences et les performances.','hr','rh','paid','Sur devis',['gérer les RH avec l\'IA','automatiser la paie','évaluer les performances'],4.6,'https://workday.com/ai','👔','#f97316',78000,'60M+',true),
  t('greenhouse-ai','Greenhouse AI','ATS de référence avec IA pour structurer le recrutement et réduire les biais.','hr','recrutement','paid','Sur devis',['structurer le processus de recrutement','réduire les biais de sélection','analyser les pipelines de talents'],4.6,'https://greenhouse.com','🌿','#10b981',52000,'7500+'),
  t('lever-ai','Lever AI','CRM et ATS de recrutement avec automatisation IA et analyse des pipelines.','hr','recrutement','paid','Sur devis',['gérer un pipeline de candidats','automatiser les relances de recrutement','collaborer sur les décisions d\'embauche'],4.5,'https://lever.co','⚙️','#6366f1',38000,'5000+'),
  t('hireez-ai','hireEZ AI','Sourcing de candidats IA qui trouve les profils passifs sur 45+ plateformes.','hr','sourcing','paid','Sur devis',['trouver des candidats passifs','enrichir les profils de candidats','automatiser la prospection de talents'],4.5,'https://hireez.com','🔍','#3b82f6',28000,'3000+'),
  t('fetcher-ai','Fetcher AI','Automatisation du sourcing de candidats et personnalisation des messages d\'outreach.','hr','sourcing','paid','Sur devis',['automatiser le sourcing de talents','personnaliser les messages de recrutement','analyser les campagnes de sourcing'],4.4,'https://fetcher.ai','🎣','#7c3aed',18000,'500+'),
  t('manatal','Manatal AI','ATS IA abordable avec enrichissement des profils LinkedIn et scoring automatique.','hr','recrutement','paid','19$/mois',['gérer un ATS simple et abordable','scorer des CV automatiquement','intégrer LinkedIn au recrutement'],4.7,'https://manatal.com','🏆','#f97316',42000,'10K+'),
  t('vervoe','Vervoe AI','Évaluation des compétences et simulations d\'emploi IA pour un recrutement basé sur les données.','hr','evaluation','freemium','Gratuit / 109$/mois',['évaluer les compétences des candidats','remplacer les entretiens traditionnels','tester les candidats sur des vraies tâches'],4.5,'https://vervoe.com','🎯','#ec4899',22000,'500+'),
  t('harver','Harver AI','Pré-sélection de candidats IA avec jeux cognitifs et prédiction d\'adéquation.','hr','evaluation','paid','Sur devis',['pré-sélectionner des candidats IA','réduire le turnover','prédire la performance future'],4.5,'https://harver.com','⚡','#10b981',15000,'200+'),
  t('pymetrics','Pymetrics','Évaluation neuroscientifique IA avec des jeux pour mesurer les aptitudes cognitives.','hr','evaluation','paid','Sur devis',['évaluer les aptitudes cognitives','réduire les biais dans le recrutement','prédire la performance et la rétention'],4.4,'https://pymetrics.ai','🎮','#7c3aed',12000,'200+'),
  t('eightfold-ai','Eightfold AI','Plateforme de gestion des talents IA complète pour l\'acquisition et le développement.','hr','rh','paid','Sur devis',['trouver les meilleurs talents','développer les compétences internes','prévoir les besoins en talents'],4.6,'https://eightfold.ai','🌐','#1d4ed8',19000,'1000+'),
  t('textio','Textio AI','IA d\'augmentation des offres d\'emploi pour éliminer les biais et attirer plus de candidats.','hr','recrutement','paid','Sur devis',['améliorer les offres d\'emploi','réduire les biais de genre dans les annonces','attirer des candidats diversifiés'],4.5,'https://textio.com','📝','#f59e0b',16000,'3000+'),
  t('paradox-ai','Paradox (Olivia)','Assistant IA conversationnel pour le recrutement qui planifie les entretiens automatiquement.','hr','recrutement','paid','Sur devis',['planifier des entretiens automatiquement','qualifier des candidats par chatbot','accélérer le recrutement de masse'],4.6,'https://paradox.ai','💬','#6366f1',14000,'500+'),
  t('beamery-ai','Beamery AI','Gestion des talents IA avec cartographie des compétences et engagement des candidats.','hr','talent','paid','Sur devis',['créer un vivier de talents','cartographier les compétences de l\'entreprise','engager des candidats passifs'],4.4,'https://beamery.com','✨','#a855f7',11000,'500+'),
  t('skillate','Skillate AI','Matching IA de candidats et scoring de CV pour les équipes de recrutement.','hr','recrutement','paid','Sur devis',['scorer des CV automatiquement','matcher candidats et postes','analyser la qualité du pipeline'],4.4,'https://skillate.com','🎯','#3b82f6',8000,'200+'),
  t('findem-ai','Findem AI','Sourcing IA 3D qui croise data LinkedIn, GitHub et web pour trouver les meilleurs profils.','hr','sourcing','paid','Sur devis',['trouver des développeurs sur GitHub','sourcer des profils rares','enrichir les profils de candidats'],4.5,'https://findem.ai','🔍','#ef4444',9000,'200+'),

  // ── Formation & E-Learning ─────────────────────────────────────────────────
  t('coursera-ai','Coursera AI','Plateforme de MOOC avec coach IA, résumés de cours et apprentissage personnalisé.','hr','formation','freemium','Gratuit / 59$/mois',['apprendre une nouvelle compétence','obtenir une certification reconnue','suivre une formation en ligne'],4.7,'https://coursera.org','🎓','#0056d2',280000,'100M+',true),
  t('linkedin-learning-ai','LinkedIn Learning AI','Formation en ligne avec recommandations IA personnalisées basées sur votre profil.','hr','formation','freemium','Gratuit 1 mois / 19.99$/mois',['développer mes compétences professionnelles','me former pour un nouveau métier','obtenir des certifications LinkedIn'],4.6,'https://linkedin.com/learning','💼','#0a66c2',180000,'27M+'),
  t('360learning','360Learning AI','LMS collaboratif IA où les experts internes créent et partagent leurs formations.','hr','formation','paid','8$/mois/utilisateur',['créer des formations internes rapidement','faire monter en compétences ses équipes','mesurer l\'efficacité des formations'],4.5,'https://360learning.com','🔄','#f97316',38000,'1700+'),
  t('docebo-ai','Docebo AI','LMS enterprise avec IA pour personnaliser l\'apprentissage et automatiser l\'administration.','hr','formation','paid','Sur devis',['personnaliser les parcours d\'apprentissage','automatiser l\'attribution de formations','mesurer le ROI de la formation'],4.5,'https://docebo.com','📚','#6366f1',18000,'3000+'),
  t('cornerstone-ai','Cornerstone AI','Suite talent management avec IA pour la formation, les compétences et la succession.','hr','formation','paid','Sur devis',['planifier la succession','identifier les compétences manquantes','créer des plans de développement'],4.4,'https://cornerstoneondemand.com','🏛️','#1d4ed8',14000,'6000+'),
  t('degreed-ai','Degreed AI','Plateforme d\'apprentissage en continu qui agrège toutes les ressources de formation.','hr','formation','paid','Sur devis',['centraliser toutes mes ressources d\'apprentissage','mesurer mes compétences','créer un parcours de développement'],4.4,'https://degreed.com','🎓','#10b981',13000,'400+'),
  t('articulate-ai','Articulate AI','Création de cours e-learning IA avec Articulate 360 et Review AI.','hr','formation','paid','1199$/an',['créer des cours e-learning interactifs','développer du contenu de formation rapidement','réviser des cours en collaboration'],4.6,'https://articulate.com','📖','#3b82f6',28000,'120K+'),
  t('learnosity-ai','Learnosity AI','Infrastructure d\'évaluation IA pour créer des quiz et examens adaptatifs.','hr','formation','paid','Sur devis',['créer des évaluations adaptatives','intégrer des quiz dans une plateforme','mesurer les acquis d\'apprentissage'],4.5,'https://learnosity.com','📝','#f59e0b',8000,'1000+'),

  // ── Éducation ──────────────────────────────────────────────────────────────
  t('khanmigo','Khanmigo (Khan Academy)','Tuteur IA de Khan Academy qui guide par des questions sans donner les réponses directement.','hr','education','freemium','Gratuit pour les enseignants / 4$/mois élèves',['tuteur IA pour faire mes devoirs','apprendre les maths avec l\'IA','préparer le bac avec un coach IA'],4.8,'https://khanacademy.org/khan-labs','🏫','#14b8a6',110000,'50M+',true),
  t('duolingo-ai','Duolingo Max AI','Apprendre une langue avec des exercices IA personnalisés, explication et jeu de rôle.','hr','langues','freemium','Gratuit / Duolingo Max 14.99$/mois',['apprendre l\'anglais avec l\'IA','pratiquer une langue par gamification','conversatons IA en langue étrangère'],4.7,'https://duolingo.com','🦜','#58cc02',480000,'500M+',true),
  t('quizlet-ai','Quizlet AI','Plateforme de révision avec flashcards IA, quiz et assistant pour mémoriser plus vite.','hr','education','freemium','Gratuit / 5.99$/mois',['créer des flashcards automatiquement','réviser pour un examen','mémoriser du vocabulaire'],4.6,'https://quizlet.com','🃏','#3b82f6',180000,'60M+'),
  t('photomath','Photomath','Résolvez des problèmes de maths en photographiant l\'énoncé, avec explications étapes.','hr','education','freemium','Gratuit / 9.99$/mois',['résoudre des équations en photo','comprendre les étapes de calcul','aider mon enfant en maths'],4.8,'https://photomath.com','📷','#ef4444',210000,'220M+',true),
  t('wolfram-alpha','Wolfram Alpha','Moteur de réponse computationnel IA pour les maths, sciences et données factuelles.','hr','education','freemium','Gratuit / 5.49$/mois Pro',['résoudre des équations complexes','calculer des intégrales','rechercher des faits scientifiques'],4.7,'https://wolframalpha.com','🧮','#ef0505',190000,'10M+',true),
  t('magic-school-ai','MagicSchool.ai','Suite d\'outils IA pour enseignants : créer des cours, évaluations et communications.','hr','education','freemium','Gratuit / 16$/mois',['créer des plans de cours IA','générer des évaluations personnalisées','rédiger des communications parents'],4.7,'https://magicschool.ai','🪄','#7c3aed',72000,'3M+',true),
  t('eduaide-ai','Eduaide.Ai','Assistant IA pour enseignants avec 100+ types de ressources pédagogiques.','hr','education','freemium','Gratuit / 12$/mois',['créer des exercices différenciés','générer des rubriques d\'évaluation','adapter le contenu aux besoins des élèves'],4.6,'https://eduaide.ai','📚','#f97316',38000,'500K+'),
  t('turnitin-ai','Turnitin AI Detection','Détection de plagiat et de contenu IA dans les travaux académiques.','hr','education','paid','Sur devis établissements',['détecter le plagiat dans les copies','identifier du contenu écrit par IA','vérifier l\'intégrité académique'],4.5,'https://turnitin.com','🔍','#ef4444',62000,'15000+'),
  t('brisk-teaching','Brisk Teaching','Extension Chrome IA pour les enseignants avec retours sur les travaux et création de contenu.','hr','education','freemium','Gratuit / 12$/mois',['donner des retours IA sur des copies','créer du contenu pédagogique','évaluer des travaux étudiants'],4.6,'https://briskteaching.com','⚡','#10b981',28000,'1M+'),
  t('gradescope-ai','Gradescope AI','Notation IA d\'examens et devoirs avec regroupement automatique des réponses.','hr','education','freemium','Gratuit / 3$/étudiant',['noter des copies automatiquement','corriger des examens plus vite','donner des feedbacks cohérents'],4.5,'https://gradescope.com','📊','#3b82f6',19000,'25M+'),

  // ── Coaching & Développement ──────────────────────────────────────────────
  t('betterup-ai','BetterUp AI','Coaching professionnel IA et humain pour développer les leaders et performer.','hr','coaching','paid','Sur devis',['coacher mes managers','développer mes leaders','améliorer le bien-être au travail'],4.6,'https://betterup.com','🚀','#f97316',22000,'3000+'),
  t('lattice-ai','Lattice AI','Gestion des performances avec IA pour les évaluations, OKR et développement des équipes.','hr','performance','paid','11$/mois/utilisateur',['gérer les évaluations de performance','créer des OKR collaboratifs','analyser l\'engagement des équipes'],4.5,'https://lattice.com','🔷','#6366f1',32000,'5000+'),
  t('leapsome-ai','Leapsome AI','Plateforme de performance et d\'apprentissage IA pour les équipes à forte croissance.','hr','performance','paid','Sur devis',['conduire des évaluations continues','créer des cycles de feedback','personnaliser les parcours de développement'],4.5,'https://leapsome.com','🌱','#10b981',18000,'1500+'),
  t('15five-ai','15Five AI','Gestion des performances avec IA pour des check-ins rapides et un coaching proactif.','hr','performance','paid','14$/mois/utilisateur',['effectuer des check-ins hebdomadaires','identifier les collaborateurs en difficulté','améliorer la rétention des talents'],4.5,'https://15five.com','5️⃣','#3b82f6',24000,'3500+'),
  t('impraise-ai','Impraise AI','Plateforme de feedback continu et développement des compétences IA.','hr','performance','paid','Sur devis',['collecter du feedback en continu','développer les compétences','mesurer l\'engagement'],4.3,'https://impraise.com','💬','#a855f7',9000,'500+'),
  t('humu-ai','Humu AI','Nudges comportementaux IA envoyés aux managers pour améliorer le management au quotidien.','hr','coaching','paid','Sur devis',['améliorer les comportements de management','développer les habitudes positives','réduire le turnover par des nudges'],4.3,'https://humu.com','💡','#f59e0b',7000,'200+'),
]

export default tools
