import { t } from './catalog-types'
import type { CatalogTool } from './catalog-types'

const tools: CatalogTool[] = [
  // ── Immobilier ────────────────────────────────────────────────────────────
  t('zillow-ai','Zillow AI','Estimation immobilière IA Zestimate et recherche de biens personnalisée.','industry','immobilier','free','Gratuit',['estimer la valeur d\'un bien','chercher une maison à acheter','analyser le marché immobilier'],4.5,'https://zillow.com','🏠','#0074e4',89000,'200M+',true),
  t('virtual-staging-ai','Virtual Staging AI','Meublez virtuellement vos photos de biens immobiliers avec l\'IA en quelques secondes.','industry','immobilier','freemium','Gratuit 3 essais / 24$/mois',['meubler virtuellement un appartement','améliorer des photos immobilières','vendre plus vite un bien vide'],4.7,'https://virtualstagingai.app','🛋️','#f97316',38000,'200K+',true),
  t('restb-ai','Restb.ai','Vision par ordinateur IA pour tagger et analyser automatiquement les biens immobiliers.','industry','immobilier','paid','Sur devis',['tagger automatiquement des photos de biens','analyser les caractéristiques d\'un bien','enrichir les annonces immobilières'],4.5,'https://restb.ai','🏡','#3b82f6',9000,'500+'),
  t('skyline-ai','Skyline AI (JLL)','IA d\'intelligence du marché immobilier commercial pour prédire la performance.','industry','immobilier','paid','Sur devis',['analyser le marché immobilier commercial','prédire la valeur d\'un actif','optimiser un portefeuille immobilier'],4.5,'https://jll.com','🏢','#e60000',8000,'1000+'),
  t('deepblocks','Deepblocks AI','Analyse de faisabilité immobilière IA pour les promoteurs et investisseurs.','industry','immobilier','paid','Sur devis',['analyser la faisabilité d\'un projet','optimiser le nombre de lots','étudier le potentiel d\'un terrain'],4.4,'https://deepblocks.com','🧱','#7c3aed',7000,'500+'),
  t('deckard-ai','Deckard.ai','Évaluation et analyse de marché IA pour les professionnels de l\'immobilier.','industry','immobilier','paid','Sur devis',['évaluer automatiquement des biens','analyser un quartier','prédire les tendances du marché'],4.3,'https://deckard.ai','🔍','#1d4ed8',5000,'500+'),
  t('propchat-ai','HouseCanary AI','Analytics immobilier IA avec valorisation en temps réel de millions de biens US.','industry','immobilier','paid','Sur devis',['évaluer un portefeuille immobilier','analyser le risque de prêt','prédire l\'évolution des prix'],4.4,'https://housecanary.com','🏚️','#10b981',6000,'1000+'),
  t('rex-ai','REX AI','Courtage immobilier IA qui réduit les commissions en automatisant le processus.','industry','immobilier','paid','2% commission',['vendre ma maison sans agent','économiser sur les commissions','automatiser la vente immobilière'],4.2,'https://rexhomes.com','🏠','#ef4444',12000,'100K+'),

  // ── Architecture ──────────────────────────────────────────────────────────
  t('architechtures-ai','Architechtures AI','Génération automatique de plans d\'étage architecturaux à partir de contraintes.','industry','architecture','paid','49$/mois',['générer un plan d\'appartement','optimiser la disposition des pièces','créer des variantes de plan rapidement'],4.6,'https://architechtures.com','🏛️','#1a1a2e',22000,'5K+'),
  t('finch3d','Finch3D','Conception architecturale générative IA pour optimiser les bâtiments résidentiels.','industry','architecture','paid','Sur devis',['concevoir un immeuble résidentiel','optimiser les surfaces habitables','explorer des variantes architecturales'],4.5,'https://finch3d.com','🐦','#f97316',11000,'1K+'),
  t('autodesk-forma','Autodesk Forma AI','IA de conception architecturale pour l\'analyse de site et la conception durable.','industry','architecture','paid','Sur devis',['analyser le vent et l\'ensoleillement','concevoir un bâtiment durable','évaluer l\'impact environnemental d\'un bâtiment'],4.5,'https://autodesk.com/products/forma','🔬','#000000',14000,'5K+'),
  t('maket-ai','Maket AI','Génération de plans 3D et études de faisabilité architecturale par l\'IA.','industry','architecture','paid','99$/mois',['générer un plan de masse','créer des rendus 3D rapidement','étudier des options de conception'],4.4,'https://maket.ai','🏗️','#6366f1',9000,'2K+'),
  t('hypar-ai','Hypar AI','Plateforme de conception paramétrique IA pour automatiser les analyses d\'ingénierie.','industry','architecture','freemium','Gratuit / Sur devis',['automatiser les calculs structurels','générer des géométries complexes','connecter BIM et IA'],4.4,'https://hypar.io','⚙️','#3b82f6',7000,'5K+'),
  t('testfit-ai','TestFit AI','Optimisation de site immobilier IA pour maximiser la valeur des projets de logements.','industry','architecture','paid','Sur devis',['optimiser le nombre d\'appartements','étudier la faisabilité d\'un projet','itérer rapidement sur des designs de site'],4.5,'https://testfit.io','🏘️','#10b981',8000,'1K+'),
  t('snaptrude','Snaptrude AI','Modélisation BIM collaborative IA dans le navigateur avec génération de plans.','industry','architecture','freemium','Gratuit / 50$/mois',['créer des plans BIM rapidement','collaborer sur un projet architectural','générer automatiquement des niveaux'],4.5,'https://snaptrude.com','🏠','#7c3aed',12000,'20K+'),
  t('spacemaker-ai','Spacemaker AI (Autodesk)','IA de planification urbaine pour optimiser les projets de développement immobilier.','industry','architecture','paid','Sur devis',['planifier un quartier','optimiser un master plan','analyser l\'impact d\'un projet urbain'],4.6,'https://autodesk.com/spacemaker','🌆','#000000',10000,'1K+'),

  // ── Agriculture ────────────────────────────────────────────────────────────
  t('john-deere-ai','John Deere Operations Center AI','IA agricole intégrée dans les machines John Deere pour l\'agriculture de précision.','industry','agriculture','freemium','Gratuit avec machines JD / abonnement',['piloter automatiquement un tracteur','analyser la qualité des sols','optimiser les rendements agricoles'],4.7,'https://operationscenter.deere.com','🚜','#367c2b',38000,'500K+',true),
  t('climate-corp','Climate Corporation AI','Prévisions météo ultra-locales et recommandations agronomiques IA pour les agriculteurs.','industry','agriculture','freemium','Gratuit / abonnement',['planifier mes semis selon la météo','analyser la santé de mes cultures','optimiser les traitements phytosanitaires'],4.5,'https://climate.com','🌦️','#1d4ed8',22000,'100K+'),
  t('prospera-ai','Prospera AI','IA de monitoring des cultures qui analyse les images pour détecter maladies et stress.','industry','agriculture','paid','Sur devis',['détecter les maladies des plantes','surveiller la santé des cultures','réduire les traitements phytosanitaires'],4.5,'https://prospera.ag','🌱','#10b981',12000,'500+'),
  t('taranis-ai','Taranis AI','Intelligence des cultures IA par imagerie drone et satellite pour l\'agriculture.','industry','agriculture','paid','Sur devis',['surveiller mes champs par drone','détecter des ravageurs','cartographier les variabilités de rendement'],4.5,'https://taranis.com','✈️','#f59e0b',10000,'1000+'),
  t('farmwise-ai','FarmWise AI','Robot agricole IA qui désherbe avec précision sans herbicides.','industry','agriculture','paid','Sur devis',['désherber sans herbicides','réduire les coûts d\'entretien','agriculture biologique robotisée'],4.4,'https://farmwise.io','🤖','#15803d',8000,'100+'),
  t('arable-ai','Arable AI','Capteurs de terrain et IA pour suivre météo, sol et cultures en temps réel.','industry','agriculture','paid','Sur devis',['mesurer l\'humidité des sols','prévoir les besoins en irrigation','optimiser les intrants agricoles'],4.4,'https://arable.com','🌿','#059669',7000,'500+'),
  t('granular-ag','Granular Ag AI','Logiciel de gestion agricole IA avec analytics pour optimiser la rentabilité.','industry','agriculture','paid','Sur devis',['gérer ma ferme avec des données','analyser la rentabilité par parcelle','planifier les opérations agricoles'],4.4,'https://granular.ag','📊','#d97706',9000,'10K+'),
  t('semios','Semios AI','Plateforme de gestion des cultures pérennes avec capteurs IoT et IA prédictive.','industry','agriculture','paid','Sur devis',['surveiller les arbres fruitiers','prédire les attaques de ravageurs','optimiser l\'irrigation des vergers'],4.5,'https://semios.com','🍎','#10b981',6000,'1K+'),

  // ── Logistique ────────────────────────────────────────────────────────────
  t('project44-ai','Project44 AI','Visibilité supply chain IA avec suivi en temps réel de millions de livraisons.','industry','logistique','paid','Sur devis',['suivre mes expéditions en temps réel','prévoir les retards de livraison','optimiser mes coûts logistiques'],4.6,'https://project44.com','📦','#f97316',18000,'1200+'),
  t('flexport-ai','Flexport AI','Fret mondial IA qui automatise et optimise les expéditions internationales.','industry','logistique','paid','Sur devis',['expédier des marchandises à l\'international','optimiser les coûts de fret','gérer les douanes avec l\'IA'],4.5,'https://flexport.com','🚢','#1d4ed8',22000,'10K+'),
  t('loadsmart-ai','Loadsmart AI','Courtage de fret routier IA avec tarification instantanée et matching automatique.','industry','logistique','freemium','Gratuit devis / commission',['obtenir un devis de transport routier','réserver un camion instantanément','optimiser les coûts de transport'],4.4,'https://loadsmart.com','🚚','#f43f5e',12000,'10K+'),
  t('kinaxis-ai','Kinaxis AI','Planification de supply chain IA avec simulation et optimisation en temps réel.','industry','logistique','paid','Sur devis',['planifier ma supply chain','simuler des scénarios de disruption','optimiser les stocks'],4.5,'https://kinaxis.com','⚙️','#3b82f6',11000,'500+'),
  t('covariant-ai','Covariant AI','Robot picking IA pour les entrepôts avec apprentissage universel des objets.','industry','logistique','paid','Sur devis',['automatiser le picking entrepôt','trier des colis avec l\'IA','robotiser la logistique'],4.5,'https://covariant.ai','🤖','#6366f1',9000,'100+'),
  t('locus-robotics','Locus Robotics AI','Robots AMR IA pour les entrepôts e-commerce avec optimisation des trajets.','industry','logistique','paid','Sur devis',['automatiser le picking e-commerce','optimiser les trajets entrepôt','augmenter la productivité logistique'],4.5,'https://locusrobotics.com','🤖','#f59e0b',8000,'200+'),
  t('transmetrics','Transmetrics AI','Prévision de la demande et optimisation du réseau logistique IA pour le transport.','industry','logistique','paid','Sur devis',['prévoir la demande de transport','optimiser le réseau de livraison','réduire les véhicules à vide'],4.4,'https://transmetrics.eu','📊','#10b981',5000,'100+'),
  t('o9-solutions','o9 Solutions AI','Plateforme de planification intégrée IA pour supply chain, finances et opérations.','industry','logistique','paid','Sur devis',['planifier les opérations de bout en bout','synchroniser supply chain et finances','optimiser le S&OP avec l\'IA'],4.5,'https://o9solutions.com','🌐','#7c3aed',8000,'200+'),

  // ── Tourisme & Voyage ─────────────────────────────────────────────────────
  t('roam-around','Roam Around AI','Planificateur de voyage IA qui génère des itinéraires personnalisés en quelques secondes.','industry','tourisme','free','Gratuit',['planifier un voyage','créer un itinéraire personnalisé','trouver des activités locales'],4.6,'https://roamaround.io','✈️','#3b82f6',42000,'1M+',true),
  t('wonderplan-ai','Wonderplan AI','Créez des plans de voyage détaillés et personnalisés grâce à l\'IA.','industry','tourisme','free','Gratuit',['créer un planning de vacances','trouver les meilleurs endroits','organiser un road trip'],4.5,'https://wonderplan.ai','🗺️','#10b981',28000,'500K+'),
  t('vacay-chatbot','Vacay Chatbot AI','Chatbot IA de voyage qui recommande des destinations, hôtels et activités.','industry','tourisme','freemium','Gratuit / 9.99$/mois',['trouver un hôtel adapté à mes goûts','recommander une destination','planifier mes vacances en chatbot'],4.4,'https://vacay.io','🌴','#f97316',18000,'200K+'),
  t('layla-travel','Layla AI Travel','Planificateur de voyage IA avec recommandations personnalisées et réservation.','industry','tourisme','free','Gratuit',['trouver l\'hôtel parfait','planifier une lune de miel','recommander des restaurants'],4.5,'https://usegalileo.ai/layla','🧳','#ec4899',22000,'500K+'),
  t('tripnotes-ai','TripNotes AI','Transformez vos préférences en itinéraires de voyage détaillés et réservables.','industry','tourisme','freemium','Gratuit / 5$/mois',['créer un itinéraire détaillé','adapter un voyage à mon budget','trouver des pépites locales'],4.4,'https://tripnotes.ai','📔','#7c3aed',12000,'100K+'),
  t('guidegeek-ai','GuideGeek AI','Guide de voyage IA sur WhatsApp avec recommandations locales en temps réel.','industry','tourisme','free','Gratuit (sur WhatsApp)',['poser des questions de voyage sur WhatsApp','trouver des restaurants locaux','obtenir des conseils de voyage'],4.4,'https://guidegeek.com','🗺️','#25d366',16000,'500K+'),
  t('curiosio','Curiosio AI','Planificateur de road trips IA avec optimisation des itinéraires et points d\'intérêt.','industry','tourisme','free','Gratuit',['planifier un road trip','optimiser un itinéraire voiture','découvrir des sites incontournables'],4.4,'https://curiosio.com','🚗','#f59e0b',11000,'200K+'),
  t('airbnb-ai','Airbnb AI','Recherche de logements personnalisée et assistant IA pour les voyages.','industry','tourisme','free','Gratuit (commission 3%)',['trouver un logement unique','planifier un séjour','explorer de nouvelles destinations'],4.5,'https://airbnb.com','🏠','#ff5a5f',280000,'150M+',true),

  // ── Retail & E-commerce ───────────────────────────────────────────────────
  t('shopify-magic','Shopify Magic AI','IA intégrée à Shopify pour rédiger des descriptions produit, répondre aux clients.','industry','retail','freemium','Inclus dans Shopify / 29$/mois',['rédiger des fiches produit automatiquement','créer des contenus e-commerce','répondre aux questions clients'],4.7,'https://shopify.com/magic','🛍️','#96bf48',190000,'4M+',true),
  t('dynamic-yield','Dynamic Yield AI','Personnalisation IA omnicanal pour le retail : web, app, email et instore.','industry','retail','paid','Sur devis',['personnaliser mon site e-commerce','recommander des produits','tester des expériences A/B'],4.5,'https://dynamicyield.com','🎯','#f97316',18000,'400+'),
  t('nosto-ai','Nosto AI','Personnalisation e-commerce IA pour les recommandations et la segmentation.','industry','retail','paid','Sur devis',['recommander des produits pertinents','personnaliser la page d\'accueil','créer des segments comportementaux'],4.5,'https://nosto.com','✨','#6366f1',14000,'2500+'),
  t('coveo-ai','Coveo AI','Recherche intelligente et recommandations IA pour les sites e-commerce.','industry','retail','paid','Sur devis',['améliorer la recherche sur site','recommander des produits','personnaliser les résultats'],4.5,'https://coveo.com','🔍','#3b82f6',12000,'500+'),
  t('bloomreach-ai','Bloomreach AI','Commerce experience IA pour le search, le merchandising et les campagnes marketing.','industry','retail','paid','Sur devis',['optimiser le merchandising digital','personnaliser l\'expérience d\'achat','automatiser les campagnes e-commerce'],4.5,'https://bloomreach.com','🌸','#ef4444',11000,'1000+'),
  t('constructor-io','Constructor.io AI','Recherche produit et navigation IA avec ML pour augmenter les conversions.','industry','retail','paid','Sur devis',['améliorer la recherche produit','optimiser la navigation catégorie','personnaliser les résultats par client'],4.5,'https://constructor.io','🏗️','#10b981',9000,'300+'),
  t('syte-ai','Syte AI','Recherche visuelle et taggage produit IA pour le retail fashion et home.','industry','retail','paid','Sur devis',['rechercher un produit par photo','tagger automatiquement des produits','recommander des articles similaires'],4.5,'https://syte.ai','👁️','#ec4899',8000,'200+'),
  t('mercaux-ai','Mercaux AI','Outil d\'aide à la vente IA pour les vendeurs en magasin avec recommandations.','industry','retail','paid','Sur devis',['aider les vendeurs en magasin','recommander des produits en boutique','digitaliser l\'expérience retail'],4.3,'https://mercaux.com','🛒','#7c3aed',5000,'50+'),
]

export default tools
