import { t } from './catalog-types'
import type { CatalogTool } from './catalog-types'

const tools: CatalogTool[] = [
  // ── Génération vidéo IA ──────────────────────────────────────────────────
  t('runway-ml','Runway ML','Plateforme de génération et édition vidéo IA de référence avec Gen-2 et Gen-3.','video','generation','freemium','Gratuit 125 crédits / 12$/mois',['générer une vidéo depuis du texte','créer une vidéo depuis une image','animer une photo'],4.8,'https://runwayml.com','🎬','#ef4444',380000,'3M+',true),
  t('pika-labs','Pika Labs','Générateur de vidéos IA créatif avec contrôle sur le mouvement et les effets.','video','generation','freemium','Gratuit / 8$/mois',['créer une vidéo courte IA','animer un personnage','créer des effets vidéo IA'],4.7,'https://pika.art','🎥','#f97316',210000,'2M+',true),
  t('kling-ai','Kling AI','Générateur de vidéos IA photoréaliste de Kuaishou avec des mouvements naturels impressionnants.','video','generation','freemium','Gratuit 66 crédits/jour / 9.9$/mois',['créer des vidéos réalistes IA','générer des mouvements naturels','créer des publicités vidéo'],4.7,'https://klingai.com','🎬','#7c3aed',185000,'2M+',true),
  t('sora-openai','Sora','Générateur de vidéos IA haute qualité d\'OpenAI avec une cohérence temporelle exceptionnelle.','video','generation','freemium','Inclus ChatGPT Plus/Pro',['créer des vidéos cinématographiques','générer des scènes réalistes','créer des clips musicaux IA'],4.8,'https://sora.com','🌀','#10a37f',290000,'5M+',true),
  t('dream-machine-luma','Dream Machine (Luma AI)','Générateur de vidéos réalistes et cinématiques depuis texte ou image par Luma AI.','video','generation','freemium','Gratuit 30 vidéos/mois / 29.99$/mois',['créer des vidéos photoréalistes','animer des images fixes','générer des scènes dynamiques'],4.7,'https://lumalabs.ai/dream-machine','🎞️','#6366f1',160000,'1M+',true),
  t('haiper-ai','Haiper AI','Génération de vidéos courtes IA avec un style artistique unique et rapide.','video','generation','freemium','Gratuit / 9$/mois',['créer des vidéos artistiques','générer des clips courts','animer des concepts créatifs'],4.5,'https://haiper.ai','💫','#ec4899',78000,'500K+'),
  t('stable-video','Stable Video Diffusion','Modèle open source de Stability AI pour générer des vidéos courtes depuis des images.','video','generation','free','Open source gratuit',['animer une image fixe','générer des vidéos en local','créer des animations artistiques'],4.5,'https://stability.ai/stable-video','🌊','#5c54c4',95000,'1M+'),
  t('kaiber-ai','Kaiber AI','Transformez vos photos et musiques en vidéos artistiques animées.','video','generation','freemium','Gratuit 100 crédits / 5$/mois',['créer un clip musical IA','animer des photos avec de la musique','créer du contenu artistique animé'],4.5,'https://kaiber.ai','🎵','#7c3aed',62000,'500K+'),
  t('genmo-ai','Genmo AI','Plateforme créative IA pour générer des vidéos et animations depuis du texte.','video','generation','freemium','Gratuit / 8$/mois',['créer des animations depuis du texte','générer des vidéos créatives','créer du contenu motion graphics'],4.4,'https://genmo.ai','🎨','#f43f5e',41000,'200K+'),
  t('moonvalley','MoonValley','Générateur de vidéos IA haute résolution avec une attention particulière aux détails.','video','generation','freemium','Gratuit liste d\'attente / Bientôt payant',['générer des vidéos 4K IA','créer des scènes détaillées','produire du contenu vidéo professionnel'],4.5,'https://moonvalley.ai','🌙','#1a1a2e',55000,'200K+'),

  // ── Avatars IA / Synthèse humaine ────────────────────────────────────────
  t('heygen','HeyGen','Créez des vidéos avec des avatars IA réalistes et clonez votre voix en 30 secondes.','video','avatar','freemium','Gratuit 1 min/mois / 29$/mois',['créer une vidéo de présentation avec avatar','cloner ma voix pour des vidéos','traduire une vidéo avec mon avatar'],4.8,'https://heygen.com','👤','#6366f1',320000,'2M+',true),
  t('synthesia','Synthesia','Plateforme professionnelle de création de vidéos avec avatars IA pour la formation et le marketing.','video','avatar','paid','22$/mois',['créer des vidéos de formation IA','produire des vidéos corporate sans caméra','multilinguiser une vidéo avec avatar'],4.8,'https://synthesia.io','🎭','#9333ea',280000,'1M+',true),
  t('d-id','D-ID','Animez des photos et créez des présentateurs IA pour des vidéos personnalisées.','video','avatar','freemium','Gratuit 5 vidéos / 5.9$/mois',['animer un portrait photo','créer un présentateur IA','personnaliser des vidéos à grande échelle'],4.6,'https://d-id.com','🤖','#ec4899',190000,'1M+'),
  t('deepbrain-ai','DeepBrain AI (AI Studios)','Générez des vidéos professionnelles avec des avatars IA hyper-réalistes et du texte.','video','avatar','paid','30$/mois',['créer des vidéos d\'entreprise sans acteur','produire du e-learning','créer des vidéos multilingues'],4.5,'https://aistudios.com','🎬','#3b82f6',75000,'200K+'),

  // ── Édition vidéo IA ─────────────────────────────────────────────────────
  t('descript','Descript','Éditeur vidéo et podcast révolutionnaire : éditez la vidéo en éditant la transcription comme un document.','video','edition','freemium','Gratuit / 24$/mois',['éditer une vidéo en éditant le texte','supprimer les mots de remplissage automatiquement','créer un podcast vidéo','transcrire et éditer une interview'],4.8,'https://descript.com','📝','#7c3aed',280000,'5M+',true),
  t('capcut-ai','CapCut AI','Éditeur vidéo IA de ByteDance avec effets automatiques, sous-titres et templates viraux.','video','edition','freemium','Gratuit / 9.99$/mois',['monter une vidéo TikTok','ajouter des sous-titres automatiquement','créer des effets vidéo tendances'],4.8,'https://capcut.com','✂️','#000000',480000,'200M+',true),
  t('veed-io','VEED.io','Éditeur vidéo en ligne avec sous-titres IA, traduction et outils de collaboration.','video','edition','freemium','Gratuit / 18$/mois',['ajouter des sous-titres automatiquement','traduire une vidéo','éditer une vidéo en ligne sans logiciel'],4.7,'https://veed.io','🎬','#ef4444',190000,'12M+',true),
  t('invideo-ai','InVideo AI','Créez des vidéos professionnelles depuis un texte ou un script en quelques minutes.','video','edition','freemium','Gratuit 4 exports/sem / 25$/mois',['créer une vidéo depuis un texte','transformer un article en vidéo','créer des publicités vidéo'],4.6,'https://invideo.io','📹','#6366f1',160000,'7M+'),
  t('pictory-ai','Pictory AI','Transformez des articles, scripts ou longues vidéos en clips courts partageables.','video','edition','paid','25$/mois',['transformer un blog en vidéo','créer des highlights de webinaire','recycler du contenu long en shorts'],4.5,'https://pictory.ai','🎬','#10b981',89000,'1M+'),
  t('lumen5','Lumen5','Transformez du contenu texte en vidéos engageantes pour les réseaux sociaux.','video','edition','freemium','Gratuit / 29$/mois',['transformer un article en vidéo','créer du contenu LinkedIn','automatiser la création vidéo'],4.4,'https://lumen5.com','🎞️','#f97316',95000,'800K+'),
  t('fliki-ai','Fliki AI','Créez des vidéos et podcasts depuis du texte avec des voix IA réalistes et des visuels.','video','edition','freemium','Gratuit / 28$/mois',['créer une vidéo depuis du texte','transformer du texte en voix IA','créer du contenu vidéo multilingue'],4.5,'https://fliki.ai','📱','#7c3aed',78000,'1M+'),
  t('opus-clip','Opus Clip','Découpez automatiquement vos longues vidéos en clips courts viraux pour TikTok et Shorts.','video','edition','freemium','Gratuit 60 min/mois / 19$/mois',['découper une vidéo en clips courts','créer des Shorts YouTube','recycler des webinaires en contenu'],4.7,'https://opus.pro','✂️','#f43f5e',140000,'1M+',true),
  t('vidyo-ai','Vidyo.ai','Repurposez vos longues vidéos en contenu court optimisé pour chaque plateforme.','video','edition','freemium','Gratuit / 29$/mois',['créer des TikTok depuis des podcasts','découper des streams en highlights','optimiser des vidéos pour chaque réseau'],4.5,'https://vidyo.ai','📐','#6366f1',61000,'500K+'),
  t('munch-ai','Munch AI','IA qui identifie les moments clés de vos vidéos et crée automatiquement des clips optimisés.','video','edition','paid','49$/mois',['extraire les meilleurs moments d\'une vidéo','créer des clips automatiquement','analyser la performance des clips'],4.5,'https://www.getmunch.com','🌙','#1d4ed8',42000,'200K+'),
  t('submagic','Submagic','Ajoutez des sous-titres animés automatiques et stylisés à vos vidéos short-form.','video','sous-titres','freemium','Gratuit / 20$/mois',['ajouter des sous-titres animés','créer des captions virales','sous-titrer un Reel automatiquement'],4.7,'https://submagic.co','💬','#7c3aed',98000,'500K+',true),
  t('captions-ai','Captions AI','Éditeur vidéo mobile avec sous-titres automatiques, correction IA et effets.','video','sous-titres','freemium','Gratuit / 19.99$/mois',['sous-titrer une vidéo sur iPhone','corriger mes erreurs de langue IA','créer du contenu vidéo mobile'],4.6,'https://captions.ai','💬','#ec4899',110000,'10M+'),
  t('wisecut','Wisecut','Éditeur vidéo IA qui coupe les silences et pauses automatiquement pour un montage parfait.','video','edition','freemium','Gratuit / 10$/mois',['couper les silences automatiquement','monter un podcast vidéo rapidement','améliorer le rythme d\'une vidéo'],4.5,'https://wisecut.video','✂️','#10b981',38000,'200K+'),

  // ── Présentation IA ──────────────────────────────────────────────────────
  t('gamma-ai','Gamma AI','Créez des présentations, documents et pages web magnifiques en quelques secondes depuis du texte.','video','presentation','freemium','Gratuit / 10$/mois',['créer une présentation depuis du texte','générer un pitch deck IA','créer une landing page rapidement'],4.8,'https://gamma.app','⚡','#6366f1',310000,'10M+',true),
  t('beautiful-ai','Beautiful.ai','Créez des présentations professionnelles avec IA qui s\'adapte automatiquement au design.','video','presentation','freemium','Gratuit / 12$/mois',['créer un deck de présentation','designer des slides automatiquement','créer des présentations d\'équipe'],4.6,'https://beautiful.ai','🌟','#ec4899',120000,'2M+'),
  t('tome-ai','Tome','Outil de narration IA qui crée des présentations interactives et des pitchs captivants.','video','presentation','freemium','Gratuit / 16$/mois',['créer un pitch de startup','présenter une idée visuellement','créer un document interactif'],4.6,'https://tome.app','📖','#3b82f6',140000,'3M+'),
  t('magicslides','MagicSlides','Transformez du texte ou un sujet en présentation PowerPoint/Google Slides en 3 secondes.','video','presentation','freemium','Gratuit 3 ppts/mois / 9$/mois',['créer une présentation depuis un sujet','générer des slides automatiquement','transformer du texte en PowerPoint'],4.5,'https://magicslides.app','🪄','#a855f7',88000,'1M+'),
  t('decktopus','Decktopus','Créateur de présentations IA avec conseils de design et narration intelligente.','video','presentation','freemium','Gratuit / 9.99$/mois',['créer une présentation professionnelle','générer un pitch deck','automatiser la création de slides'],4.4,'https://decktopus.com','🂡','#7c3aed',56000,'500K+'),
  t('plus-ai','Plus AI','Extension Google Slides qui génère et améliore vos présentations avec l\'IA.','video','presentation','freemium','Gratuit / 10$/mois',['améliorer une présentation existante','générer des slides dans Google Slides','reformuler du contenu de présentation'],4.5,'https://plusdocs.com','📊','#4285f4',48000,'500K+'),
  t('visme-ai','Visme AI','Créez des infographies, présentations et visuels de marque avec l\'IA.','video','presentation','freemium','Gratuit / 12.25$/mois',['créer une infographie','designer une présentation de marque','générer des visuels data'],4.5,'https://visme.co','📊','#6366f1',78000,'4M+'),

  // ── Animation & Motion Capture ───────────────────────────────────────────
  t('cascadeur','Cascadeur AI','Logiciel d\'animation 3D IA pour créer des mouvements réalistes de personnages.','video','animation','freemium','Gratuit / 99$/an',['animer un personnage 3D','créer des animations de jeu','simuler des mouvements physiques'],4.6,'https://cascadeur.com','🦿','#1a1a2e',28000,'100K+'),
  t('plask-ai','Plask AI','Animation 3D par motion capture IA depuis une simple vidéo de téléphone.','video','animation','freemium','Gratuit / 11.25$/mois',['motion capture depuis une vidéo','animer un personnage 3D','créer des animations pour le jeu vidéo'],4.5,'https://plask.ai','🎬','#7c3aed',19000,'50K+'),
  t('krikey-ai','Krikey AI','Créez des animations de personnages 3D et des vidéos animées avec l\'IA.','video','animation','freemium','Gratuit / 9$/mois',['créer un personnage animé','générer une courte animation','créer du contenu éducatif animé'],4.4,'https://krikey.ai','🐙','#f97316',14000,'100K+'),
  t('animaker-ai','Animaker AI','Créez des vidéos animées professionnelles avec des personnages, scènes et voix IA.','video','animation','freemium','Gratuit / 19$/mois',['créer une vidéo animée explainer','réaliser un dessin animé','créer une animation pour enfants'],4.4,'https://animaker.com','🎨','#ec4899',62000,'15M+'),
]

export default tools
