import { t } from './catalog-types'
import type { CatalogTool } from './catalog-types'

const tools: CatalogTool[] = [
  // ── Génération musicale IA ────────────────────────────────────────────────
  t('suno-ai','Suno AI','Créez des chansons complètes avec paroles et musique en décrivant simplement le style.','audio','musique','freemium','Gratuit 50 crédits/jour / 10$/mois',['créer une chanson IA','générer de la musique depuis du texte','composer un jingle','créer une musique de fond'],4.8,'https://suno.com','🎵','#f97316',390000,'10M+',true),
  t('udio','Udio','Génération musicale IA haute qualité avec contrôle précis du style et des instruments.','audio','musique','freemium','Gratuit 100 générations/mois / 10$/mois',['générer de la musique professionnelle','créer des instrumentales','composer dans des genres spécifiques'],4.7,'https://udio.com','🎼','#7c3aed',180000,'3M+',true),
  t('mubert','Mubert','Génération de musique IA sans droits pour le streaming, les podcasts et les créateurs.','audio','musique','freemium','Gratuit / 14$/mois',['créer une musique de fond royalty-free','générer une playlist IA','musique pour des vidéos YouTube'],4.5,'https://mubert.com','🎶','#6366f1',89000,'1M+'),
  t('soundraw','Soundraw','Composez de la musique IA personnalisable avec contrôle sur le mood, le tempo et les instruments.','audio','musique','paid','16.99$/mois',['créer de la musique de fond vidéo','personnaliser une composition IA','musique sans droits d\'auteur pour contenus'],4.6,'https://soundraw.io','🎹','#10b981',71000,'500K+'),
  t('aiva','AIVA','Compositeur IA émotionnel pour films, jeux vidéo et publicités avec styles variés.','audio','musique','freemium','Gratuit / 15$/mois',['composer de la musique pour un film','créer une bande originale de jeu vidéo','générer de la musique classique IA'],4.6,'https://aiva.ai','🎻','#3b82f6',65000,'300K+'),
  t('boomy','Boomy','Créez des chansons originales IA en secondes et publiez-les sur Spotify et Apple Music.','audio','musique','freemium','Gratuit / 2.99$/mois',['créer une chanson et la publier','générer de la musique de relaxation','composer de la trap IA'],4.4,'https://boomy.com','🎧','#a855f7',82000,'5M+'),
  t('beatoven-ai','Beatoven.ai','Générez des musiques de fond IA adaptées au mood de vos vidéos et podcasts.','audio','musique','freemium','Gratuit 15 min/mois / 12$/mois',['générer une musique adaptée à une vidéo','créer une atmosphère sonore','musique IA pour podcast'],4.5,'https://beatoven.ai','🥁','#f59e0b',38000,'200K+'),
  t('loudly-ai','Loudly AI','Plateforme de musique IA avec 170K stems pour créer des compositions uniques.','audio','musique','freemium','Gratuit / 9.99$/mois',['créer de la musique IA royalty-free','mixer des stems IA','générer de la musique dance/EDM'],4.4,'https://loudly.com','🔊','#ef4444',31000,'500K+'),
  t('musicfy','Musicfy','Clonez votre voix ou celle de célébrités et créez des covers de chansons avec l\'IA.','audio','musique','freemium','Gratuit / 14.99$/mois',['couvrir une chanson avec ma voix','cloner une voix pour de la musique','créer des chansons AI voice covers'],4.5,'https://musicfy.lol','🎤','#ec4899',52000,'1M+'),
  t('moises-app','Moises App','Séparez les pistes d\'une chanson (voix, batterie, basse) et transposez la tonalité automatiquement.','audio','musique','freemium','Gratuit / 5.99$/mois',['séparer la voix d\'une chanson','extraire l\'instrumentale','transposer une chanson'],4.7,'https://moises.ai','🎸','#10b981',110000,'5M+',true),
  t('lalal-ai','LALAL.AI','Séparateur de stems IA haute qualité pour extraire voix, batterie, basse, piano.','audio','musique','freemium','Gratuit 10 min / 15$/10min',['extraire la voix d\'une chanson','isoler la batterie','créer une version karaoké'],4.7,'https://lalal.ai','🎵','#6366f1',88000,'5M+'),
  t('vocal-remover','Vocal Remover','Séparez gratuitement et instantanément la voix de la musique dans n\'importe quelle chanson.','audio','musique','free','Gratuit',['supprimer la voix d\'une chanson','créer une version instrumentale','karaoké IA gratuit'],4.5,'https://vocalremover.org','🎙️','#f97316',140000,'10M+',true),
  t('magenta-studio','Magenta Studio (Google)','Plugins de composition IA par Google pour Ableton : génération de mélodies et continuation.','audio','musique','free','Open source gratuit',['générer des mélodies IA dans Ableton','continuer une mélodie','harmoniser une composition'],4.5,'https://magenta.tensorflow.org/studio','🎹','#4285f4',24000,'100K+'),
  t('soundful','Soundful','Créez de la musique de fond unique royalty-free pour vos contenus créatifs.','audio','musique','freemium','Gratuit / 9.99$/mois',['musique de fond pour mes vidéos','créer du contenu sans droits','personnaliser l\'ambiance musicale'],4.4,'https://soundful.com','🌊','#3b82f6',26000,'200K+'),

  // ── Voix & Text-to-Speech ─────────────────────────────────────────────────
  t('elevenlabs','ElevenLabs','Synthèse vocale IA la plus réaliste : clonez votre voix, créez des audiobooks et du contenu vocal.','audio','voix','freemium','Gratuit 10K chars/mois / 5$/mois',['cloner ma voix','créer un audiobook','transformer du texte en voix réaliste','doubler une vidéo dans une autre langue'],4.9,'https://elevenlabs.io','🎙️','#f43f5e',480000,'1M+',true),
  t('play-ht','Play.ht','Générateur de voix IA ultra-réaliste pour podcasts, articles et contenus d\'apprentissage.','audio','voix','freemium','Gratuit / 31.2$/mois',['créer des voix IA pour mon podcast','textifier des articles','créer des messages vocaux personnalisés'],4.7,'https://play.ht','📢','#7c3aed',180000,'1M+'),
  t('murf-ai','Murf AI','Créez des voix off professionnelles en 120+ langues sans micro ni studio.','audio','voix','freemium','Gratuit / 26$/mois',['créer une voix off pour une vidéo','générer du contenu de formation vocal','produire un audiobook professionnel'],4.7,'https://murf.ai','🎤','#6366f1',150000,'500K+'),
  t('wellsaid-labs','WellSaid Labs','Voix off IA de qualité studio pour le marketing, l\'e-learning et les communications.','audio','voix','paid','49$/mois',['créer des voix de qualité studio','produire du e-learning vocal','voix off pour publicités'],4.7,'https://wellsaidlabs.com','🎚️','#3b82f6',68000,'200K+'),
  t('resemble-ai','Resemble AI','Clonage vocal IA, synthèse temps réel et génération d\'effets sonores IA.','audio','voix','freemium','Gratuit / 99$/mois',['cloner une voix en quelques minutes','créer un avatar vocal','générer des effets sonores IA'],4.6,'https://resemble.ai','🔊','#a855f7',52000,'100K+'),
  t('speechify','Speechify','Transformez n\'importe quel texte en audio avec des voix célébrités ou des voix clonées.','audio','voix','freemium','Gratuit / 139$/an',['écouter des articles en voiture','lire plus vite avec audio','transformer des PDFs en audio'],4.7,'https://speechify.com','👂','#f97316',210000,'20M+',true),
  t('lovo-ai','LOVO AI','Plateforme de voix off IA et clonage vocal avec 500+ voix en 100 langues.','audio','voix','freemium','Gratuit / 24$/mois',['créer une voix off multilingue','cloner une voix personnalisée','produire des publicités audio'],4.6,'https://lovo.ai','🎙️','#ec4899',72000,'300K+'),
  t('altered-ai','Altered AI','Transformez et modifiez votre voix en temps réel avec des effets IA avancés.','audio','voix','freemium','Gratuit / 19$/mois',['changer ma voix en temps réel','créer des personnages vocaux','modifier une voix enregistrée'],4.5,'https://altered.ai','🔄','#6366f1',31000,'100K+'),
  t('replica-studios','Replica Studios','Voix IA expressives pour les jeux vidéo, films et contenus créatifs.','audio','voix','freemium','Gratuit / 24$/mois',['créer des voix de personnages de jeu','production de voix pour animation','générer des voix expressives'],4.5,'https://replicastudios.com','🎭','#7c3aed',28000,'50K+'),

  // ── Podcast ───────────────────────────────────────────────────────────────
  t('adobe-podcast','Adobe Podcast','Enregistrez, éditez et améliorez vos podcasts avec l\'IA : suppression du bruit, transcription.','audio','podcast','freemium','Gratuit / inclus Adobe Creative Cloud',['améliorer la qualité audio d\'un podcast','supprimer le bruit de fond','transcrire un podcast automatiquement'],4.8,'https://podcast.adobe.com','🎙️','#ff0000',160000,'2M+',true),
  t('podcastle-ai','Podcastle AI','Enregistrez, éditez et publiez des podcasts IA de qualité studio depuis votre navigateur.','audio','podcast','freemium','Gratuit / 11.99$/mois',['enregistrer un podcast de qualité studio','éditer un podcast en ligne','créer un podcast solo avec des invités IA'],4.6,'https://podcastle.ai','🏰','#6366f1',78000,'500K+'),
  t('riverside-ai','Riverside.fm AI','Plateforme d\'enregistrement podcast et vidéo HD avec édition IA et transcription.','audio','podcast','freemium','Gratuit / 15$/mois',['enregistrer un podcast à distance','éditer un podcast automatiquement','transcrire un enregistrement'],4.7,'https://riverside.fm','🎬','#10b981',120000,'2M+'),
  t('cleanvoice-ai','Cleanvoice AI','Supprimez automatiquement les remplisseurs de silence, les mots de remplissage et bruits de bouche.','audio','podcast','freemium','Gratuit 30 min / 10$/mois',['nettoyer un enregistrement audio','supprimer les "euh" et "ah"','améliorer la fluidité d\'un podcast'],4.7,'https://cleanvoice.ai','🧹','#f97316',62000,'200K+'),
  t('auphonic','Auphonic','Post-production audio automatique : normalisation, suppression de bruit, chapitres.','audio','podcast','freemium','2h gratuit/mois / 11$/mois',['normaliser l\'audio d\'un podcast','améliorer la qualité d\'un enregistrement','publier sur toutes les plateformes'],4.6,'https://auphonic.com','⚡','#3b82f6',55000,'300K+'),
  t('headliner-ai','Headliner AI','Transformez vos podcasts en vidéos et audiogrammes viraux pour les réseaux sociaux.','audio','podcast','freemium','Gratuit / 12.99$/mois',['créer un audiogramme de podcast','transformer un podcast en vidéo','promouvoir un podcast sur les réseaux'],4.5,'https://headliner.app','📻','#a855f7',48000,'1M+'),
  t('capsho-ai','Capsho AI','Générez automatiquement des show notes, titres et contenus marketing depuis votre audio.','audio','podcast','freemium','Gratuit / 83$/mois',['générer des show notes de podcast','créer du contenu marketing depuis l\'audio','rédiger des descriptions d\'épisode'],4.5,'https://capsho.com','📝','#7c3aed',22000,'30K+'),
  t('transistor-ai','Transistor.fm AI','Hébergement podcast avec analytics avancés et outils IA pour développer votre audience.','audio','podcast','paid','19$/mois',['héberger mon podcast','analyser l\'audience d\'un podcast','distribuer sur Spotify et Apple'],4.6,'https://transistor.fm','📡','#ef4444',31000,'50K+'),

  // ── Traitement audio ──────────────────────────────────────────────────────
  t('krisp','Krisp','Suppression du bruit de fond IA en temps réel pour les appels vidéo et enregistrements.','audio','traitement','freemium','Gratuit 60 min/jr / 8$/mois',['supprimer le bruit de fond en visio','améliorer la qualité d\'un appel','enregistrer sans bruit ambiant'],4.8,'https://krisp.ai','🔇','#10b981',280000,'10M+',true),
  t('audo-ai','Audo.ai','Améliorez la qualité de n\'importe quel enregistrement audio en un clic avec l\'IA.','audio','traitement','freemium','Gratuit 15 min / 10$/mois',['améliorer la qualité d\'un enregistrement','nettoyer un fichier audio','restaurer un vieux enregistrement'],4.6,'https://audo.ai','🎚️','#6366f1',38000,'300K+'),
  t('izotope-ai','iZotope RX AI','Suite de restauration audio professionnelle avec IA pour les studios et post-production.','audio','traitement','paid','99$/an',['restaurer des enregistrements anciens','supprimer des bruits indésirables','réparer de l\'audio de studio'],4.8,'https://izotope.com/rx','🔬','#1a1a2e',24000,'500K+'),
  t('audioshake-ai','AudioShake AI','Séparation de sources audio IA pour l\'industrie musicale et les médias.','audio','traitement','paid','Sur devis',['séparer les pistes d\'une chanson professionnellement','remixer pour le cinéma','restaurer des archives musicales'],4.6,'https://audioshake.ai','🎵','#7c3aed',11000,'1000+'),
  t('adobe-audition-ai','Adobe Audition AI','DAW professionnel avec outils IA pour la restauration, le mixage et l\'édition.','audio','traitement','paid','20.99€/mois',['mixer de l\'audio professionnellement','restaurer un enregistrement','enlever les bruits de clics et pops'],4.7,'https://adobe.com/audition','🎛️','#002fa7',58000,'5M+'),
  t('noise-eraser','Noise Eraser','Application mobile IA de suppression du bruit de fond pour les enregistrements audio.','audio','traitement','freemium','Gratuit / 2.99$/mois',['supprimer le bruit d\'un enregistrement mobile','améliorer une vidéo bruitée','nettoyer un entretien'],4.4,'https://noiseeraser.com','🔕','#10b981',24000,'1M+'),
  t('infinite-drum','Infinite Drum Machine','Explorez un espace latent infini de sons percussifs générés par l\'IA de Google.','audio','traitement','free','Gratuit',['explorer des sons de batterie IA','créer des beats uniques','expérimenter avec des textures sonores'],4.4,'https://experiments.withgoogle.com/drum-machine','🥁','#f97316',18000,'1M+'),
]

export default tools
