import { t } from './catalog-types'
import type { CatalogTool } from './catalog-types'

const tools: CatalogTool[] = [
  // ── Rédaction & Copywriting ───────────────────────────────────────────────
  t('jasper-ai','Jasper AI','Plateforme de rédaction IA enterprise avec des templates pour chaque format marketing.','writing','copywriting','paid','49$/mois',['rédiger des articles de blog','créer des textes publicitaires','générer des emails marketing','écrire des descriptions produit'],4.7,'https://jasper.ai','✍️','#7c3aed',290000,'1M+',true),
  t('copy-ai','Copy.ai','Générez du contenu marketing, des posts et des emails en 25+ langues instantanément.','writing','copywriting','freemium','Gratuit 2000 mots/mois / 49$/mois',['écrire des posts réseaux sociaux','créer des accroches publicitaires','rédiger des emails de vente'],4.6,'https://copy.ai','📋','#6366f1',220000,'10M+',true),
  t('writesonic','Writesonic','Rédacteur IA complet avec Chatsonic (accès web), générateur d\'articles et optimisation SEO.','writing','copywriting','freemium','Gratuit / 16$/mois',['générer un article de blog complet','rédiger des textes web','créer du contenu SEO optimisé'],4.7,'https://writesonic.com','⚡','#3b82f6',180000,'4M+'),
  t('rytr','Rytr','Assistant de rédaction IA abordable pour blogs, emails et réseaux sociaux en 40+ langues.','writing','copywriting','freemium','Gratuit 10K chars/mois / 9$/mois',['rédiger un email de relance','écrire un article court','créer des descriptions de produit'],4.5,'https://rytr.me','✏️','#10b981',150000,'8M+'),
  t('grammarly-ai','Grammarly AI','Correcteur grammatical et assistant de rédaction IA intégré à tous vos outils de travail.','writing','correction','freemium','Gratuit / 12$/mois',['corriger ma grammaire et orthographe','améliorer le style d\'un texte','vérifier le ton d\'un email','adapter le registre de ma rédaction'],4.8,'https://grammarly.com','✅','#15c39a',680000,'30M+',true),
  t('quillbot','QuillBot','Rephraseur, résumeur et paraphraseur IA pour améliorer et simplifier vos textes.','writing','correction','freemium','Gratuit / 9.95$/mois',['rephrsaer un texte','résumer un article','corriger une rédaction','éviter le plagiat'],4.7,'https://quillbot.com','🔄','#6dc552',320000,'30M+',true),
  t('wordtune','Wordtune','Reformulez, résumez et réécrivez vos textes avec des suggestions contextuelles IA.','writing','correction','freemium','Gratuit 10 réécritures/jour / 9.99$/mois',['reformuler une phrase maladroite','trouver de meilleures formulations','simplifier un texte complexe'],4.6,'https://wordtune.com','🌊','#7c3aed',140000,'5M+'),
  t('notion-ai','Notion AI','IA intégrée à Notion pour rédiger, résumer, traduire et analyser directement dans vos pages.','writing','productivite','freemium','Gratuit avec Notion / 10$/mois',['rédiger dans Notion avec l\'IA','résumer des notes de réunion','créer un plan de contenu','brainstormer des idées'],4.7,'https://notion.so/product/ai','📓','#000000',380000,'30M+',true),
  t('sudowrite','Sudowrite','Assistant de rédaction créative IA pour romanciers avec génération de plot et de descriptions.','writing','fiction','paid','19$/mois',['écrire un roman avec l\'IA','développer des personnages','générer des scènes narratives'],4.6,'https://sudowrite.com','📚','#7c3aed',42000,'150K+'),
  t('anyword','Anyword','Plateforme de copywriting IA avec prédiction de performance et A/B testing automatisé.','writing','copywriting','paid','49$/mois',['prédire la performance d\'un texte','optimiser des publicités','créer des landing pages converties'],4.6,'https://anyword.com','🎯','#f97316',68000,'500K+'),
  t('hypotenuse-ai','Hypotenuse AI','Génération de contenu e-commerce IA à grande échelle : fiches produit, blogs et publicités.','writing','ecommerce','freemium','Gratuit / 29$/mois',['rédiger des descriptions produit en masse','créer du contenu e-commerce','générer des articles SEO'],4.5,'https://hypotenuse.ai','🚀','#3b82f6',52000,'300K+'),
  t('copysmith','Copysmith','Générateur de contenu IA pour les équipes e-commerce et les grandes marques.','writing','copywriting','paid','19$/mois',['créer des descriptions produit en lot','générer du contenu marketing coordonné','rédiger des ads Facebook et Google'],4.4,'https://copysmith.ai','🖊️','#ec4899',38000,'200K+'),
  t('writer-com','Writer.com','Plateforme de rédaction IA enterprise avec modèles personnalisés et guide de style.','writing','copywriting','paid','18$/mois/utilisateur',['rédiger du contenu cohérent en équipe','appliquer la charte de rédaction','créer des templates de contenu'],4.6,'https://writer.com','✒️','#1d4ed8',45000,'500K+'),
  t('contentatscale','Content at Scale','Générateur d\'articles de blog longs optimisés SEO qui imitent la plume humaine.','writing','seo','paid','250$/mois',['créer des articles longs SEO','publier du contenu IA non détectable','générer 10 articles par jour'],4.5,'https://contentatscale.ai','📈','#10b981',29000,'50K+'),
  t('longshot-ai','LongShot AI','Rédacteur de contenu long format IA avec research intégrée et vérification de faits.','writing','seo','freemium','Gratuit / 19$/mois',['écrire un article de fond','vérifier les faits d\'un texte','créer du contenu avec des sources'],4.4,'https://longshot.ai','🎯','#7c3aed',32000,'100K+'),
  t('textcortex','TextCortex','Assistant de rédaction IA multifonction disponible partout via extension navigateur.','writing','copywriting','freemium','Gratuit 100 créations/mois / 6.99$/mois',['rédiger partout sur le web','reformuler un email','créer du contenu en un clic'],4.5,'https://textcortex.com','🧠','#a855f7',58000,'2M+'),
  t('cohesive-ai','Cohesive AI','Éditeur de contenu IA collaboratif avec 200+ templates et modification en temps réel.','writing','copywriting','freemium','Gratuit / 13.99$/mois',['créer du contenu avec mon équipe','utiliser des templates de rédaction','éditer et améliorer du contenu collaborativement'],4.4,'https://cohesive.so','🤝','#6366f1',34000,'500K+'),
  t('hyperwrite-ai','HyperWrite','Extension IA qui rédige, reformule et prédit le texte dans n\'importe quelle application web.','writing','copywriting','freemium','Gratuit / 19.99$/mois',['compléter mes phrases automatiquement','rédiger dans Gmail ou Notion','reformuler un texte sélectionné'],4.4,'https://hyperwriteai.com','✨','#3b82f6',26000,'500K+'),
  t('compose-ai','Compose AI','Extension Chrome IA pour rédiger 40% plus vite avec autocomplétion et reformulation.','writing','productivite','free','Gratuit',['écrire plus vite dans Gmail','compléter automatiquement mes emails','reformuler dans n\'importe quelle fenêtre'],4.4,'https://compose.ai','🚀','#f97316',42000,'1M+'),
  t('ai21-studio','AI21 Labs (Wordtune)','LLM de pointe avec Jurassic-2 pour la génération de texte enterprise.','writing','copywriting','freemium','Gratuit / Pay as you go',['générer du texte de haute qualité','paraphraser des documents','créer des applications texte IA'],4.5,'https://www.ai21.com','🔬','#6d28d9',28000,'100K+'),
  t('simplified-writing','Simplified AI','Suite créative IA tout-en-un : rédaction, design et réseaux sociaux pour les équipes.','writing','copywriting','freemium','Gratuit / 18$/mois',['gérer tout le contenu depuis un outil','créer du texte et des visuels ensemble','planifier les réseaux sociaux'],4.5,'https://simplified.com','🌟','#ec4899',87000,'4M+'),

  // ── SEO ──────────────────────────────────────────────────────────────────
  t('surfer-seo','Surfer SEO','Optimisez vos articles pour le top 1 Google avec des recommandations IA en temps réel.','writing','seo','paid','89$/mois',['optimiser un article pour Google','analyser les mots-clés d\'un concurrent','créer une stratégie de contenu SEO'],4.7,'https://surferseo.com','🏄','#06b6d4',180000,'150K+',true),
  t('marketmuse','MarketMuse','Plateforme de stratégie de contenu IA qui identifie les lacunes et opportunités SEO.','writing','seo','freemium','Gratuit / 149$/mois',['créer un plan de contenu SEO','identifier les gaps de contenu','optimiser l\'autorité thématique'],4.6,'https://marketmuse.com','📊','#7c3aed',48000,'500K+'),
  t('frase-io','Frase.io','Recherche de contenu et optimisation SEO IA pour écrire des articles qui rankent.','writing','seo','paid','15$/mois',['rechercher des sujets SEO','optimiser un article existant','créer un brief de contenu'],4.5,'https://frase.io','🔎','#10b981',62000,'300K+'),
  t('clearscope','Clearscope','Outil d\'optimisation de contenu IA utilisé par les équipes SEO des grandes entreprises.','writing','seo','paid','189$/mois',['améliorer le score de pertinence d\'un article','optimiser pour les termes sémantiques','analyser le contenu des concurrents'],4.7,'https://clearscope.io','📊','#3b82f6',39000,'100K+'),
  t('neuronwriter','NeuronWriter','Outil SEO et rédaction IA qui analyse les SERPs pour créer du contenu optimisé.','writing','seo','paid','23$/mois',['analyser les SERPs pour écrire mieux','créer du contenu optimisé NLP','planifier une stratégie de contenu'],4.6,'https://neuronwriter.com','🧠','#f97316',31000,'50K+'),
  t('semrush-writing','Semrush (Writing)','Suite SEO complète avec assistant de rédaction IA pour optimiser chaque article.','writing','seo','freemium','Gratuit / 129.95$/mois',['analyser mes mots-clés','auditer mon site SEO','surveiller les classements'],4.7,'https://semrush.com/writing-assistant','🔭','#ff6b00',310000,'10M+',true),
  t('ahrefs-content','Ahrefs Content','Outil SEO de référence pour la recherche de mots-clés, l\'analyse de backlinks et le contenu.','writing','seo','paid','99$/mois',['trouver des mots-clés à fort potentiel','analyser les backlinks concurrents','auditer mon contenu'],4.8,'https://ahrefs.com','🔗','#1d4ed8',280000,'5M+',true),
  t('content-harmony','Content Harmony','Brief de contenu IA et optimisation sémantique pour les équipes de contenu.','writing','seo','paid','99$/mois',['créer des briefs de contenu détaillés','guider des rédacteurs freelance','optimiser le contenu sémantiquement'],4.5,'https://contentharmony.com','🎵','#10b981',18000,'10K+'),
  t('alli-ai','Alli AI','Automatisation SEO IA pour optimiser des milliers de pages en quelques clics.','writing','seo','paid','299$/mois',['automatiser l\'optimisation SEO','mettre à jour des méta-descriptions en masse','corriger les erreurs SEO techniques'],4.4,'https://alli.ai','🤖','#7c3aed',12000,'5000+'),
  t('outranking-io','Outranking.io','Écriture SEO IA assistée avec SERP analysis et optimisation en temps réel.','writing','seo','paid','79$/mois',['rédiger du contenu SEO guidé','analyser les concurrents Google','créer une stratégie de liens internes'],4.4,'https://outranking.io','🏆','#f59e0b',14000,'20K+'),
  t('growthbar','GrowthBar','SEO IA et générateur de contenu pour les blogueurs et équipes marketing.','writing','seo','paid','36$/mois',['générer des articles SEO rapidement','trouver des opportunités de mots-clés','créer du contenu pour mon blog'],4.4,'https://growthbarseo.com','📊','#6366f1',22000,'50K+'),

  // ── Traduction ──────────────────────────────────────────────────────────
  t('deepl','DeepL','Le meilleur traducteur IA avec une qualité nuance et naturelle supérieure à Google Translate.','writing','traduction','freemium','Gratuit / 8.74€/mois Pro',['traduire un document professionnellement','traduire un site web','améliorer ma rédaction dans une autre langue'],4.9,'https://deepl.com','🌍','#1c6cf0',590000,'10M+',true),
  t('google-translate','Google Translate','Traduction IA gratuite dans 133 langues avec traduction en temps réel via caméra.','writing','traduction','free','Gratuit',['traduire du texte gratuitement','traduire depuis la caméra','comprendre une langue étrangère'],4.6,'https://translate.google.com','🌐','#4285f4',890000,'500M+',true),
  t('microsoft-translator','Microsoft Translator','Service de traduction IA de Microsoft intégré à Office, Teams et Azure.','writing','traduction','free','Gratuit / Pay as you go API',['traduire dans Teams','traduction en temps réel pour réunions','traduire des documents Word'],4.5,'https://translator.microsoft.com','🪟','#0078d4',180000,'50M+'),
  t('deepl-write','DeepL Write','Améliorez la qualité et le style de votre rédaction en anglais et en allemand.','writing','correction','freemium','Gratuit / inclus DeepL Pro',['améliorer mon anglais écrit','corriger le style en allemand','affiner ma rédaction professionnelle'],4.6,'https://deepl.com/write','✍️','#1c6cf0',95000,'2M+'),
  t('lilt-ai','Lilt AI','Plateforme de traduction IA adaptative pour les entreprises avec mémoire de traduction.','writing','traduction','paid','Sur devis',['traduire en masse des documents','adapter la traduction à mon secteur','localiser un logiciel'],4.5,'https://lilt.com','🔄','#6366f1',18000,'500+'),
  t('unbabel','Unbabel','Traduction IA + humaine pour un service client multilingue de qualité.','writing','traduction','paid','Sur devis',['traduire le service client','localiser des communications','garantir la qualité de traduction'],4.5,'https://unbabel.com','🌊','#3b82f6',14000,'2000+'),
  t('lokalise-ai','Lokalise AI','Plateforme de localisation IA pour les équipes produit avec traduction automatique.','writing','traduction','paid','120$/mois',['localiser une application','gérer les traductions produit','automatiser la localisation'],4.5,'https://lokalise.com','🌐','#7c3aed',16000,'3000+'),
  t('phrase-ai','Phrase AI','TMS (Translation Management System) avec IA pour les entreprises tech.','writing','traduction','paid','Sur devis',['gérer des projets de traduction','automatiser le flux de localisation','intégrer la traduction dans le CI/CD'],4.5,'https://phrase.com','📝','#10b981',12000,'5000+'),
  t('smartcat','Smartcat','Plateforme tout-en-un de traduction IA et de gestion de traducteurs.','writing','traduction','freemium','Gratuit / Pay per use',['gérer des traducteurs freelance','combiner IA et traduction humaine','créer un flux de traduction'],4.4,'https://smartcat.com','🐱','#f59e0b',22000,'1M+'),
  t('weglot','Weglot AI','Traduisez et gérez votre site web multilingue automatiquement avec l\'IA.','writing','traduction','paid','17$/mois',['créer un site multilingue','traduire mon Shopify automatiquement','gérer les traductions de mon site web'],4.6,'https://weglot.com','🌍','#06b6d4',38000,'70K+'),
]

export default tools
