import { t } from './catalog-types'
import type { CatalogTool } from './catalog-types'

const tools: CatalogTool[] = [
  // ── Cuisine & Restauration ────────────────────────────────────────────────
  t('whisk-ai','Whisk (Google)','Sauvegardez des recettes depuis n\'importe quel site et planifiez vos repas avec l\'IA.','misc','cuisine','free','Gratuit',['sauvegarder des recettes','planifier mes repas de la semaine','créer une liste de courses'],4.5,'https://whisk.com','🍳','#f59e0b',38000,'3M+',true),
  t('chefgpt','ChefGPT','Générateur de recettes IA qui crée des plats à partir des ingrédients que vous avez.','misc','cuisine','freemium','Gratuit / 4.99$/mois',['trouver une recette avec mes ingrédients','créer des repas adaptés à mon régime','découvrir de nouvelles recettes'],4.5,'https://chefgpt.xyz','👨‍🍳','#f97316',42000,'1M+'),
  t('plant-jammer','Plant Jammer AI','Planification de repas végétaliens et végétariens avec IA et réduction du gaspillage.','misc','cuisine','freemium','Gratuit / 10$/mois',['cuisiner végétarien créativement','utiliser les restes du frigo','réduire le gaspillage alimentaire'],4.4,'https://plantjammer.com','🌿','#10b981',18000,'200K+'),
  t('popmenu-ai','Popmenu AI','Plateforme restaurant IA avec gestion de menu, site web et marketing automatisé.','misc','restauration','paid','199$/mois',['créer un site de restaurant','gérer mon menu dynamiquement','automatiser le marketing restaurant'],4.5,'https://popmenu.com','🍽️','#ef4444',14000,'10K+'),
  t('toast-ai','Toast AI Intelligence','Analytics et insights IA pour les restaurateurs pour optimiser les opérations.','misc','restauration','paid','Sur devis avec Toast POS',['analyser les performances de mon restaurant','optimiser mon menu','prédire les ventes quotidiennes'],4.5,'https://toasttab.com','🍞','#ef4444',12000,'100K+'),
  t('craftable-ai','Craftable AI','Gestion des coûts et des achats pour les bars et restaurants avec IA.','misc','restauration','paid','Sur devis',['contrôler les coûts de boissons','gérer les stocks de bar','optimiser les achats restaurant'],4.4,'https://craftable.com','🍸','#7c3aed',6000,'5K+'),
  t('recipai-io','RecipAI','Génération de recettes personnalisées basées sur vos ingrédients, régimes et préférences.','misc','cuisine','freemium','Gratuit / 3.99$/mois',['trouver une recette rapide','adapter une recette à mes allergies','créer un menu de la semaine'],4.4,'https://recipai.com','🥗','#10b981',22000,'500K+'),
  t('flavoriq','FlavorIQ AI','IA de développement produit pour l\'industrie agroalimentaire avec prédiction des tendances.','misc','restauration','paid','Sur devis',['développer de nouveaux produits alimentaires','analyser les tendances gustatives','innover en R&D agroalimentaire'],4.4,'https://flavoriq.ai','🌶️','#f43f5e',5000,'200+'),

  // ── Sciences ──────────────────────────────────────────────────────────────
  t('alphafold','AlphaFold (DeepMind)','IA révolutionnaire de DeepMind qui prédit la structure 3D de toutes les protéines connues.','misc','science','free','Gratuit (accès base de données)',['prédire la structure d\'une protéine','rechercher des structures moléculaires','accélérer la recherche médicale'],4.9,'https://alphafold.ebi.ac.uk','🧬','#4285f4',58000,'1M+',true),
  t('schrödinger-ai','Schrödinger AI','Simulation moléculaire et découverte de médicaments par IA pour la pharma.','misc','science','paid','Sur devis',['découvrir de nouveaux médicaments','simuler des interactions moléculaires','accélérer le développement pharmaceutique'],4.7,'https://schrodinger.com','💊','#1d4ed8',14000,'2000+'),
  t('insilico-medicine','Insilico Medicine AI','Découverte de médicaments IA de bout en bout avec génération de molécules.','misc','science','paid','Sur devis',['générer de nouvelles molécules',  'identifier des cibles thérapeutiques','accélérer les essais cliniques'],4.6,'https://insilico.com','🔬','#7c3aed',11000,'500+'),
  t('benchling-ai','Benchling AI','Plateforme de R&D biologique IA pour les équipes de biotech et pharma.','misc','science','paid','Sur devis',['gérer des expériences biologiques','analyser des données NGS','collaborer sur des projets de biotech'],4.5,'https://benchling.com','🧪','#10b981',12000,'2000+'),
  t('chemix-ai','Chemix AI','Créez des diagrammes de labo et des schémas chimiques professionnels avec l\'IA.','misc','science','freemium','Gratuit / 6$/mois',['créer un schéma de montage chimique','dessiner un circuit électronique','générer des figures scientifiques'],4.5,'https://chemix.org','⚗️','#6366f1',19000,'1M+'),
  t('recursion-ai','Recursion AI','Découverte de médicaments IA à ultra-haute échelle avec robots et deep learning.','misc','science','paid','Sur devis',['cribler des millions de molécules','identifier des effets médicamenteux','accélérer la découverte en biologie'],4.6,'https://recursion.com','🤖','#f43f5e',9000,'500+'),
  t('perplexity-science','Consensus / Science AI','Synthèse de la littérature scientifique par IA pour des revues de preuves rapides.','misc','science','freemium','Gratuit / 9.99$/mois',['synthétiser des études scientifiques','vérifier une affirmation médicale','revue de littérature rapide'],4.6,'https://consensus.app','🎓','#3b82f6',32000,'1M+'),
  t('openai-o1','OpenAI o1 (reasoning)','Modèle de raisonnement avancé d\'OpenAI pour résoudre des problèmes scientifiques complexes.','misc','science','freemium','Inclus ChatGPT Pro / API pay-as-you-go',['résoudre des problèmes de physique avancés','raisonner sur des problèmes mathématiques','coder des algorithmes complexes'],4.8,'https://openai.com/o1','🧠','#10a37f',89000,'10M+',true),

  // ── Journalisme & Médias ──────────────────────────────────────────────────
  t('automated-insights','Automated Insights (Wordsmith)','Génération automatique de narrations textuelles à partir de données pour le journalisme.','misc','journalisme','paid','Sur devis',['générer des articles à partir de données','automatiser les rapports financiers','créer des résumés sportifs automatiques'],4.5,'https://automatedinsights.com','📰','#1d4ed8',8000,'500+'),
  t('newsguard-ai','NewsGuard AI','Extension IA qui évalue la fiabilité des sources d\'information et détecte les fakes news.','misc','journalisme','freemium','Gratuit extension / Pro pour médias',['vérifier la fiabilité d\'une source','détecter les fake news','évaluer la crédibilité d\'un article'],4.5,'https://newsguardtech.com','🛡️','#10b981',22000,'1M+'),
  t('primer-ai','Primer AI','IA d\'analyse de l\'information et de veille pour les gouvernements et médias.','misc','journalisme','paid','Sur devis',['analyser des volumes massifs d\'information','détecter des tendances émergentes','créer des briefings d\'intelligence'],4.5,'https://primer.ai','📊','#7c3aed',7000,'200+'),
  t('ground-news','Ground News AI','Comparez les biais politiques des médias et identifiez les angles couverts ou ignorés.','misc','journalisme','freemium','Gratuit / 9.99$/mois',['détecter les biais médiatiques','comparer la couverture d\'un événement','s\'informer sans bulles de filtre'],4.6,'https://ground.news','🌍','#f97316',28000,'5M+'),
  t('aylien-ai','Aylien AI','API d\'analyse de texte et veille médiatique IA pour les professionnels de l\'information.','misc','journalisme','paid','Sur devis',['analyser le sentiment des articles','faire de la veille médiatique','extraire des entités nommées'],4.4,'https://aylien.com','📡','#3b82f6',6000,'500+'),
  t('chartbeat-ai','Chartbeat AI','Analytics temps réel et IA pour les médias digitaux avec recommandations d\'engagement.','misc','journalisme','paid','Sur devis',['analyser le trafic éditorial en temps réel','optimiser les titres d\'articles','prédire la viralité du contenu'],4.5,'https://chartbeat.com','📈','#f43f5e',12000,'1000+'),
  t('knowhere-ai','Knowhere News AI','Agrégateur d\'actualités IA qui présente les événements sans biais politiques.','misc','journalisme','free','Gratuit',['lire l\'actualité sans biais','comprendre différents points de vue','s\'informer objectivement'],4.3,'https://knowherenews.com','📰','#6366f1',9000,'200K+'),
  t('diffbot-ai','Diffbot AI','Web scraping et extraction de données structurées IA pour le journalisme de données.','misc','journalisme','paid','Sur devis',['extraire des données du web','créer une base de données d\'articles','analyser les médias en masse'],4.4,'https://diffbot.com','🕷️','#1a1a2e',8000,'1000+'),

  // ── Gaming ────────────────────────────────────────────────────────────────
  t('ai-dungeon','AI Dungeon','Jeu d\'aventure textuelle IA où l\'histoire s\'adapte à chaque décision.','misc','gaming','freemium','Gratuit / 9.99$/mois',['jouer à un RPG textuel infini','créer une histoire interactive','jeu de rôle avec l\'IA'],4.4,'https://aidungeon.com','🎲','#1a1a2e',68000,'5M+'),
  t('inworld-ai','Inworld AI','Moteur de PNJ IA pour les jeux vidéo avec des personnages qui parlent et réagissent.','misc','gaming','freemium','Gratuit / Pay as you go',['créer des PNJ intelligents pour mon jeu','dialogues dynamiques dans un jeu','personnages non-joueurs réalistes'],4.6,'https://inworld.ai','🎮','#7c3aed',28000,'50K+'),
  t('charisma-ai','Charisma.AI','Personnages IA narratifs pour les jeux, VR et expériences interactives.','misc','gaming','freemium','Gratuit / 99$/mois',['créer des personnages IA narratifs','jeux éducatifs avec PNJ intelligents','expériences de storytelling interactif'],4.5,'https://charisma.ai','🎭','#ec4899',16000,'5K+'),
  t('scenario-gg','Scenario.gg','Générateur d\'assets visuels IA pour les jeux vidéo avec fine-tuning de style.','misc','gaming','freemium','Gratuit / 15$/mois',['générer des assets de jeu vidéo','créer des textures cohérentes','générer des personnages de jeu'],4.5,'https://scenario.gg','🖼️','#f97316',24000,'50K+'),
  t('unity-muse','Unity Muse AI','IA intégrée à Unity pour générer des assets, du code et des comportements de jeu.','misc','gaming','freemium','Gratuit / 30$/mois',['générer des scripts Unity','créer des assets 3D depuis du texte','accélérer le développement de jeux'],4.5,'https://unity.com/products/muse','🎮','#000000',31000,'1M+'),
  t('ludo-ai','Ludo AI','Plateforme de game design IA pour trouver des idées de jeux et analyser le marché.','misc','gaming','freemium','Gratuit / 59$/mois',['trouver des idées de game design','analyser des jeux concurrents','créer un GDD avec l\'IA'],4.4,'https://ludo.ai','🎯','#6366f1',12000,'20K+'),
  t('promethean-ai','Promethean AI','Construction de mondes virtuels IA pour les artistes de jeux et la VR.','misc','gaming','freemium','Gratuit / Sur devis studio',['construire un environnement de jeu','générer une scène 3D','peupler un monde virtuel'],4.4,'https://prometheanai.com','🌍','#a855f7',11000,'10K+'),
  t('meshy-ai','Meshy AI','Générateur de modèles 3D IA depuis du texte ou des images pour les jeux et la 3D.','misc','gaming','freemium','Gratuit / 20$/mois',['créer un modèle 3D depuis du texte','générer des assets 3D pour mon jeu','transformer une image en objet 3D'],4.6,'https://meshy.ai','🔷','#3b82f6',38000,'500K+',true),

  // ── Accessibilité ──────────────────────────────────────────────────────────
  t('be-my-ai','Be My AI (Be My Eyes)','IA qui décrit visuellement l\'environnement pour les personnes malvoyantes via téléphone.','misc','accessibilite','free','Gratuit',['décrire une image pour une personne aveugle','lire un document pour malvoyant','naviguer dans un environnement inconnu'],4.8,'https://bemyeyes.com/ai','👁️','#3b82f6',52000,'700K+',true),
  t('orcam-ai','OrCam MyEye AI','Dispositif portable IA qui lit le texte, reconnaît les visages et identifie les objets.','misc','accessibilite','paid','3990€ appareil',['lire du texte pour malvoyants','reconnaître des visages','identifier des billets et produits'],4.7,'https://orcam.com','👓','#1d4ed8',18000,'100K+'),
  t('seeing-ai','Seeing AI (Microsoft)','Application IA de Microsoft qui décrit le monde pour les personnes malvoyantes.','misc','accessibilite','free','Gratuit',['lire du texte avec l\'IA','décrire une scène pour malvoyant','identifier des personnes et émotions'],4.7,'https://seeing.ai','👁️','#0078d4',38000,'1M+',true),
  t('voiceitt','Voiceitt AI','Reconnaissance vocale IA pour les personnes avec des troubles de la parole.','misc','accessibilite','freemium','Gratuit / abonnement',['communiquer avec un trouble de la parole','adapter la reconnaissance vocale','aide à la communication alternative'],4.5,'https://voiceitt.com','🗣️','#f97316',9000,'50K+'),
  t('google-lookout','Google Lookout AI','Application Android IA qui aide les personnes malvoyantes à identifier leur environnement.','misc','accessibilite','free','Gratuit (Android)',['identifier des objets pour malvoyants','lire du texte en temps réel','explorer un environnement inconnu'],4.5,'https://lookout.app','👁️','#4285f4',16000,'500K+'),
  t('readspeaker-ai','ReadSpeaker AI','Solution TTS IA enterprise pour rendre les contenus digitaux accessibles.','misc','accessibilite','paid','Sur devis',['rendre mon site accessible aux malvoyants','créer des versions audio de contenus','conformité accessibilité RGAA'],4.5,'https://readspeaker.com','📢','#3b82f6',8000,'5000+'),

  // ── Artisanat & Créativité ─────────────────────────────────────────────────
  t('artbreeder','Artbreeder AI','Créez et explorez des portraits, paysages et œuvres d\'art en mélangeant des images.','misc','creativite','freemium','Gratuit / 8.99$/mois',['créer des portraits IA uniques','mélanger des styles artistiques','explorer la génération d\'art'],4.5,'https://artbreeder.com','🎨','#a855f7',72000,'10M+'),
  t('neural-love','Neural.love','Amélioration et restauration de photos et vidéos IA avec upscaling et déblurring.','misc','creativite','freemium','Gratuit 5 images / 30$/mois',['améliorer une vieille photo','restaurer une image dégradée','agrandir une photo en haute qualité'],4.5,'https://neural.love','💕','#ec4899',38000,'500K+'),
  t('wombo-ai','WOMBO AI','Applications créatives IA : génération d\'art, lip sync et NFT.','misc','creativite','freemium','Gratuit / 9.99$/mois',['créer de l\'art IA facilement','animer une photo','générer des NFT'],4.3,'https://wombo.art','🎪','#f97316',62000,'5M+'),
  t('pixray','PixRay AI','Générateur d\'art IA open source avec des styles très artistiques et alternatifs.','misc','creativite','free','Open source gratuit',['créer de l\'art pixel','générer de l\'art voxel','explorer des styles artistiques alternatifs'],4.3,'https://pixray.com','🕹️','#7c3aed',18000,'200K+'),
  t('deepdream','DeepDream Generator','Transformez vos photos en œuvres d\'art psychédéliques inspirées des réseaux de neurones.','misc','creativite','freemium','Gratuit / 19$/mois',['créer de l\'art psychédélique','transformer une photo en style artistique','explorer l\'art neural'],4.3,'https://deepdreamgenerator.com','🌀','#6366f1',28000,'2M+'),
  t('inkarnate','Inkarnate AI','Créez des cartes de monde fantasy et de jeux de rôle avec des outils IA.','misc','creativite','freemium','Gratuit / 5$/mois',['créer une carte de monde fantasy','dessiner une carte pour D&D','créer des cartes de jeu de rôle'],4.6,'https://inkarnate.com','🗺️','#a78b44',22000,'1M+'),
]

export default tools
