import { t } from './catalog-types'
import type { CatalogTool } from './catalog-types'

const tools: CatalogTool[] = [
  // ── IA Généraliste ────────────────────────────────────────────────────────
  t('chatgpt','ChatGPT','Le chatbot IA le plus populaire au monde par OpenAI, capable de tout : écrire, analyser, coder.','generaliste','chat','freemium','Gratuit / Plus 20$/mois',['discuter avec une IA','écrire du contenu','analyser un document','répondre à mes questions'],4.9,'https://chat.openai.com','🤖','#10a37f',990000,'100M+',true),
  t('claude-ai','Claude','L\'IA conversationnelle d\'Anthropic, reconnue pour sa nuance, son éthique et l\'analyse de longs documents.','generaliste','chat','freemium','Gratuit / Pro 20$/mois',['analyser un long document','rédiger avec nuance','discuter de sujets complexes','générer du code propre'],4.9,'https://claude.ai','🧠','#d97706',820000,'10M+',true),
  t('gemini','Gemini','L\'IA multimodale de Google qui comprend texte, images, audio et vidéo avec accès au web.','generaliste','chat','freemium','Gratuit / Advanced 21.99€/mois',['faire des recherches en temps réel','analyser une image','créer du contenu multimodal','résumer une vidéo YouTube'],4.8,'https://gemini.google.com','✨','#4285f4',760000,'50M+',true),
  t('microsoft-copilot','Microsoft Copilot','L\'IA de Microsoft intégrée à Windows, Edge, Office 365 et Bing avec accès temps réel au web.','generaliste','chat','freemium','Gratuit / Pro 20$/mois',['chercher sur le web avec l\'IA','intégrer l\'IA dans Word et Excel','générer des images avec DALL-E','résumer des pages web'],4.7,'https://copilot.microsoft.com','🪟','#0078d4',680000,'100M+',true),
  t('mistral-chat','Le Chat (Mistral)','Le chatbot IA européen de Mistral AI, rapide, multilingue et respectueux de la confidentialité.','generaliste','chat','freemium','Gratuit / Pro 14.99€/mois',['discuter en français avec une IA','générer du contenu en français','analyser des documents en toute confidentialité','coder avec une IA européenne'],4.7,'https://chat.mistral.ai','🌬️','#ff7000',340000,'5M+',true),
  t('perplexity','Perplexity AI','Moteur de réponses IA avec citations en temps réel, idéal pour la recherche et la vérification.','generaliste','recherche','freemium','Gratuit / Pro 20$/mois',['rechercher une information fiable','vérifier des faits','résumer l\'actualité','faire de la veille'],4.8,'https://perplexity.ai','🔍','#1fb8cd',520000,'10M+',true),
  t('grok','Grok (xAI)','L\'IA d\'Elon Musk intégrée à X (Twitter) avec accès en temps réel aux tendances et actualités.','generaliste','chat','freemium','Gratuit avec X Premium',['analyser les tendances Twitter','obtenir des informations en temps réel','poser des questions sans censure','générer du contenu humoristique'],4.5,'https://grok.x.ai','🚀','#1da1f2',280000,'5M+'),
  t('deepseek','DeepSeek','LLM chinois de haute performance, open source, performant sur les maths et le code.','generaliste','chat','free','Gratuit',['résoudre des problèmes de maths','coder avec un modèle open source','analyser des données complexes','raisonnement avancé'],4.7,'https://chat.deepseek.com','🌊','#1a73e8',410000,'10M+',true),
  t('meta-ai','Meta AI','L\'IA de Meta disponible sur WhatsApp, Instagram, Facebook et Messenger.','generaliste','chat','free','Gratuit',['discuter sur WhatsApp avec l\'IA','générer des images gratuitement','obtenir des recommandations','demander des conseils quotidiens'],4.5,'https://www.meta.ai','🦙','#0082fb',310000,'50M+'),
  t('poe','Poe (Quora)','Plateforme qui regroupe GPT-4, Claude, Gemini, Llama et des centaines de chatbots en un seul endroit.','generaliste','chat','freemium','Gratuit / 19.99$/mois',['comparer plusieurs IA','accéder à tous les modèles IA','créer son propre chatbot','discuter avec des bots spécialisés'],4.5,'https://poe.com','🌀','#a855f7',170000,'5M+'),
  t('you-com','You.com','Moteur de recherche IA avec chat, génération d\'images et applications IA intégrées.','generaliste','recherche','freemium','Gratuit / Pro 15$/mois',['rechercher sans publicités','utiliser plusieurs IA dans un moteur de recherche','générer des images depuis la recherche'],4.4,'https://you.com','🔎','#3b82f6',120000,'3M+'),
  t('pi-ai','Pi (Inflection)','IA conversationnelle conçue pour le soutien émotionnel, la réflexion et les conversations profondes.','generaliste','chat','free','Gratuit',['obtenir un soutien émotionnel IA','réfléchir à un problème personnel','avoir une conversation bienveillante'],4.5,'https://pi.ai','😊','#ec4899',95000,'1M+'),
  t('character-ai','Character.AI','Créez et discutez avec des personnages IA : célébrités, personnages fictifs ou vos propres créations.','generaliste','chat','freemium','Gratuit / c.ai+ 9.99$/mois',['discuter avec un personnage fictif','créer un personnage IA','jeu de rôle avec l\'IA','pratiquer une langue avec un personnage'],4.4,'https://character.ai','🎭','#8b5cf6',310000,'20M+'),
  t('coral-cohere','Coral (Cohere)','Assistant IA d\'entreprise par Cohere, optimisé pour la recherche sur documents internes.','generaliste','chat','freemium','Gratuit trial / Enterprise',['rechercher dans mes documents d\'entreprise','créer un assistant interne','sécuriser mes données avec une IA'],4.4,'https://coral.cohere.com','🌊','#39594d',45000,'100K+'),

  // ── Data & Analytics ─────────────────────────────────────────────────────
  t('julius-ai','Julius AI','Analysez et visualisez vos données en téléchargeant un CSV et en posant des questions en langage naturel.','data','analyse','freemium','Gratuit / 20$/mois',['analyser un fichier CSV','créer des graphiques automatiquement','poser des questions sur mes données','générer des insights de données'],4.7,'https://julius.ai','📊','#3b82f6',38000,'200K+',true),
  t('rows-ai','Rows AI','Tableur en ligne avec IA intégrée pour analyser, résumer et visualiser vos données.','data','tableur','freemium','Gratuit / 59$/mois',['analyser des données dans un tableur','créer des formules avec l\'IA','importer des données depuis des APIs','automatiser un reporting'],4.5,'https://rows.com','📈','#10b981',18000,'100K+'),
  t('obviously-ai','Obviously AI','Créez des modèles de machine learning prédictifs sans code en quelques minutes.','data','ml','freemium','Gratuit trial / 75$/mois',['prédire des churn clients','créer un modèle prédictif sans coder','faire des prévisions de ventes'],4.4,'https://www.obviously.ai','🔮','#6366f1',12000,'20K+'),
  t('polymer-ai','Polymer','Transformez n\'importe quel dataset en une base de données intelligente avec recherche IA.','data','analyse','freemium','Gratuit / 10$/mois',['explorer mes données','créer un dashboard interactif','partager des données avec mon équipe'],4.4,'https://www.polymersearch.com','🔬','#f97316',9000,'50K+'),
  t('pandas-ai','PandasAI','Bibliothèque Python qui rend les DataFrames conversationnels grâce aux LLM.','data','python','free','Open source gratuit',['analyser des données en Python avec l\'IA','poser des questions sur un DataFrame','visualiser des données en langage naturel'],4.5,'https://pandas-ai.com','🐼','#150458',19000,'50K+'),
  t('thoughtspot-ai','ThoughtSpot AI','Plateforme de BI qui permet aux non-techniciens de poser des questions sur leurs données.','data','bi','paid','Sur devis',['faire de la BI sans SQL','créer des rapports en langage naturel','analyser des données d\'entreprise'],4.5,'https://www.thoughtspot.com','💡','#e8502f',15000,'500K+'),
  t('dataiku','Dataiku','Plateforme collaborative de data science et MLOps pour les équipes enterprise.','data','ml','paid','Sur devis',['créer des pipelines ML','collaborer sur des projets data','déployer des modèles en production'],4.5,'https://www.dataiku.com','🔧','#2ab1ac',13000,'500K+'),
  t('databricks-ai','Databricks AI','Plateforme lakehouse pour le big data, ML et l\'IA générative à l\'échelle enterprise.','data','big-data','paid','Sur devis',['traiter du big data','entraîner des LLM','déployer des modèles ML en production'],4.6,'https://www.databricks.com/product/machine-learning','🧱','#ff3621',18000,'5000+'),
  t('snowflake-cortex','Snowflake Cortex','IA intégrée dans Snowflake pour analyser, résumer et générer du contenu depuis vos données.','data','big-data','paid','Pay as you go',['analyser des données Snowflake avec l\'IA','créer un LLM sur mes données cloud','faire de la recherche sémantique'],4.5,'https://www.snowflake.com/cortex','❄️','#29b5e8',11000,'10000+'),
  t('google-analytics-ai','Google Analytics 4 (IA)','Analytics web avec insights IA, prédictions de churn et modélisation des conversions.','data','analytics','free','Gratuit',['analyser le trafic de mon site','prévoir les conversions','comprendre le comportement utilisateur'],4.6,'https://analytics.google.com','📊','#e37400',110000,'5M+',true),
  t('mixpanel-ai','Mixpanel AI','Analytics produit avec insights IA pour comprendre le comportement et la rétention utilisateur.','data','analytics','freemium','Gratuit / 28$/mois',['analyser la rétention utilisateur','trouver les points de friction','segmenter mes utilisateurs automatiquement'],4.6,'https://mixpanel.com','📱','#7856ff',26000,'1M+'),
  t('amplitude-ai','Amplitude AI','Plateforme analytics avec IA pour optimiser l\'expérience produit et augmenter la rétention.','data','analytics','freemium','Gratuit / 61$/mois',['analyser le funnel produit','créer des cohortes automatiquement','prédire le churn'],4.6,'https://amplitude.com','🎯','#1a53f0',21000,'1M+'),

  // ── Recherche ────────────────────────────────────────────────────────────
  t('elicit','Elicit','Moteur de recherche scientifique IA qui extrait des données de millions de papiers académiques.','data','recherche-academique','freemium','Gratuit / 12$/mois',['faire une revue de littérature','trouver des études scientifiques','extraire des données de papers','résumer des recherches académiques'],4.7,'https://elicit.org','📚','#8b5cf6',28000,'300K+',true),
  t('consensus-ai','Consensus','Moteur de recherche scientifique IA qui synthétise les résultats de milliers d\'études.','data','recherche-academique','freemium','Gratuit / 10.99$/mois',['trouver des consensus scientifiques','vérifier une affirmation par les études','rechercher des preuves scientifiques'],4.6,'https://consensus.app','🔬','#3b82f6',22000,'200K+'),
  t('semantic-scholar','Semantic Scholar AI','Moteur de recherche académique gratuit avec résumés IA et graphe de citations.','data','recherche-academique','free','Gratuit',['trouver des articles scientifiques gratuits','explorer les citations','résumer un paper'],4.6,'https://www.semanticscholar.org','🎓','#1a73e8',19000,'500K+'),
  t('research-rabbit','Research Rabbit','Outil de découverte de littérature académique avec visualisation en graphe et recommandations IA.','data','recherche-academique','free','Gratuit',['découvrir des articles connexes','visualiser un réseau de citations','organiser ma bibliographie'],4.6,'https://www.researchrabbit.ai','🐇','#7c3aed',16000,'200K+'),
  t('scite-ai','Scite AI','Analysez comment les articles scientifiques sont cités : soutien, contradiction ou mention simple.','data','recherche-academique','freemium','Gratuit / 20$/mois',['vérifier si une étude est répliquée','analyser la qualité d\'une citation','évaluer la fiabilité d\'un paper'],4.5,'https://scite.ai','📎','#f59e0b',12000,'100K+'),
  t('explainpaper','Explainpaper','Téléchargez un article académique et obtenez des explications claires des passages complexes.','data','recherche-academique','freemium','Gratuit / 12$/mois',['comprendre un article scientifique complexe','simplifier le jargon académique','apprendre depuis des papers'],4.5,'https://www.explainpaper.com','📖','#10b981',11000,'100K+'),
  t('chatpdf','ChatPDF','Importez n\'importe quel PDF et discutez directement avec son contenu grâce à l\'IA.','data','documents','freemium','Gratuit / 5$/mois',['lire un PDF avec l\'IA','résumer un document','poser des questions sur un rapport'],4.5,'https://www.chatpdf.com','📄','#ef4444',38000,'5M+'),
  t('humata-ai','Humata AI','Analysez des fichiers complexes (PDF, Word) et obtenez des réponses sourcées instantanément.','data','documents','freemium','Gratuit / 14.99$/mois',['analyser un contrat juridique','résumer un rapport annuel','comparer plusieurs documents'],4.5,'https://www.humata.ai','🔍','#6366f1',16000,'300K+'),

  // ── Cybersécurité ─────────────────────────────────────────────────────────
  t('darktrace','Darktrace','IA de cybersécurité autonome qui détecte et répond aux cybermenaces en temps réel.','data','securite','paid','Sur devis',['détecter des intrusions en temps réel','protéger mon réseau avec l\'IA','répondre automatiquement aux cyberattaques'],4.7,'https://darktrace.com','🛡️','#dc2626',24000,'9000+'),
  t('crowdstrike-ai','CrowdStrike Falcon AI','Plateforme EDR/XDR avec IA Charlotte qui détecte et neutralise les menaces avancées.','data','securite','paid','Sur devis',['protection endpoint IA','détecter les ransomwares','répondre aux incidents de sécurité'],4.7,'https://www.crowdstrike.com','🦅','#e2001a',19000,'23000+'),
  t('sentinelone-ai','SentinelOne AI','Protection autonome des endpoints avec IA prédictive et réponse en temps réel.','data','securite','paid','Sur devis',['protéger les endpoints','prévenir les attaques zero-day','automatiser la réponse aux incidents'],4.6,'https://www.sentinelone.com','🔒','#7c3aed',15000,'11000+'),
  t('vectra-ai','Vectra AI','Détection des menaces réseau et cloud avec IA comportementale pour stopper les attaques.','data','securite','paid','Sur devis',['détecter des anomalies réseau','chasser les menaces internes','sécuriser le cloud avec l\'IA'],4.5,'https://www.vectra.ai','👁️','#1d4ed8',11000,'2000+'),
  t('snyk-ai','Snyk AI','Plateforme de sécurité pour développeurs qui détecte les vulnérabilités dans le code et les dépendances.','data','securite','freemium','Gratuit / 25$/mois',['scanner les vulnérabilités de mon code','sécuriser mes dépendances NPM','intégrer la sécurité dans le CI/CD'],4.7,'https://snyk.io','🔐','#4c4a73',29000,'500K+'),
  t('wiz-ai','Wiz','Plateforme de sécurité cloud IA qui scanne toute l\'infrastructure pour trouver les risques.','data','securite','paid','Sur devis',['sécuriser mon cloud AWS/Azure/GCP','trouver des mauvaises configurations','gérer les risques cloud'],4.7,'https://www.wiz.io','🌩️','#00adef',16000,'35000+'),
  t('lacework-ai','Lacework AI','Sécurité cloud avec détection d\'anomalies comportementales par machine learning.','data','securite','paid','Sur devis',['détecter des comportements anormaux','audit de conformité cloud','sécuriser les workloads cloud'],4.4,'https://www.lacework.com','🔍','#6366f1',8000,'5000+'),
  t('securonix-ai','Securonix AI','SIEM/UEBA avec IA pour détecter les menaces internes et les attaques avancées.','data','securite','paid','Sur devis',['détecter des menaces internes','analyser les logs de sécurité','conformité SOC avec l\'IA'],4.4,'https://www.securonix.com','🛡️','#f43f5e',7000,'1000+'),
  t('exabeam-ai','Exabeam AI','Analyse comportementale des entités et utilisateurs pour détecter les menaces avancées.','data','securite','paid','Sur devis',['analyse comportementale des utilisateurs','détecter les comptes compromis','investigation d\'incidents de sécurité'],4.4,'https://www.exabeam.com','🔮','#a855f7',7000,'1000+'),
  t('cyberark-ai','CyberArk AI','Gestion des identités et accès privilégiés avec IA pour protéger les comptes critiques.','data','securite','paid','Sur devis',['sécuriser les comptes admin','gérer les accès privilégiés','détecter les abus de comptes'],4.5,'https://www.cyberark.com','🔑','#dc2626',9000,'7000+'),
]

export default tools
