import { t } from './catalog-types'
import type { CatalogTool } from './catalog-types'

const tools: CatalogTool[] = [
  // ── Assistants de code IA ────────────────────────────────────────────────
  t('github-copilot','GitHub Copilot','L\'assistant IA de codage le plus utilisé au monde, intégré dans VS Code et tous les IDE majeurs.','code','assistant','paid','10$/mois',['compléter mon code automatiquement','générer des fonctions','écrire des tests unitaires','suggérer du code en temps réel'],4.8,'https://github.com/features/copilot','🤖','#24292e',89000,'1M+',true),
  t('cursor','Cursor','L\'IDE IA qui comprend tout votre codebase pour vous aider à coder, refactoriser et déboguer.','code','assistant','freemium','Gratuit / 20$/mois',['coder avec l\'IA dans un IDE','refactoriser du code','comprendre un codebase complexe','corriger des bugs automatiquement'],4.9,'https://cursor.sh','⚡','#7c3aed',76000,'500K+',true),
  t('tabnine','Tabnine','Autocomplétion de code IA qui fonctionne dans tous les IDE et s\'adapte à votre style de code.','code','assistant','freemium','Gratuit / 12$/mois',['autocomplétion de code','suggestions intelligentes','adapter l\'IA à mon code privé'],4.6,'https://www.tabnine.com','🧩','#3b82f6',34000,'1M+'),
  t('codeium','Codeium','Assistant de code IA gratuit avec autocomplétion, chat et recherche dans 70+ langages.','code','assistant','free','Gratuit',['coder gratuitement avec l\'IA','complétion de code rapide','support multi-langages'],4.7,'https://codeium.com','💡','#06b6d4',41000,'500K+',true),
  t('amazon-codewhisperer','Amazon CodeWhisperer','Génération de code IA par AWS, optimisé pour les services cloud Amazon.','code','assistant','freemium','Gratuit / 19$/mois',['coder pour AWS','intégrer des services cloud','générer du code sécurisé'],4.5,'https://aws.amazon.com/codewhisperer','☁️','#f59e0b',28000,'200K+'),
  t('replit-ai','Replit AI','Plateforme de code en ligne avec IA intégrée pour créer des apps directement dans le navigateur.','code','nocode','freemium','Gratuit / 7$/mois',['coder dans le navigateur','créer une app sans installer quoi que ce soit','déployer une application rapidement'],4.6,'https://replit.com','🌐','#f97316',52000,'20M+',true),
  t('bolt-new','Bolt.new','Créez des applications web complètes en décrivant ce que vous voulez en langage naturel.','code','nocode','freemium','Gratuit / 20$/mois',['créer une application web sans coder','générer une app fullstack','déployer un site instantanément'],4.8,'https://bolt.new','⚡','#7c3aed',67000,'300K+',true),
  t('v0-dev','v0 by Vercel','Générateur d\'interfaces React et Tailwind CSS à partir de descriptions textuelles.','code','nocode','freemium','Gratuit / 10$/mois',['générer une interface utilisateur','créer des composants React','concevoir une UI avec du texte'],4.7,'https://v0.dev','🎨','#000000',58000,'200K+',true),
  t('lovable-dev','Lovable','Créez des applications fullstack en quelques minutes grâce à l\'IA conversationnelle.','code','nocode','freemium','Gratuit / 25$/mois',['créer une app fullstack','développer sans être développeur','prototyper rapidement une idée'],4.7,'https://lovable.dev','❤️','#ec4899',43000,'100K+'),
  t('devin-ai','Devin','Le premier ingénieur logiciel IA autonome capable de gérer des tâches de bout en bout.','code','assistant','paid','Sur devis',['déléguer un projet à une IA','automatiser le développement logiciel','résoudre des issues GitHub automatiquement'],4.4,'https://cognition.ai','🦾','#6d28d9',38000,'10K+'),
  t('aider-ai','Aider','Assistant de codage en ligne de commande qui édite vos fichiers en collaboration avec Claude ou GPT.','code','assistant','free','Open source gratuit',['coder en ligne de commande avec l\'IA','modifier plusieurs fichiers simultanément','intégrer GPT dans mon terminal'],4.6,'https://aider.chat','💻','#10b981',22000,'50K+'),
  t('continue-dev','Continue.dev','Extension VS Code open source qui connecte n\'importe quel LLM à votre environnement de dev.','code','assistant','free','Open source gratuit',['utiliser Claude dans VS Code','connecter un modèle local à mon IDE','personnaliser mon assistant de code'],4.5,'https://continue.dev','🔗','#3b82f6',18000,'100K+'),
  t('cody-sourcegraph','Cody (Sourcegraph)','Assistant IA qui comprend la totalité de votre codebase grâce au moteur de recherche Sourcegraph.','code','assistant','freemium','Gratuit / 9$/mois',['comprendre un grand codebase','chercher dans tout le code source','documenter du code existant'],4.5,'https://sourcegraph.com/cody','🔍','#a855f7',16000,'200K+'),
  t('phind-ai','Phind','Moteur de recherche IA spécialisé pour les développeurs avec génération de code et explications.','code','recherche','freemium','Gratuit / 17$/mois',['chercher des solutions de code','déboguer avec des explications','trouver des exemples de code'],4.7,'https://www.phind.com','🔎','#06b6d4',31000,'1M+'),
  t('blackbox-ai','Blackbox AI','Autocomplétion et recherche de code IA disponible dans tous les IDE majeurs, gratuit.','code','assistant','freemium','Gratuit / 12.99$/mois',['autocomplétion gratuite','extraire du code depuis une vidéo','générer du code depuis une image'],4.4,'https://www.blackbox.ai','⬛','#1f2937',27000,'1M+'),
  t('warp-terminal','Warp','Terminal nouvelle génération avec IA intégrée pour exécuter des commandes en langage naturel.','code','terminal','freemium','Gratuit / 16$/mois',['utiliser le terminal avec l\'IA','exécuter des commandes en langage naturel','déboguer des erreurs de terminal'],4.7,'https://www.warp.dev','🖥️','#0f172a',33000,'500K+'),
  t('pieces-app','Pieces.app','Gestionnaire de snippets de code IA qui organise, enrichit et retrouve vos bouts de code.','code','productivite','freemium','Gratuit / 10$/mois',['sauvegarder des snippets de code','retrouver du code déjà écrit','organiser ma bibliothèque de code'],4.4,'https://pieces.app','🧩','#f97316',12000,'200K+'),

  // ── Plateformes IA / APIs ────────────────────────────────────────────────
  t('google-ai-studio','Google AI Studio','Plateforme gratuite pour expérimenter avec Gemini et créer des prototypes d\'applications IA.','code','plateforme','free','Gratuit',['tester Gemini gratuitement','prototyper une app IA','créer un prompt structuré'],4.6,'https://aistudio.google.com','🧪','#4285f4',24000,'500K+'),
  t('openai-playground','OpenAI Playground','Interface web pour tester et expérimenter avec tous les modèles OpenAI (GPT-4, o1, etc.).','code','plateforme','paid','Pay as you go',['tester GPT-4','expérimenter avec les LLM','fine-tuner un modèle OpenAI'],4.6,'https://platform.openai.com/playground','🎮','#10a37f',29000,'1M+'),
  t('huggingface','Hugging Face','La plateforme open source de référence pour les modèles IA, datasets et spaces.','code','plateforme','free','Gratuit / Pro 9$/mois',['héberger un modèle IA','trouver des modèles open source','déployer une demo IA'],4.8,'https://huggingface.co','🤗','#f97316',71000,'5M+',true),
  t('replicate','Replicate','Déployez et utilisez des milliers de modèles IA via une API simple et unifiée.','code','plateforme','paid','Pay as you go',['utiliser Stable Diffusion via API','déployer un modèle custom','intégrer des modèles IA en production'],4.6,'https://replicate.com','♾️','#6366f1',26000,'500K+'),
  t('together-ai','Together AI','Infrastructure pour exécuter des LLM open source à grande vitesse et faible coût.','code','plateforme','paid','Pay as you go',['exécuter Llama rapidement','réduire les coûts d\'inférence IA','utiliser des modèles open source en production'],4.6,'https://www.together.ai','⚡','#7c3aed',19000,'100K+'),
  t('groq','Groq','Inférence ultra-rapide pour les LLM open source grâce à des puces LPU dédiées.','code','plateforme','freemium','Gratuit / Pay as you go',['obtenir des réponses IA ultra-rapides','inférence LLM en temps réel','utiliser Llama ou Mixtral rapidement'],4.7,'https://groq.com','🚀','#f43f5e',34000,'200K+',true),
  t('anthropic-api','Anthropic API','API Claude pour intégrer l\'intelligence de Claude dans vos applications professionnelles.','code','plateforme','paid','Pay as you go',['intégrer Claude dans mon app','créer un chatbot intelligent','analyser des documents par API'],4.8,'https://www.anthropic.com/api','🧠','#d97706',41000,'200K+'),
  t('openai-api','OpenAI API','API d\'OpenAI pour accéder à GPT-4, DALL-E, Whisper et tous les modèles phares.','code','plateforme','paid','Pay as you go',['intégrer GPT-4 dans mon app','générer des images par API','transcrire de l\'audio par API'],4.8,'https://platform.openai.com','🔮','#10a37f',58000,'1M+',true),
  t('mistral-api','Mistral AI API','API des modèles Mistral : Mixtral 8x7B, Mistral Large, et Codestral pour le code.','code','plateforme','paid','Pay as you go',['utiliser Mixtral par API','intégrer un LLM européen','coder avec Codestral'],4.6,'https://mistral.ai/api','🌬️','#ff7000',22000,'100K+'),
  t('aws-bedrock','Amazon Bedrock','Service AWS pour accéder et fine-tuner des modèles de fondation IA (Claude, Llama, Titan).','code','plateforme','paid','Pay as you go',['déployer des LLM sur AWS','fine-tuner un modèle fondation','sécuriser l\'IA en entreprise'],4.5,'https://aws.amazon.com/bedrock','☁️','#f59e0b',18000,'100K+'),
  t('azure-openai','Azure OpenAI Service','Accédez aux modèles OpenAI sur l\'infrastructure Microsoft Azure avec conformité enterprise.','code','plateforme','paid','Pay as you go',['utiliser GPT-4 en entreprise','déployer une IA conforme RGPD','intégrer OpenAI dans Azure'],4.5,'https://azure.microsoft.com/services/openai-service','☁️','#0078d4',24000,'500K+'),
  t('google-vertex-ai','Google Vertex AI','Plateforme MLOps de Google Cloud pour entraîner, déployer et gérer des modèles IA.','code','plateforme','paid','Pay as you go',['déployer des modèles ML en production','entraîner une IA sur Google Cloud','AutoML sans coder'],4.5,'https://cloud.google.com/vertex-ai','🔬','#4285f4',16000,'200K+'),

  // ── No-code / Low-code / Automatisation ──────────────────────────────────
  t('langchain','LangChain','Framework Python/JS pour créer des applications LLM avec chaînes, agents et mémoire.','code','framework','free','Open source gratuit',['créer un agent IA','chaîner des LLM','connecter un LLM à une base de données'],4.7,'https://langchain.com','🔗','#1c7c54',48000,'500K+',true),
  t('llamaindex','LlamaIndex','Framework pour indexer vos données et les connecter aux LLM (RAG et agents).','code','framework','free','Open source gratuit',['créer un chatbot sur mes données','connecter une base de données à un LLM','RAG sur des documents PDF'],4.6,'https://www.llamaindex.ai','🦙','#7c3aed',31000,'200K+'),
  t('flowise-ai','Flowise','Interface visuelle drag-and-drop pour créer des chaînes LangChain et des agents IA.','code','nocode','free','Open source gratuit',['créer un agent IA sans coder','construire un pipeline RAG visuellement','déployer un chatbot personnalisé'],4.6,'https://flowiseai.com','🌊','#3b82f6',27000,'100K+'),
  t('n8n-ai','n8n','Plateforme d\'automatisation open source avec nœuds IA pour connecter 400+ services.','code','automatisation','freemium','Gratuit self-hosted / 20$/mois cloud',['automatiser mes workflows','connecter mes apps avec l\'IA','créer des automatisations sans coder'],4.7,'https://n8n.io','⚙️','#f97316',43000,'400K+',true),
  t('zapier-ai','Zapier AI','Automatisez vos tâches répétitives avec l\'IA en connectant 6000+ applications.','code','automatisation','freemium','Gratuit / 19.99$/mois',['automatiser mes emails','connecter mes apps','créer des workflows automatiques'],4.6,'https://zapier.com/ai','⚡','#f97316',61000,'2M+',true),
  t('make-ai','Make (Integromat)','Plateforme d\'automatisation visuelle avancée avec modules IA pour des workflows complexes.','code','automatisation','freemium','Gratuit / 9$/mois',['automatiser des processus complexes','créer des scénarios multi-étapes','intégrer des apps avec des données complexes'],4.7,'https://www.make.com','🔄','#6d28d9',34000,'500K+'),
  t('retool-ai','Retool AI','Créez des outils internes et dashboards avec IA intégrée pour vos équipes.','code','nocode','freemium','Gratuit / 10$/mois',['créer un outil interne','construire un dashboard IA','développer une app admin rapidement'],4.6,'https://retool.com/ai','🛠️','#1d4ed8',19000,'200K+'),
  t('bubble-ai','Bubble AI','Plateforme no-code pour créer des applications web complètes avec IA intégrée.','code','nocode','freemium','Gratuit / 29$/mois',['créer une app web sans coder','construire un SaaS sans développeur','déployer une marketplace'],4.5,'https://bubble.io','💬','#0ea5e9',28000,'2M+'),
  t('dify-ai','Dify','Plateforme open source pour créer des applications LLM avec un éditeur visuel de workflows.','code','plateforme','freemium','Gratuit open source / Cloud 19$/mois',['créer une app LLM','orchestrer des agents IA','déployer un chatbot personnalisé'],4.6,'https://dify.ai','🔧','#9333ea',24000,'100K+'),
  t('stack-ai','Stack AI','Plateforme no-code pour construire et déployer des applications IA sans code.','code','nocode','freemium','Gratuit / 99$/mois',['créer une app IA sans coder','automatiser avec des LLM','construire un chatbot sur mes données'],4.5,'https://www.stack-ai.com','📚','#3b82f6',11000,'50K+'),
  t('vapi-ai','Vapi AI','Plateforme pour créer des agents vocaux IA et des callbots intelligents en quelques minutes.','code','vocal','paid','0.05$/min',['créer un agent vocal IA','automatiser des appels téléphoniques','construire un callbot intelligent'],4.6,'https://vapi.ai','📞','#ec4899',16000,'20K+'),
  t('relevance-ai','Relevance AI','Plateforme no-code pour créer des agents IA et automatiser des workflows complexes.','code','nocode','freemium','Gratuit / 19$/mois',['créer un agent IA sans coder','automatiser la prospection commerciale','analyser des données avec l\'IA'],4.5,'https://relevanceai.com','🤖','#7c3aed',14000,'30K+'),
  t('supabase-ai','Supabase AI','Base de données PostgreSQL avec embeddings vectoriels et IA intégrée pour les développeurs.','code','base-de-donnees','freemium','Gratuit / 25$/mois',['ajouter une recherche sémantique','stocker des embeddings','créer un RAG sur Postgres'],4.7,'https://supabase.com/ai','⚡','#3ecf8e',31000,'500K+'),
  t('vercel-ai-sdk','Vercel AI SDK','SDK officiel pour intégrer des LLM (OpenAI, Anthropic, Google) dans des apps Next.js.','code','framework','free','Open source gratuit',['intégrer un LLM dans Next.js','créer un streaming chat UI','connecter plusieurs modèles IA'],4.7,'https://sdk.vercel.ai','▲','#000000',22000,'200K+'),
  t('cohere','Cohere','API de LLM enterprise pour la recherche sémantique, la génération et la classification.','code','plateforme','freemium','Gratuit trial / Pay as you go',['recherche sémantique dans mes documents','classification de texte par IA','créer un chatbot enterprise'],4.5,'https://cohere.com','🌊','#39594d',16000,'100K+'),
  t('mutable-ai','Mutable AI','Refactoring et documentation de code automatiques grâce à l\'IA.','code','assistant','freemium','Gratuit / 19$/mois',['documenter automatiquement mon code','refactoriser avec l\'IA','améliorer la qualité de code'],4.3,'https://mutable.ai','✨','#8b5cf6',8000,'20K+'),
]

export default tools
